DCPROJ: src/SFEM.cpp File Reference
SFEM.cpp File Reference
#include <iostream>
#include <Eigen/Core>
#include <direct.h>
#include <iomanip>
#include <cmath>
#include "shapequad.h"
#include "gridmesh.h"
#include "elastmat2D.h"
#include "KLGalerkinRF.h"
#include "vonmises.h"
#include "druckerprager.h"
#include "elastoplastic2D.h"
#include "ludcmp.h"
#include <math.h>
#include "mesh.h"
#include "postprocess.h"
#include <algorithm>
#include <chrono>
#include <Eigen/SparseCholesky>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <vector>
#include "elastoplasticbase.h"
#include "slopeproject.h"
Typedefs
typedef Eigen::SparseMatrix< double > SpMat
typedef Eigen::Triplet< double > T
Functions
NRvector< MatDoub > FindEl (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt meshtopology, const VecDoub Vec, MatDoub hhat)
void OutPutFile (MatDoub &postdata, std::ofstream &file)
void OutPutFile1var (MatDoub &postdata, std::ofstream &file)
void OutPutFile4var (MatDoub &postdata, std::ofstream &file)
void OutPutPost (std::vector< std::vector< double >> &postdata, std::ofstream &file)
void OutPutPost (MatDoub &postdata, std::ofstream &file)
void OutPutPost (MatInt &postdata, std::ofstream &file)
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology, string filenameel, string filenamecoord)
std::vector< Int > vecstr_to_vecint (std::vector< string > vs)
std::vector< Doub > vecstr_to_vecdoub (std::vector< string > vs)
std::vector< std::vector< int > > LineTopology (std::vector< int > ids, Int order)
void ToMatInt (std::vector< std::vector< int >> in, MatInt &out)
template<class T >
std::vector< T > vecstr_to_vec (std::vector< string > vs)
void MonteCarloTalude2 ()
void MonteCarlo ()
std::vector< std::vector< double > > IterativeProcess (mesh *gmesh, MatDoub hhatinho, elastoplastic2D< druckerprager > *material, int ndesi, Doub dlamb0)
void ReadMatDoub (MatDoub &matdoub, std::string file)
void SolveEigen (MatDoub A, MatDoub b, MatDoub &x)
void SolveNR3 (MatDoub A, MatDoub b, MatDoub &x)
void SolveEigen2 (MatDoub A, MatDoub b, MatDoub &x)
std::vector< std::vector< double > > IterativeSlopeStabilityEig (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > *material)
void solvedeterm (string nodestr, string elsstr, MatDoub hhatinho)
void IterativeCho (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > *material)
void solvedetermtest (string nodestr, string elsstr, MatDoub hhatinho, Doub c, Doub phi, Doub gamma)
void InserBC (MatDoub &KG, MatDoub &R, MatDoub &FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material *mat)
Doub computelamda (MatDoub &dwb, MatDoub &dws, MatDoub &dw, Doub &l)
std::vector< std::vector< double > > IterativeProcessShearRed (mesh *gmesh, MatDoub hhatinho, elastoplastic2D< druckerprager > *material)
void IterativeProcessShearRed2 (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > *material)
std::vector< std::vector< double > > IterativeProcessShearRed3 (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > *material)
void SolveShearRed (string nodestr, string elsstr, MatDoub hhatinho, Doub c, Doub phi, Doub gamma)
std::vector< std::vector< double > > IterativeProcessShearRed (mesh *mesh)
void findbcids (mesh *gmesh, std::vector< std::vector< int >> &idsvector)
std::vector< std::vector< double > > IterativeProcess (mesh *gmesh, Int ndesi, Doub dlamb0)
void CreateRandomField ()
void ExecuteMonteCarlo ()
int main2 ()
std::vector< std::vector< double > > IterativeProcessShearRed (mesh *gmesh, elastoplastic2D< druckerprager > *material)
std::vector< Doub > vecstr_to_vecdoub2 (std::vector< string > vs)
void solvedeterm (string nodestr, string elsstr)
Variables
bool flag
int cccccccc
Typedef Documentation
SpMat
typedef Eigen::SparseMatrix<double> SpMat
Definition at line 30 of file SFEM.cpp.
T
typedef Eigen::Triplet<double> T
Definition at line 31 of file SFEM.cpp.
Function Documentation
computelamda()
Doub computelamda (MatDoub & dwb, MatDoub & dws, MatDoub & dw, Doub & l)
Definition at line 1403 of file SFEM.cpp.
References NRmatrix< T >::nrows().
Referenced by IterativeProcess(), and IterativeProcessShearRed3().
CreateRandomField()
void CreateRandomField ()
Definition at line 455 of file SFEM.cpp.
References OutPutPost(), ReadMesh(), and KLGalerkinRF::SolveGenEigValProblem().
ExecuteMonteCarlo()
void ExecuteMonteCarlo ()
Definition at line 450 of file SFEM.cpp.
findbcids()
void findbcids (mesh * gmesh, std::vector< std::vector< int >> & idsvector)
Definition at line 516 of file SFEM.cpp.
References gridmesh::FindIdsInPath(), mesh::GetAllCoords(), mesh::GetMeshTopology(), and gridmesh::Line().
Referenced by IterativeProcess(), and IterativeProcessShearRed().
FindEl()
NRvector< MatDoub > FindEl (const std::vector< std::vector< std::vector< Doub > > > & allcoords, const MatInt meshtopology, const VecDoub Vec, MatDoub hhat)
Matrix inversion routine.
Definition at line 2241 of file SFEM.cpp.
References NRvector< T >::assign(), NRmatrix< T >::assign(), gridmesh::GetElCoords(), NRmatrix< T >::Mult(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), NRvector< T >::resize(), shapequad::shapes(), NRvector< T >::size(), and NRmatrix< T >::Transpose().
InserBC()
void InserBC (MatDoub & KG, MatDoub & R, MatDoub & FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material * mat)
Definition at line 1423 of file SFEM.cpp.
References material::DirichletBC().
Referenced by IterativeProcess(), IterativeProcessShearRed(), IterativeProcessShearRed2(), and IterativeProcessShearRed3().
IterativeCho()
void IterativeCho (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > * material)
Definition at line 2427 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), NRmatrix< T >::CopyFromVector(), material::DirichletBC(), gridmesh::FindIdsInPath(), gridmesh::Line(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), NRmatrix< T >::Print(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
Referenced by solvedeterm().
IterativeProcess() [1/2]
std::vector< std::vector< double > > IterativeProcess (mesh * gmesh, Int ndesi, Doub dlamb0)
Definition at line 924 of file SFEM.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), cccccccc, computelamda(), NRmatrix< T >::CopyFromVector(), findbcids(), mesh::fmaterial, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeProcess() [2/2]
std::vector< std::vector< double > > IterativeProcess (mesh * gmesh, MatDoub hhatinho, elastoplastic2D< druckerprager > * material, int ndesi, Doub dlamb0)
Definition at line 1169 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), cccccccc, computelamda(), NRmatrix< T >::CopyFromVector(), findbcids(), mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), InserBC(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
Referenced by main2(), MonteCarlo(), and solvedetermtest().
IterativeProcessShearRed() [1/3]
std::vector<std::vector<double> > IterativeProcessShearRed (mesh * gmesh, elastoplastic2D< druckerprager > * material)
Definition at line 591 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), findbcids(), mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), InserBC(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), SolveEigen2(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeProcessShearRed() [2/3]
std::vector<std::vector<double> > IterativeProcessShearRed (mesh * gmesh, MatDoub hhatinho, elastoplastic2D< druckerprager > * material)
Referenced by main2().
IterativeProcessShearRed() [3/3]
std::vector< std::vector< double > > IterativeProcessShearRed (mesh * mesh)
Definition at line 751 of file SFEM.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), findbcids(), mesh::fmaterial, mesh::GetAllCoords(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetMat(), material::SetMatConstants(), SolveEigen(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeProcessShearRed2()
void IterativeProcessShearRed2 (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > * material)
Definition at line 3558 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), gridmesh::FindIdsInPath(), InserBC(), gridmesh::Line(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetMat(), SolveEigen2(), material::UpdateBodyForce(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeProcessShearRed3()
std::vector< std::vector< double > > IterativeProcessShearRed3 (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > * material)
Definition at line 3738 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), cccccccc, computelamda(), NRmatrix< T >::CopyFromVector(), gridmesh::FindIdsInPath(), InserBC(), gridmesh::Line(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeSlopeStabilityEig()
std::vector< std::vector< double > > IterativeSlopeStabilityEig (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub hhatinho, elastoplastic2D< druckerprager > * material)
Definition at line 2784 of file SFEM.cpp.
References material::Assemble(), NRmatrix< T >::assign(), NRmatrix< T >::CopyFromVector(), material::DirichletBC(), gridmesh::FindIdsInPath(), gridmesh::Line(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), NRmatrix< T >::Print(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
Referenced by MonteCarloTalude2().
LineTopology()
std::vector< std::vector< int > > LineTopology (std::vector< int > ids, Int order)
Definition at line 2401 of file SFEM.cpp.
main2()
int main2 ()
string nodestr = "D:/DClib/meshes/nos-297.txt"; string elsstr = "D:/DClib/meshes/els-297.txt";
Definition at line 83 of file SFEM.cpp.
References NRmatrix< T >::CopyFromVector(), elastoplastic2D< YC >::fYC, elastoplastic2D< YC >::GetSolution(), IterativeProcess(), IterativeProcessShearRed(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), NRmatrix< T >::nrows(), OutPutFile1var(), OutPutPost(), shapequad::pointsandweigths(), elastoplastic2D< YC >::PostProcess(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), ReadMatDoub(), ReadMesh(), elastoplastic2D< YC >::ResetMat(), mesh::SetHhat(), elastoplastic2D< YC >::SetMemory(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
MonteCarlo()
void MonteCarlo ()
Definition at line 1459 of file SFEM.cpp.
References NRmatrix< T >::CopyFromVector(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), elastoplastic2D< YC >::GetSolution(), IterativeProcess(), NRmatrix< T >::nrows(), OutPutFile1var(), OutPutPost(), shapequad::pointsandweigths(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), ReadMesh(), mesh::SetHhat(), elastoplastic2D< YC >::SetMatConstants(), elastoplastic2D< YC >::SetMemory(), elastoplastic2D< YC >::SetRandomField(), NRvector< T >::size(), KLGalerkinRF::SolveGenEigValProblem(), and elastoplastic2D< YC >::UpdateBodyForce().
MonteCarloTalude2()
void MonteCarloTalude2 ()
coordsvec[0] = 32.5;
solcount[5] = diff2;
Definition at line 3087 of file SFEM.cpp.
References NRmatrix< T >::CopyFromVector(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), IterativeSlopeStabilityEig(), NRmatrix< T >::nrows(), OutPutFile(), OutPutFile1var(), OutPutPost(), shapequad::pointsandweigths(), material::PostProcess(), material::PostProcessIntegrationPointVar(), ReadMesh(), material::SetMemory(), material::SetRandomField(), NRvector< T >::size(), KLGalerkinRF::SolveGenEigValProblem(), and material::UpdateBodyForce().
OutPutFile()
void OutPutFile (MatDoub & postdata, std::ofstream & file)
Definition at line 1828 of file SFEM.cpp.
References NRmatrix< T >::nrows().
Referenced by IterativeCho(), IterativeProcess(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), and MonteCarloTalude2().
OutPutFile1var()
void OutPutFile1var (MatDoub & postdata, std::ofstream & file)
Definition at line 1841 of file SFEM.cpp.
References NRmatrix< T >::nrows().
Referenced by main2(), MonteCarlo(), and MonteCarloTalude2().
OutPutFile4var()
void OutPutFile4var (MatDoub & postdata, std::ofstream & file)
Definition at line 1854 of file SFEM.cpp.
References NRmatrix< T >::nrows().
OutPutPost() [1/3]
void OutPutPost (MatDoub & postdata, std::ofstream & file)
Definition at line 1882 of file SFEM.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
OutPutPost() [2/3]
void OutPutPost (MatInt & postdata, std::ofstream & file)
Definition at line 1895 of file SFEM.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
OutPutPost() [3/3]
void OutPutPost (std::vector< std::vector< double >> & postdata, std::ofstream & file)
Definition at line 1868 of file SFEM.cpp.
Referenced by CreateRandomField(), IterativeCho(), IterativeProcess(), IterativeProcessShearRed(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), main2(), MonteCarlo(), MonteCarloTalude2(), solvedeterm(), and solvedetermtest().
ReadMatDoub()
void ReadMatDoub (MatDoub & matdoub, std::string file)
Definition at line 2037 of file SFEM.cpp.
References NRmatrix< T >::CopyFromVector(), and vecstr_to_vecdoub2().
Referenced by main2().
ReadMesh()
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology, string filenameel, string filenamecoord)
Definition at line 1909 of file SFEM.cpp.
References NRmatrix< T >::CopyFromVector(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), vecstr_to_vecdoub(), and vecstr_to_vecint().
Referenced by CreateRandomField(), main2(), MonteCarlo(), MonteCarloTalude2(), solvedeterm(), and solvedetermtest().
solvedeterm() [1/2]
void solvedeterm (string nodestr, string elsstr)
Definition at line 2726 of file SFEM.cpp.
References IterativeCho(), NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), ReadMesh(), material::SetMemory(), and material::UpdateBodyForce().
solvedeterm() [2/2]
void solvedeterm (string nodestr, string elsstr, MatDoub hhatinho)
solvedetermtest()
void solvedetermtest (string nodestr, string elsstr, MatDoub hhatinho, Doub c, Doub phi, Doub gamma)
Definition at line 2644 of file SFEM.cpp.
References mesh::GetMeshNodes(), mesh::GetMeshTopology(), IterativeProcess(), NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), material::PostProcess(), material::PostProcessIntegrationPointVar(), ReadMesh(), material::SetMemory(), and material::UpdateBodyForce().
SolveEigen()
void SolveEigen (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 2380 of file SFEM.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeCho(), IterativeProcess(), IterativeProcessShearRed(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
SolveEigen2()
void SolveEigen2 (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 2336 of file SFEM.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeProcessShearRed(), and IterativeProcessShearRed2().
SolveNR3()
void SolveNR3 (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 2363 of file SFEM.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and Cholesky::solve().
SolveShearRed()
void SolveShearRed (string nodestr, string elsstr, MatDoub hhatinho, Doub c, Doub phi, Doub gamma)
ToMatInt()
void ToMatInt (std::vector< std::vector< int >> in, MatInt & out)
Definition at line 2419 of file SFEM.cpp.
References NRmatrix< T >::assign().
vecstr_to_vec()
template<class T > std::vector<T> vecstr_to_vec (std::vector< string > vs)
Definition at line 2024 of file SFEM.cpp.
vecstr_to_vecdoub()
std::vector<Doub> vecstr_to_vecdoub (std::vector< string > vs)
Definition at line 1997 of file SFEM.cpp.
Referenced by ReadMesh().
vecstr_to_vecdoub2()
std::vector<Doub> vecstr_to_vecdoub2 (std::vector< string > vs)
Definition at line 2010 of file SFEM.cpp.
Referenced by ReadMatDoub().
vecstr_to_vecint()
std::vector<Int> vecstr_to_vecint (std::vector< string > vs)
Definition at line 1984 of file SFEM.cpp.
Referenced by ReadMesh().
Variable Documentation
cccccccc
int cccccccc
Definition at line 513 of file SFEM.cpp.
Referenced by IterativeProcess(), and IterativeProcessShearRed3().
flag
bool flag
Definition at line 59 of file SFEM.cpp.
Referenced by druckerprager::FindMinimum(), and rtsafe().