DCPROJ: VTKGraphMesh Class Reference
VTKGraphMesh Class Reference
#include <vtkmesh.h>
Public Member Functions
VTKGraphMesh (mesh *cmesh, int dimension, std::vector< std::string > &scalnames, const std::vector< std::string > &vecnames, std::string FileName)
Constructor for graphical mesh using VTK format with tensor variables.
void DrawNodes ()
void DrawConnectivity ()
void DrawSolution (Int step, Doub time)
MatInt GetMeshTopologyVTK ()
Protected Attributes
std::ofstream fOutFile
NRmatrix< Doub > fdata
mesh * fmesh
std::string fFileName
Int fdim
std::vector< std::string > fVecNames
std::vector< std::string > fScalNames
Detailed Description
Definition at line 8 of file vtkmesh.h.
Constructor & Destructor Documentation
VTKGraphMesh()
VTKGraphMesh::VTKGraphMesh (mesh * cmesh, int dimension, std::vector< std::string > & scalnames, const std::vector< std::string > & vecnames, std::string FileName)
Constructor for graphical mesh using VTK format with tensor variables.
Definition at line 6 of file vtkmesh.cpp.
References fdata, fdim, fFileName, mesh::fmaterial, fmesh, fScalNames, fVecNames, and material::GetSolution().
Member Function Documentation
DrawConnectivity()
void VTKGraphMesh::DrawConnectivity ()
DrawNodes()
void VTKGraphMesh::DrawNodes ()
DrawSolution()
void VTKGraphMesh::DrawSolution (Int step, Doub time)
Definition at line 16 of file vtkmesh.cpp.
References material::ComputePhi(), material::ComputeSolAndDSol(), fdim, fFileName, mesh::fmaterial, fmesh, fOutFile, fVecNames, mesh::GetHhat(), mesh::GetMeshNodes(), GetMeshTopologyVTK(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRtensor< T >::XX(), NRtensor< T >::XY(), and NRtensor< T >::YY().
Referenced by pressurizedhole::IterativeProcess(), and slopeproject::IterativeProcess().
GetMeshTopologyVTK()
MatInt VTKGraphMesh::GetMeshTopologyVTK () inline
Definition at line 19 of file vtkmesh.h.
References fdim, fmesh, mesh::GetMeshTopology(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by DrawSolution().
Member Data Documentation
fdata
NRmatrix<Doub> VTKGraphMesh::fdata protected
Definition at line 79 of file vtkmesh.h.
Referenced by VTKGraphMesh().
fdim
Int VTKGraphMesh::fdim protected
Definition at line 82 of file vtkmesh.h.
Referenced by DrawSolution(), GetMeshTopologyVTK(), and VTKGraphMesh().
fFileName
std::string VTKGraphMesh::fFileName protected
Definition at line 81 of file vtkmesh.h.
Referenced by DrawSolution(), and VTKGraphMesh().
fmesh
mesh* VTKGraphMesh::fmesh protected
Definition at line 80 of file vtkmesh.h.
Referenced by DrawSolution(), GetMeshTopologyVTK(), and VTKGraphMesh().
fOutFile
std::ofstream VTKGraphMesh::fOutFile protected
Definition at line 78 of file vtkmesh.h.
Referenced by DrawSolution().
fScalNames
std::vector<std::string> VTKGraphMesh::fScalNames protected
Definition at line 84 of file vtkmesh.h.
Referenced by VTKGraphMesh().
fVecNames
std::vector<std::string> VTKGraphMesh::fVecNames protected
Definition at line 83 of file vtkmesh.h.
Referenced by DrawSolution(), and VTKGraphMesh().
The documentation for this class was generated from the following files:
src/vtkmesh.h
src/vtkmesh.cpp