DCPROJ: vonmises Class Reference
vonmises Class Reference
#include <vonmises.h>
Public Member Functions
vonmises (Doub young, Doub nu, Doub sigy)
vonmises ()
~vonmises ()
void closestpointproj (NRtensor< Doub > epst, NRtensor< Doub > epsp, NRtensor< Doub > &projstress, NRtensor< Doub > &projstrain, MatDoub &Dep, Doub &projgamma)
Doub yield (Doub J2)
MatDoub GetElasticMatrix ()
MatDoub GetInverseElasticMatrix ()
MatDoub F1HWCylVonMises (Doub xisol, Doub rho, Doub betasol)
MatDoub HW (MatDoub sig)
MatDoub stressrecosntruction (MatDoub val, MatDoub vec)
MatDoub dadsig (NRtensor< Doub > sigprojvoigt)
MatDoub P ()
Doub phi (NRtensor< Doub > epse)
void setup (Doub young, Doub nu, Doub sigy)
void GetElasticParameters (Doub young, Doub nu, Doub sigy, Doub K, Doub G)
void updateatributes (NRvector< MatDoub > mult)
void restoreoriginalatributes ()
void GetMatConstants (NRvector< Doub > &consts)
void SetMatConstants (NRvector< Doub > &consts)
void reset ()
Public Attributes
Doub fyoung
Doub fnu
Doub fyoung0
Doub fnu0
Private Attributes
Doub fsigy0
Doub fsigy
Doub fK
Doub fG
Additional Inherited Members
Private Member Functions inherited from elastoplasticbase
~elastoplasticbase ()
Detailed Description
Definition at line 8 of file vonmises.h.
Constructor & Destructor Documentation
vonmises() [1/2]
vonmises::vonmises (Doub young, Doub nu, Doub sigy)
Definition at line 8 of file vonmises.cpp.
References fG, fK, fnu, fsigy, and fyoung.
vonmises() [2/2]
vonmises::vonmises ()
Definition at line 17 of file vonmises.cpp.
~vonmises()
vonmises::~vonmises ()
Definition at line 22 of file vonmises.cpp.
Member Function Documentation
closestpointproj()
void vonmises::closestpointproj (NRtensor< Doub > epst, NRtensor< Doub > epsp, NRtensor< Doub > & projstress, NRtensor< Doub > & projstrain, MatDoub & Dep, Doub & projgamma) virtual
Implements elastoplasticbase.
Definition at line 26 of file vonmises.cpp.
References NRtensor< T >::ComputeS(), dadsig(), NRtensor< T >::EigenSystem(), F1HWCylVonMises(), NRmatrix< T >::FromFullToVoigt(), NRtensor< T >::FromNRmatrixToTensor(), NRtensor< T >::FromTensorToNRmatrix(), GetElasticMatrix(), GetInverseElasticMatrix(), HW(), NRtensor< T >::I1(), LUdcmp::inverse(), NRtensor< T >::J2(), NRmatrix< T >::Mult(), NRtensor< T >::Norm(), NRmatrix< T >::nrows(), stressrecosntruction(), NRmatrix< T >::Transpose(), and yield().
dadsig()
MatDoub vonmises::dadsig (NRtensor< Doub > sigprojvoigt) virtual
Implements elastoplasticbase.
Definition at line 158 of file vonmises.cpp.
References NRtensor< T >::ComputeS(), NRtensor< T >::FromTensorToNRmatrix(), NRtensor< T >::I1(), NRtensor< T >::J2(), NRmatrix< T >::Mult(), P(), and NRmatrix< T >::Transpose().
Referenced by closestpointproj().
F1HWCylVonMises()
MatDoub vonmises::F1HWCylVonMises (Doub xisol, Doub rho, Doub betasol)
Definition at line 241 of file vonmises.cpp.
References fsigy.
Referenced by closestpointproj().
GetElasticMatrix()
MatDoub vonmises::GetElasticMatrix () virtual
Implements elastoplasticbase.
Definition at line 202 of file vonmises.cpp.
References fG, and fK.
Referenced by closestpointproj(), and phi().
GetElasticParameters()
void vonmises::GetElasticParameters (Doub young, Doub nu, Doub sigy, Doub K, Doub G) inline
Definition at line 50 of file vonmises.h.
References fG, fK, fnu, fsigy, and fyoung.
GetInverseElasticMatrix()
MatDoub vonmises::GetInverseElasticMatrix () virtual
Implements elastoplasticbase.
Definition at line 215 of file vonmises.cpp.
References fG, and fK.
Referenced by closestpointproj().
GetMatConstants()
void vonmises::GetMatConstants (NRvector< Doub > & consts) inline virtual
Implements elastoplasticbase.
Definition at line 71 of file vonmises.h.
References NRvector< T >::assign(), fnu, fsigy, and fyoung.
HW()
MatDoub vonmises::HW (MatDoub sig) virtual
Implements elastoplasticbase.
Definition at line 250 of file vonmises.cpp.
Referenced by closestpointproj().
P()
MatDoub vonmises::P () virtual
Implements elastoplasticbase.
Definition at line 228 of file vonmises.cpp.
Referenced by dadsig().
phi()
Doub vonmises::phi (NRtensor< Doub > epse) inline
Definition at line 25 of file vonmises.h.
References NRtensor< T >::FromNRmatrixToTensor(), NRtensor< T >::FromTensorToNRmatrix(), GetElasticMatrix(), NRtensor< T >::I1(), NRtensor< T >::J2(), NRmatrix< T >::Mult(), and yield().
reset()
void vonmises::reset () inline
Definition at line 81 of file vonmises.h.
References fG, fK, fnu, fnu0, fyoung, and fyoung0.
restoreoriginalatributes()
void vonmises::restoreoriginalatributes () inline
Definition at line 66 of file vonmises.h.
References fnu0, fsigy0, fyoung0, and setup().
SetMatConstants()
void vonmises::SetMatConstants (NRvector< Doub > & consts) inline virtual
Implements elastoplasticbase.
Definition at line 77 of file vonmises.h.
References setup().
setup()
void vonmises::setup (Doub young, Doub nu, Doub sigy) inline
Definition at line 42 of file vonmises.h.
References fG, fK, fnu, fsigy, and fyoung.
Referenced by pressurizedhole::CreateMatAndMesh(), beam3dtools::CreateMatAndMesh(), beam3dtools::CreateMatAndMeshCube(), restoreoriginalatributes(), SetMatConstants(), and updateatributes().
stressrecosntruction()
MatDoub vonmises::stressrecosntruction (MatDoub val, MatDoub vec) virtual
Implements elastoplasticbase.
Definition at line 177 of file vonmises.cpp.
References NRmatrix< T >::Transpose().
Referenced by closestpointproj().
updateatributes()
void vonmises::updateatributes (NRvector< MatDoub > mult) inline
Definition at line 58 of file vonmises.h.
References fnu, fnu0, fsigy, fsigy0, fyoung, fyoung0, and setup().
yield()
Doub vonmises::yield (Doub J2)
Definition at line 197 of file vonmises.cpp.
References fsigy.
Referenced by closestpointproj(), and phi().
Member Data Documentation
fG
Doub vonmises::fG private
Definition at line 98 of file vonmises.h.
Referenced by GetElasticMatrix(), GetElasticParameters(), GetInverseElasticMatrix(), reset(), setup(), and vonmises().
fK
Doub vonmises::fK private
Definition at line 97 of file vonmises.h.
Referenced by GetElasticMatrix(), GetElasticParameters(), GetInverseElasticMatrix(), reset(), setup(), and vonmises().
fnu
Doub vonmises::fnu
Definition at line 91 of file vonmises.h.
Referenced by GetElasticParameters(), GetMatConstants(), reset(), setup(), updateatributes(), and vonmises().
fnu0
Doub vonmises::fnu0
Definition at line 93 of file vonmises.h.
Referenced by reset(), restoreoriginalatributes(), and updateatributes().
fsigy
Doub vonmises::fsigy private
Definition at line 96 of file vonmises.h.
Referenced by F1HWCylVonMises(), GetElasticParameters(), GetMatConstants(), setup(), updateatributes(), vonmises(), and yield().
fsigy0
Doub vonmises::fsigy0 private
Definition at line 95 of file vonmises.h.
Referenced by restoreoriginalatributes(), and updateatributes().
fyoung
Doub vonmises::fyoung
Definition at line 90 of file vonmises.h.
Referenced by GetElasticParameters(), GetMatConstants(), reset(), setup(), updateatributes(), and vonmises().
fyoung0
Doub vonmises::fyoung0
Definition at line 92 of file vonmises.h.
Referenced by reset(), restoreoriginalatributes(), and updateatributes().
The documentation for this class was generated from the following files:
src/vonmises.h
src/vonmises.cpp