DCPROJ: beam3dtools Class Reference
beam3dtools Class Reference
#include <beam3dtools.h>
Public Member Functions
beam3dtools ()
Default constructor.
beam3dtools (mesh *inmesh)
Class constructor.
~beam3dtools ()
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology, string filenameel, string filenamecoord)
Read a mesh from files.
template<class T >
std::vector< T > vecstr_to_vec (std::vector< std::string > vs)
Convert a string vector to a generic type T vector.
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, NRmatrix< Doub > &elcoords)
Get a specific element coordinates.
void SolveEigenSparse (MatDoub A, MatDoub b, MatDoub &x)
Solve a sparse linear system with Eigen.
void SolveEigen (MatDoub A, MatDoub b, MatDoub &x)
Solve a linear system with Eigen.
void CreateMatAndMesh (mesh &getmesh, material &mat)
Creates the material and the mesh for a 3D beam.
void CreateMatAndMeshCube (mesh &getmesh, material &mat)
Creates the material and the mesh for a cube.
void SolveElasticBeam ()
Manages other methods of the class and solves a elastic beam.
void SolveElasticCube ()
Manages other methods of the class and solves a elastic cube.
void IterativeProcess ()
Manages other methods of the class and solves a elastoplastic beam. Perform the newtom method for a nonlinear material.
void InsertBC (mesh &mesh0, NRmatrix< Doub > &K, NRmatrix< Doub > &F)
Insert Dirichlet boundary conditions in the end of the beam (clamped in the end)
void InsertCubeBC (mesh &mesh0, NRmatrix< Doub > &K, NRmatrix< Doub > &F)
Insert boundary conditions for the cube. Clamped in the base and a uniform pressure in the top.
Doub computelamda (MatDoub &dwb, MatDoub &dws, MatDoub &dw, Doub &l)
Compute a arc-length multiplier.
void FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< std::vector< std::vector< Doub > > > &allcoords, MatInt &meshtopology, std::vector< int > &ids)
Search for a point, line or face ids.
void LoadBC (mesh &mesh0, NRmatrix< Doub > &K, NRmatrix< Doub > &F)
Insert boundary load BCs for the beam.
void OutPutFile (MatDoub &postdata, std::ofstream &file)
Write a file.
void OutPutPost (std::vector< std::vector< double >> &postdata, std::ofstream &file)
Write a file.
template<class T >
std::vector< T > vecstr_to_vec (std::vector< string > vs)
Private Attributes
mesh * fmesh
Detailed Description
Definition at line 23 of file beam3dtools.h.
Constructor & Destructor Documentation
beam3dtools() [1/2]
beam3dtools::beam3dtools ()
Default constructor.
Definition at line 3 of file beam3dtools.cpp.
beam3dtools() [2/2]
beam3dtools::beam3dtools (mesh * inmesh)
Class constructor.
Parameters
[in] mesh
Definition at line 8 of file beam3dtools.cpp.
References fmesh.
~beam3dtools()
beam3dtools::~beam3dtools ()
Definition at line 13 of file beam3dtools.cpp.
Member Function Documentation
computelamda()
Doub beam3dtools::computelamda (MatDoub & dwb, MatDoub & dws, MatDoub & dw, Doub & l)
Compute a arc-length multiplier.
Definition at line 18 of file beam3dtools.cpp.
References DebugStop, and NRmatrix< T >::nrows().
CreateMatAndMesh()
void beam3dtools::CreateMatAndMesh (mesh & getmesh, material & mat)
Creates the material and the mesh for a 3D beam.
Parameters
[out] getmesh finite element mesh
[out] mat material
Definition at line 174 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), elastoplastic3D< YC >::fYC, NRmatrix< T >::nrows(), shapehexahedron::pointsandweigths(), ReadMesh(), elastoplastic3D< YC >::SetMemory(), vonmises::setup(), and elastoplastic3D< YC >::UpdateBodyForce().
Referenced by IterativeProcess(), and SolveElasticBeam().
CreateMatAndMeshCube()
void beam3dtools::CreateMatAndMeshCube (mesh & getmesh, material & mat)
Creates the material and the mesh for a cube.
Parameters
[out] getmesh finite element mesh
[out] mat material
Definition at line 137 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), elastoplastic3D< YC >::fYC, NRmatrix< T >::nrows(), shapehexahedron::pointsandweigths(), ReadMesh(), elastoplastic3D< YC >::SetMemory(), vonmises::setup(), and elastoplastic3D< YC >::UpdateBodyForce().
Referenced by SolveElasticCube().
FindIds()
void beam3dtools::FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< std::vector< std::vector< Doub > > > & allcoords, MatInt & meshtopology, std::vector< int > & ids)
Search for a point, line or face ids.
Parameters
[in] constcoord Constcoorddata vector containig info about the face you want to search for the id. If its a face, it must contain any coodinate locate in the in the face. If its a line, two coordinates must match. If its a point, tree exact coordinates must match
[in] allcoords object containg the element topology and nodes
[in] meshtopology object containg the mesh topology
[out] ids object(point, line or face) id or ids
Definition at line 499 of file beam3dtools.cpp.
References GetElCoords(), NRmatrix< T >::nrows(), and NRvector< T >::size().
Referenced by InsertBC(), and InsertCubeBC().
GetElCoords()
void beam3dtools::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, NRmatrix< Doub > & elcoords)
Get a specific element coordinates.
Parameters
[in] allcoords object containg the element topology and nodes.
[in] el element that you want to get the coordinates
[out] elcoords element coordinates
Definition at line 556 of file beam3dtools.cpp.
References NRmatrix< T >::assign().
Referenced by FindIds().
InsertBC()
void beam3dtools::InsertBC (mesh & mesh0, NRmatrix< Doub > & K, NRmatrix< Doub > & F)
Insert Dirichlet boundary conditions in the end of the beam (clamped in the end)
Parameters
[in] K stiffness matrix.
[in] F load vector
[in] mesh0 FEM mesh
[out] K modified stiffness matrix with BCs.
[out] F modified load vector with BCs
Definition at line 215 of file beam3dtools.cpp.
References material::DirichletBC(), FindIds(), mesh::fmaterial, mesh::GetAllCoords(), and mesh::GetMeshTopology().
Referenced by IterativeProcess(), and SolveElasticBeam().
InsertCubeBC()
void beam3dtools::InsertCubeBC (mesh & mesh0, NRmatrix< Doub > & K, NRmatrix< Doub > & F)
Insert boundary conditions for the cube. Clamped in the base and a uniform pressure in the top.
Parameters
[in] K stiffness matrix.
[in] F load vector
[in] mesh0 FEM mesh
[out] K modified stiffness matrix with BCs.
[out] F modified load vector with BCs
Definition at line 259 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), material::DirichletBC(), FindIds(), mesh::fmaterial, mesh::GetAllCoords(), mesh::GetMeshTopology(), and NRmatrix< T >::nrows().
Referenced by SolveElasticCube().
IterativeProcess()
void beam3dtools::IterativeProcess ()
Manages other methods of the class and solves a elastoplastic beam. Perform the newtom method for a nonlinear material.
Definition at line 50 of file beam3dtools.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), CreateMatAndMesh(), mesh::fmaterial, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), InsertBC(), LoadBC(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), SolveEigen(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
LoadBC()
void beam3dtools::LoadBC (mesh & mesh0, NRmatrix< Doub > & K, NRmatrix< Doub > & F)
Insert boundary load BCs for the beam.
Definition at line 252 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess(), and SolveElasticBeam().
OutPutFile()
void beam3dtools::OutPutFile (MatDoub & postdata, std::ofstream & file) inline
Write a file.
Definition at line 150 of file beam3dtools.h.
References NRmatrix< T >::nrows().
Referenced by IterativeProcess().
OutPutPost()
void beam3dtools::OutPutPost (std::vector< std::vector< double >> & postdata, std::ofstream & file) inline
Write a file.
Definition at line 163 of file beam3dtools.h.
Referenced by IterativeProcess().
ReadMesh()
void beam3dtools::ReadMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology, string filenameel, string filenamecoord)
Read a mesh from files.
Parameters
[in] filenameel file containing all the elements topology.
[in] filenamecoord file containing all the nodes coordinates.
[out] allcoords object containg the element topology and nodes in the format:
{{ {x1,y1,z1},{x2,y2,z2}...,{xn,yn,zn} }(el 1 topology), { {x1,y1,z1},{x2,y2,z2}...,{xn,yn,zn} }(el 2 topology),...,{ {x1,y1,z1},{x2,y2,z2}...{xn,yn,zn} (el m topology)}} n=1 to n=nelnode
[out] meshcoords object containg the mesh coordinates in the format: { {x1,y1,z1},{x2,y2,z2}...,{xn,yn,zn} } with n=1 to n=nmeshnodes
[out] meshtopology object containg the mesh topology in the format: { {id1,id2,id3...,idn}(el 1),{id1,id2,id3...,idn}(el 2)...,{id1,id2,id3...,idn}(el m) } with n=1 to n=nelnode
Definition at line 407 of file beam3dtools.cpp.
References NRmatrix< T >::CopyFromVector(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by CreateMatAndMesh(), and CreateMatAndMeshCube().
SolveEigen()
void beam3dtools::SolveEigen (MatDoub A, MatDoub b, MatDoub & x)
Solve a linear system with Eigen.
Parameters
[in] A matrix A.
[in] b vector b
[out] x solution vector
Definition at line 351 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess(), SolveElasticBeam(), and SolveElasticCube().
SolveEigenSparse()
void beam3dtools::SolveEigenSparse (MatDoub A, MatDoub b, MatDoub & x)
Solve a sparse linear system with Eigen.
Parameters
[in] A matrix A.
[in] b vector b
[out] x solution vector
Definition at line 373 of file beam3dtools.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
SolveElasticBeam()
void beam3dtools::SolveElasticBeam ()
Manages other methods of the class and solves a elastic beam.
Definition at line 328 of file beam3dtools.cpp.
References mesh::Assemble(), CreateMatAndMesh(), InsertBC(), LoadBC(), NRmatrix< T >::Print(), and SolveEigen().
Referenced by main().
SolveElasticCube()
void beam3dtools::SolveElasticCube ()
Manages other methods of the class and solves a elastic cube.
Definition at line 305 of file beam3dtools.cpp.
References mesh::Assemble(), CreateMatAndMeshCube(), InsertCubeBC(), and SolveEigen().
vecstr_to_vec() [1/2]
template<class T > std::vector<T> beam3dtools::vecstr_to_vec (std::vector< std::string > vs)
Convert a string vector to a generic type T vector.
Parameters
[in] std::vector<std::string> string vector.
[out] std::vector<T> generic type T vector
vecstr_to_vec() [2/2]
template<class T > std::vector<T> beam3dtools::vecstr_to_vec (std::vector< string > vs)
Definition at line 485 of file beam3dtools.cpp.
Member Data Documentation
fmesh
mesh* beam3dtools::fmesh private
Definition at line 180 of file beam3dtools.h.
Referenced by beam3dtools().
The documentation for this class was generated from the following files:
src/beam3dtools.h
src/beam3dtools.cpp