DCPROJ: KLGalerkinRF Class Reference
KLGalerkinRF Class Reference
#include <KLGalerkinRF.h>
Public Member Functions
KLGalerkinRF (Int order, Doub Lx, Doub Ly, Int type, Int samples, Int expansionorder)
~KLGalerkinRF ()
void ContributeB (MatDoub &BE, Doub xi, Doub eta, Doub w, MatDoub elcoords)
void CacStiffB (MatDoub &BE, const MatDoub &elcoords)
void AssembleB (MatDoub &B)
void ContributeC (MatDoub &CE, MatDoub psis1, MatDoub GradPsi1, MatDoub elcoords1, Doub w1, MatDoub psis2, MatDoub GradPsi2, MatDoub elcoords2, Doub w2)
void CacStiffC (MatDoub &CE, const MatDoub &elcoords1, const MatDoub &elcoords2)
void AssembleC (MatDoub &C)
void SolveGenEigValProblem (VecComplex &val, MatDoub &vec, NRmatrix< MatDoub > &HHAT, std::vector< std::vector< double >> &errpost)
void GenerateGaussinRandomField (VecComplex &val, MatDoub &vec, NRmatrix< MatDoub > &HHAT, std::vector< std::vector< double >> &errpost)
void GenerateNonGaussinRandomField (VecComplex &val, MatDoub &vec, NRmatrix< MatDoub > &HHAT, std::vector< std::vector< double >> &errpost)
Doub AutocorrelationFunc (MatDoub x1, MatDoub x2)
Doub PerfomIntegralOfListconst (const MatDoub &Vec)
Doub PerfomIntegralOfListconst2 (const MatDoub &Vec)
void ComputeVarianceError (VecComplex &val, MatDoub &vec, MatDoub &error)
void OutPutPost (std::vector< std::vector< double >> &postdata, std::ofstream &file)
Doub GetLx ()
Doub GetLy ()
Doub GetSig ()
Doub Getftype ()
Doub GetExpansionorder ()
Doub GetSamples ()
void SetMesh (mesh *inmesh)
Public Member Functions inherited from elastmat2D
elastmat2D (mesh &inmesh, Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order)
elastmat2D (Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order, MatDoub HHAT)
elastmat2D ()
~elastmat2D ()
void Contribute (MatDoub &ek, MatDoub &ef, Doub xi, Doub eta, Doub w, MatDoub elcoords)
void CacStiff (MatDoub &ek, MatDoub &ef, const MatDoub &elcoords)
void Assemble (MatDoub &KG, MatDoub &FG, const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatDoub &meshnodes, const MatInt meshtopology)
void assembleBandN (MatDoub &B, MatDoub &N, const MatDoub &psis, const MatDoub &GradPhi)
void assembleConstitutiveMatrix (MatDoub &C, Doub mult)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > &allcoords, Int el, MatDoub &elcoords)
void DirichletBC (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)
void ContributeLineNewan (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)
void SolPt (const Int &el, const MatDoub &solG, const Doub &xi, const Doub &eta, MatDoub &xycoords, MatDoub &sol)
void PostProcess (const MatDoub &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)
void PostProcess (const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)
Private Attributes
Doub fyoung
Doub fnu
Doub fbodyforce
Int fplanestress
Doub fthickness
Int fOrder
Doub fLx
Doub fLy
Int ftype
Int fsamples
Int fexpansionorder
mesh fmesh
Additional Inherited Members
Public Attributes inherited from elastmat2D
MatDoub fHHAT
MatDoub fhhatvel
Detailed Description
Definition at line 17 of file KLGalerkinRF.h.
Constructor & Destructor Documentation
KLGalerkinRF()
KLGalerkinRF::KLGalerkinRF (Int order, Doub Lx, Doub Ly, Int type, Int samples, Int expansionorder)
Definition at line 7 of file KLGalerkinRF.cpp.
References fexpansionorder, fLx, fLy, fOrder, fsamples, and ftype.
~KLGalerkinRF()
KLGalerkinRF::~KLGalerkinRF ()
Definition at line 24 of file KLGalerkinRF.cpp.
Member Function Documentation
AssembleB()
void KLGalerkinRF::AssembleB (MatDoub & B)
Definition at line 85 of file KLGalerkinRF.cpp.
References NRmatrix< T >::assign(), CacStiffB(), fmesh, mesh::GetAllCoords(), elastmat2D::GetElCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), and NRmatrix< T >::nrows().
Referenced by SolveGenEigValProblem().
AssembleC()
void KLGalerkinRF::AssembleC (MatDoub & C)
Definition at line 166 of file KLGalerkinRF.cpp.
References NRmatrix< T >::assign(), CacStiffC(), fmesh, mesh::GetAllCoords(), elastmat2D::GetElCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), and NRmatrix< T >::nrows().
Referenced by SolveGenEigValProblem().
AutocorrelationFunc()
Doub KLGalerkinRF::AutocorrelationFunc (MatDoub x1, MatDoub x2)
Definition at line 230 of file KLGalerkinRF.cpp.
References fLx, fLy, and ftype.
Referenced by ContributeC().
CacStiffB()
void KLGalerkinRF::CacStiffB (MatDoub & BE, const MatDoub & elcoords)
Definition at line 61 of file KLGalerkinRF.cpp.
References NRmatrix< T >::assign(), ContributeB(), fOrder, NRmatrix< T >::nrows(), and shapequad::pointsandweigths().
Referenced by AssembleB().
CacStiffC()
void KLGalerkinRF::CacStiffC (MatDoub & CE, const MatDoub & elcoords1, const MatDoub & elcoords2)
Definition at line 137 of file KLGalerkinRF.cpp.
References NRmatrix< T >::assign(), ContributeC(), fOrder, NRmatrix< T >::nrows(), shapequad::pointsandweigths(), and shapequad::shapes().
Referenced by AssembleC().
ComputeVarianceError()
void KLGalerkinRF::ComputeVarianceError (VecComplex & val, MatDoub & vec, MatDoub & error)
Definition at line 725 of file KLGalerkinRF.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by SolveGenEigValProblem().
ContributeB()
void KLGalerkinRF::ContributeB (MatDoub & BE, Doub xi, Doub eta, Doub w, MatDoub elcoords)
Definition at line 38 of file KLGalerkinRF.cpp.
References fOrder, NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Referenced by CacStiffB().
ContributeC()
void KLGalerkinRF::ContributeC (MatDoub & CE, MatDoub psis1, MatDoub GradPsi1, MatDoub elcoords1, Doub w1, MatDoub psis2, MatDoub GradPsi2, MatDoub elcoords2, Doub w2)
Definition at line 116 of file KLGalerkinRF.cpp.
References AutocorrelationFunc(), NRmatrix< T >::Mult(), and NRmatrix< T >::Transpose().
Referenced by CacStiffC().
GenerateGaussinRandomField()
void KLGalerkinRF::GenerateGaussinRandomField (VecComplex & val, MatDoub & vec, NRmatrix< MatDoub > & HHAT, std::vector< std::vector< double >> & errpost)
Definition at line 448 of file KLGalerkinRF.cpp.
References fexpansionorder, fsamples, NRmatrix< T >::Mult(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRmatrix< T >::resize(), and NRmatrix< T >::Transpose().
GenerateNonGaussinRandomField()
void KLGalerkinRF::GenerateNonGaussinRandomField (VecComplex & val, MatDoub & vec, NRmatrix< MatDoub > & HHAT, std::vector< std::vector< double >> & errpost)
Definition at line 371 of file KLGalerkinRF.cpp.
References fexpansionorder, fsamples, NRmatrix< T >::Mult(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRmatrix< T >::resize(), and NRmatrix< T >::Transpose().
Referenced by SolveGenEigValProblem().
GetExpansionorder()
Doub KLGalerkinRF::GetExpansionorder () inline
Definition at line 75 of file KLGalerkinRF.h.
References fexpansionorder.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
Getftype()
Doub KLGalerkinRF::Getftype () inline
Definition at line 71 of file KLGalerkinRF.h.
References ftype.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
GetLx()
Doub KLGalerkinRF::GetLx () inline
Definition at line 59 of file KLGalerkinRF.h.
References fLx.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
GetLy()
Doub KLGalerkinRF::GetLy () inline
Definition at line 63 of file KLGalerkinRF.h.
References fLy.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
GetSamples()
Doub KLGalerkinRF::GetSamples () inline
Definition at line 79 of file KLGalerkinRF.h.
References fsamples.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
GetSig()
Doub KLGalerkinRF::GetSig () inline
Definition at line 67 of file KLGalerkinRF.h.
Referenced by slopeproject::CreateRandomField(), and slopeproject::MonteCarloGIM().
OutPutPost()
void KLGalerkinRF::OutPutPost (std::vector< std::vector< double >> & postdata, std::ofstream & file) inline
Definition at line 45 of file KLGalerkinRF.h.
PerfomIntegralOfListconst()
Doub KLGalerkinRF::PerfomIntegralOfListconst (const MatDoub & Vec)
Definition at line 753 of file KLGalerkinRF.cpp.
References fmesh, fOrder, mesh::GetAllCoords(), elastmat2D::GetElCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths(), and shapequad::shapes().
Referenced by SolveGenEigValProblem().
PerfomIntegralOfListconst2()
Doub KLGalerkinRF::PerfomIntegralOfListconst2 (const MatDoub & Vec)
Definition at line 693 of file KLGalerkinRF.cpp.
References fmesh, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), and elastmat2D::SolPt().
SetMesh()
void KLGalerkinRF::SetMesh (mesh * inmesh) inline
Definition at line 84 of file KLGalerkinRF.h.
References fmesh.
Referenced by createrandomfield(), mainlinux(), mainlinux2(), mainlinuxserial(), and mainwindows().
SolveGenEigValProblem()
void KLGalerkinRF::SolveGenEigValProblem (VecComplex & val, MatDoub & vec, NRmatrix< MatDoub > & HHAT, std::vector< std::vector< double >> & errpost)
Definition at line 258 of file KLGalerkinRF.cpp.
References AssembleB(), AssembleC(), NRvector< T >::assign(), NRmatrix< T >::assign(), ComputeVarianceError(), fexpansionorder, fmesh, GenerateNonGaussinRandomField(), mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), Cholesky::inverse(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), PerfomIntegralOfListconst(), NRvector< T >::Print(), NRvector< T >::size(), Unsymmeig::wri, and Unsymmeig::zz.
Referenced by slopeproject::CreateRandomField(), CreateRandomField(), MonteCarlo(), and MonteCarloTalude2().
Member Data Documentation
fbodyforce
Doub KLGalerkinRF::fbodyforce private
Definition at line 92 of file KLGalerkinRF.h.
fexpansionorder
Int KLGalerkinRF::fexpansionorder private
Definition at line 101 of file KLGalerkinRF.h.
Referenced by GenerateGaussinRandomField(), GenerateNonGaussinRandomField(), GetExpansionorder(), KLGalerkinRF(), and SolveGenEigValProblem().
fLx
Doub KLGalerkinRF::fLx private
Definition at line 96 of file KLGalerkinRF.h.
Referenced by AutocorrelationFunc(), GetLx(), and KLGalerkinRF().
fLy
Doub KLGalerkinRF::fLy private
Definition at line 97 of file KLGalerkinRF.h.
Referenced by AutocorrelationFunc(), GetLy(), and KLGalerkinRF().
fmesh
mesh KLGalerkinRF::fmesh private
Definition at line 102 of file KLGalerkinRF.h.
Referenced by AssembleB(), AssembleC(), PerfomIntegralOfListconst(), PerfomIntegralOfListconst2(), SetMesh(), and SolveGenEigValProblem().
fnu
Doub KLGalerkinRF::fnu private
Definition at line 91 of file KLGalerkinRF.h.
fOrder
Int KLGalerkinRF::fOrder private
Definition at line 95 of file KLGalerkinRF.h.
Referenced by CacStiffB(), CacStiffC(), ContributeB(), KLGalerkinRF(), and PerfomIntegralOfListconst().
fplanestress
Int KLGalerkinRF::fplanestress private
Definition at line 93 of file KLGalerkinRF.h.
fsamples
Int KLGalerkinRF::fsamples private
Definition at line 100 of file KLGalerkinRF.h.
Referenced by GenerateGaussinRandomField(), GenerateNonGaussinRandomField(), GetSamples(), and KLGalerkinRF().
fthickness
Doub KLGalerkinRF::fthickness private
Definition at line 94 of file KLGalerkinRF.h.
ftype
Int KLGalerkinRF::ftype private
Definition at line 99 of file KLGalerkinRF.h.
Referenced by AutocorrelationFunc(), Getftype(), and KLGalerkinRF().
fyoung
Doub KLGalerkinRF::fyoung private
Definition at line 90 of file KLGalerkinRF.h.
The documentation for this class was generated from the following files:
src/KLGalerkinRF.h
src/KLGalerkinRF.cpp