DCPROJ: postprocess Class Reference
postprocess Class Reference
#include <postprocess.h>
Public Member Functions
postprocess ()
~postprocess ()
void PostProcess (mesh &inmesh, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)
Detailed Description
Definition at line 5 of file postprocess.h.
Constructor & Destructor Documentation
postprocess()
postprocess::postprocess ()
Definition at line 5 of file postprocess.cpp.
~postprocess()
postprocess::~postprocess ()
Definition at line 10 of file postprocess.cpp.
Member Function Documentation
PostProcess()
void postprocess::PostProcess (mesh & inmesh, const MatDoub & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 15 of file postprocess.cpp.
References mesh::GetAllCoords(), mesh::GetElCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
The documentation for this class was generated from the following files:
src/postprocess.h
src/postprocess.cpp