DCPROJ: NRmatrix< T > Class Template Reference
NRmatrix< T > Class Template Reference
#include <nr3.h>
Public Types
typedef T value_type
Public Member Functions
NRmatrix ()
NRmatrix (int n, int m)
NRmatrix (int n, int m, const T &a)
NRmatrix (int n, int m, const T *a)
NRmatrix (const NRmatrix &rhs)
NRmatrix & operator= (const NRmatrix &rhs)
T * operator[] (const int i)
const T * operator[] (const int i) const
NRmatrix & operator*= (const T &multipl)
NRmatrix & operator+= (NRmatrix &source)
NRmatrix & operator-= (NRmatrix &source)
int nrows () const
int ncols () const
void resize (int newn, int newm)
void assign (int newn, int newm, const T &a)
void Print ()
void Print2 ()
void Transpose (NRmatrix &transpose)
void Mult (const NRmatrix &A, NRmatrix &B)
void Dot (const NRmatrix &A, NRmatrix &B)
void CopyFromVector (const std::vector< std::vector< T >> &input)
void FromFullToVoigt (NRmatrix< T > &full)
NRmatrix & FromEigen (VectorXd data)
void FromEigen (MatrixXd data)
void ToEigen (MatrixXd &data)
T DetEig ()
void ComputeInverse (NRmatrix< T > &InvOut)
T NRmatrixNorm ()
T Det ()
void CopyFromVecdouble (const NRvector< T > &input)
~NRmatrix ()
Private Attributes
int nn
int mm
T ** v
Detailed Description
template<class T>
class NRmatrix< T >
Definition at line 293 of file nr3.h.
Member Typedef Documentation
value_type
template<class T > typedef T NRmatrix< T >::value_type
Definition at line 306 of file nr3.h.
Constructor & Destructor Documentation
NRmatrix() [1/5]
template<class T > NRmatrix< T >::NRmatrix
Definition at line 635 of file nr3.h.
NRmatrix() [2/5]
template<class T > NRmatrix< T >::NRmatrix (int n, int m)
Definition at line 638 of file nr3.h.
NRmatrix() [3/5]
template<class T > NRmatrix< T >::NRmatrix (int n, int m, const T & a)
Definition at line 646 of file nr3.h.
NRmatrix() [4/5]
template<class T > NRmatrix< T >::NRmatrix (int n, int m, const T * a)
Definition at line 655 of file nr3.h.
NRmatrix() [5/5]
template<class T > NRmatrix< T >::NRmatrix (const NRmatrix< T > & rhs)
Definition at line 664 of file nr3.h.
~NRmatrix()
template<class T > NRmatrix< T >::~NRmatrix
Definition at line 811 of file nr3.h.
Member Function Documentation
assign()
template<class T > void NRmatrix< T >::assign (int newn, int newm, const T & a)
Definition at line 783 of file nr3.h.
Referenced by elastoplastic2D< YC >::Assemble(), mesh::Assemble(), KLGalerkinRF::AssembleB(), elastmat2D::assembleBandN(), elastoplastic3D< YC >::assembleBandN(), elastoplastic2D< YC >::assembleBandN(), KLGalerkinRF::AssembleC(), elastmat2D::assembleConstitutiveMatrix(), elastoplastic2D< YC >::assembleConstitutiveMatrix(), elastmat2D::CacStiff(), elastoplastic3D< YC >::CacStiff(), elastoplastic2D< YC >::CacStiff(), KLGalerkinRF::CacStiffB(), KLGalerkinRF::CacStiffC(), NRmatrix< Doub >::ComputeInverse(), mohrcoulomb::ComputePlaneTangent(), mesh::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolAndDSol(), KLGalerkinRF::ComputeVarianceError(), elastoplastic2D< YC >::Contribute(), elastoplastic2D< YC >::ContributeCurvedLine(), elastoplastic2D< YC >::ContributeEig(), pressurizedhole::CreateMatAndMesh(), beam3dtools::CreateMatAndMesh(), beam3dtools::CreateMatAndMeshCube(), NRmatrix< Doub >::Dot(), FindEl(), mesh::FindSolution(), NRmatrix< Doub >::FromEigen(), NRmatrix< Doub >::FromFullToVoigt(), NRtensor< Doub >::FromTensorToNRmatrix(), NRtensor< Doub >::FromTensorVoigtToFullTensor(), gridmesh::GetElCoords(), elastmat2D::GetElCoords(), pressurizedhole::GetElCoords(), elastoplastic3D< YC >::GetElCoords(), mesh::GetElCoords(), elastoplastic2D< YC >::GetElCoords(), slopeproject::GetElCoords(), beam3dtools::GetElCoords(), beam3dtools::InsertCubeBC(), IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), gridmesh::Line(), slopeproject::Line(), pressurizedhole::LoadBC(), beam3dtools::LoadBC(), NRmatrix< Doub >::Mult(), NRmatrix3D< T >::NRmatrix3D(), shapehexahedron::shapes(), shapequad::shapes(), elastmat2D::SolPt(), elastoplastic2D< YC >::SolPt(), pressurizedhole::SolveEigen(), slopeproject::SolveEigen(), beam3dtools::SolveEigen(), SolveEigen(), slopeproject::SolveEigen2(), SolveEigen2(), slopeproject::SolveEigen3(), pressurizedhole::SolveEigenSparse(), slopeproject::SolveEigenSparse(), beam3dtools::SolveEigenSparse(), KLGalerkinRF::SolveGenEigValProblem(), SolveNR3(), pressurizedhole::ToMatInt(), and ToMatInt().
ComputeInverse()
template<class T > void NRmatrix< T >::ComputeInverse (NRmatrix< T > & InvOut) inline
Definition at line 363 of file nr3.h.
Referenced by druckerprager::closestpointproj().
CopyFromVecdouble()
template<class T > void NRmatrix< T >::CopyFromVecdouble (const NRvector< T > & input)
Definition at line 398 of file nr3.h.
CopyFromVector()
template<class T > void NRmatrix< T >::CopyFromVector (const std::vector< std::vector< T >> & input)
Definition at line 602 of file nr3.h.
Referenced by IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), main2(), MonteCarlo(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), slopeproject::ReadMatDoub(), ReadMatDoub(), pressurizedhole::ReadMesh(), slopeproject::ReadMesh(), beam3dtools::ReadMesh(), and ReadMesh().
Det()
template<class T > T NRmatrix< T >::Det
Definition at line 434 of file nr3.h.
DetEig()
template<class T > T NRmatrix< T >::DetEig () inline
Definition at line 349 of file nr3.h.
Referenced by druckerprager::closestpointproj().
Dot()
template<class T > void NRmatrix< T >::Dot (const NRmatrix< T > & A, NRmatrix< T > & B)
Definition at line 578 of file nr3.h.
FromEigen() [1/2]
template<class T > void NRmatrix< T >::FromEigen (MatrixXd data) inline
Definition at line 326 of file nr3.h.
FromEigen() [2/2]
template<class T > NRmatrix& NRmatrix< T >::FromEigen (VectorXd data)
Referenced by elastoplastic2D< YC >::ContributeEig().
FromFullToVoigt()
template<class T > void NRmatrix< T >::FromFullToVoigt (NRmatrix< T > & full)
Definition at line 408 of file nr3.h.
Referenced by vonmises::closestpointproj(), and druckerprager::ComputeQ().
Mult()
template<class T > void NRmatrix< T >::Mult (const NRmatrix< T > & A, NRmatrix< T > & B)
Definition at line 555 of file nr3.h.
Referenced by vonmises::closestpointproj(), druckerprager::closestpointproj(), druckerprager::ComputeQ(), elastoplastic2D< YC >::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolution(), elastmat2D::Contribute(), elastoplastic3D< YC >::Contribute(), elastoplastic2D< YC >::Contribute(), KLGalerkinRF::ContributeB(), KLGalerkinRF::ContributeC(), elastoplastic2D< YC >::ContributeCurvedLine(), elastoplastic2D< YC >::ContributeEig(), elastmat2D::ContributeLineNewan(), elastoplastic2D< YC >::ContributeLineNewan(), vonmises::dadsig(), FindEl(), mesh::FindSolution(), KLGalerkinRF::GenerateGaussinRandomField(), KLGalerkinRF::GenerateNonGaussinRandomField(), IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), FuncdSearch::operator()(), KLGalerkinRF::PerfomIntegralOfListconst(), vonmises::phi(), druckerprager::phi(), postprocess::PostProcess(), elastmat2D::PostProcess(), elastoplastic2D< YC >::PostProcess(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), elastmat2D::SolPt(), elastoplastic2D< YC >::SolPt(), and KLGalerkinRF::SolveGenEigValProblem().
ncols()
template<class T > int NRmatrix< T >::ncols inline
Definition at line 759 of file nr3.h.
Referenced by mesh::Assemble(), Cholesky::Cholesky(), NRmatrix< Doub >::ComputeInverse(), KLGalerkinRF::ComputeVarianceError(), gridmesh::CreateMesh(), druckerprager::Det(), NRmatrix< Doub >::DetEig(), NRmatrix< Doub >::Dot(), VTKGraphMesh::DrawSolution(), FindEl(), NRmatrix< Doub >::FromEigen(), KLGalerkinRF::GenerateGaussinRandomField(), KLGalerkinRF::GenerateNonGaussinRandomField(), VTKGraphMesh::GetMeshTopologyVTK(), druckerprager::Inverse(), slopeproject::MonteCarloGIM(), NRmatrix< Doub >::Mult(), NRmatrix3D< T >::NRmatrix3D(), slopeproject::OutPutPost(), pressurizedhole::OutPutPost(), OutPutPost(), gridmesh::PrintAllCoords(), slopeproject::PrintMathematicaFormat(), pressurizedhole::ReadMesh(), slopeproject::ReadMesh(), beam3dtools::ReadMesh(), ReadMesh(), LUdcmp::solve(), pressurizedhole::SolveEigen(), slopeproject::SolveEigen(), beam3dtools::SolveEigen(), SolveEigen(), slopeproject::SolveEigen2(), SolveEigen2(), slopeproject::SolveEigen3(), and NRmatrix< Doub >::ToEigen().
NRmatrixNorm()
template<class T > T NRmatrix< T >::NRmatrixNorm
Definition at line 420 of file nr3.h.
Referenced by druckerprager::ComputeQ(), IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
nrows()
template<class T > int NRmatrix< T >::nrows inline
Definition at line 753 of file nr3.h.
Referenced by elastmat2D::Assemble(), elastoplastic2D< YC >::Assemble(), mesh::Assemble(), KLGalerkinRF::AssembleB(), elastmat2D::assembleBandN(), elastoplastic3D< YC >::assembleBandN(), elastoplastic2D< YC >::assembleBandN(), KLGalerkinRF::AssembleC(), slopeproject::AssembleHhationho(), elastmat2D::CacStiff(), elastoplastic3D< YC >::CacStiff(), elastoplastic2D< YC >::CacStiff(), KLGalerkinRF::CacStiffB(), KLGalerkinRF::CacStiffC(), vonmises::closestpointproj(), druckerprager::closestpointproj(), NRmatrix< Doub >::ComputeInverse(), slopeproject::computelamda(), beam3dtools::computelamda(), computelamda(), mesh::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolAndDSol(), KLGalerkinRF::ComputeVarianceError(), elastmat2D::Contribute(), elastoplastic2D< YC >::Contribute(), KLGalerkinRF::ContributeB(), elastoplastic2D< YC >::ContributeCurvedLine(), elastoplastic2D< YC >::ContributeEig(), elastmat2D::ContributeLineNewan(), elastoplastic2D< YC >::ContributeLineNewan(), pressurizedhole::CreateMatAndMesh(), beam3dtools::CreateMatAndMesh(), beam3dtools::CreateMatAndMeshCube(), gridmesh::CreateMesh(), createrandomfield(), druckerprager::Det(), NRmatrix< Doub >::Det(), NRmatrix< Doub >::DetEig(), elastmat2D::DirichletBC(), elastoplastic3D< YC >::DirichletBC(), elastoplastic2D< YC >::DirichletBC(), NRmatrix< Doub >::Dot(), VTKGraphMesh::DrawSolution(), FindEl(), pressurizedhole::FindIds(), mesh::FindIds(), beam3dtools::FindIds(), gridmesh::FindIdsInPath(), slopeproject::FindIdsInPath(), mesh::FindSolution(), NRmatrix< Doub >::FromEigen(), KLGalerkinRF::GenerateGaussinRandomField(), KLGalerkinRF::GenerateNonGaussinRandomField(), VTKGraphMesh::GetMeshTopologyVTK(), beam3dtools::InsertCubeBC(), druckerprager::Inverse(), IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), beam3dtools::LoadBC(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), mainwindows(), MonteCarlo(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), NRmatrix< Doub >::Mult(), NRmatrix3D< T >::NRmatrix3D(), slopeproject::OutPutFile(), pressurizedhole::OutPutFile(), beam3dtools::OutPutFile(), OutPutFile(), slopeproject::OutPutFile1var(), OutPutFile1var(), OutPutFile4var(), slopeproject::OutPutPost(), pressurizedhole::OutPutPost(), OutPutPost(), KLGalerkinRF::PerfomIntegralOfListconst(), shapequad::pointsandweigths1D(), shapehexahedron::pointsandweigths1D(), postprocess::PostProcess(), elastmat2D::PostProcess(), elastoplastic2D< YC >::PostProcess(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), elastoplastic2D< YC >::PostProcessStrain(), gridmesh::PrintAllCoords(), gridmesh::PrintGMeshVTK(), slopeproject::PrintMathematicaFormat(), pressurizedhole::ReadMesh(), slopeproject::ReadMesh(), beam3dtools::ReadMesh(), ReadMesh(), elastmat2D::SolPt(), elastoplastic2D< YC >::SolPt(), LUdcmp::solve(), solvedeterm(), solvedetermtest(), pressurizedhole::SolveEigen(), slopeproject::SolveEigen(), beam3dtools::SolveEigen(), SolveEigen(), slopeproject::SolveEigen2(), SolveEigen2(), slopeproject::SolveEigen3(), pressurizedhole::SolveEigenSparse(), slopeproject::SolveEigenSparse(), beam3dtools::SolveEigenSparse(), KLGalerkinRF::SolveGenEigValProblem(), SolveNR3(), NRmatrix< Doub >::ToEigen(), and mesh::TransferSolution().
operator*=()
template<class T > NRmatrix< T > & NRmatrix< T >::operator*= (const T & multipl)
Definition at line 715 of file nr3.h.
operator+=()
template<class T > NRmatrix< T > & NRmatrix< T >::operator+= (NRmatrix< T > & source)
Definition at line 493 of file nr3.h.
operator-=()
template<class T > NRmatrix< T > & NRmatrix< T >::operator-= (NRmatrix< T > & source)
Definition at line 480 of file nr3.h.
operator=()
template<class T > NRmatrix< T > & NRmatrix< T >::operator= (const NRmatrix< T > & rhs)
Definition at line 675 of file nr3.h.
operator[]() [1/2]
template<class T > T * NRmatrix< T >::operator[] (const int i) inline
Definition at line 729 of file nr3.h.
operator[]() [2/2]
template<class T > const T * NRmatrix< T >::operator[] (const int i) const inline
Definition at line 741 of file nr3.h.
Print()
template<class T > void NRmatrix< T >::Print
Definition at line 509 of file nr3.h.
Referenced by elastmat2D::Contribute(), elastoplastic3D< YC >::Contribute(), elastoplastic2D< YC >::Contribute(), elastoplastic2D< YC >::ContributeEig(), FindEl(), mesh::FindSolution(), IterativeCho(), IterativeSlopeStabilityEig(), elastoplastic2D< YC >::PostProcessStrain(), slopeproject::ReadMesh(), ReadMesh(), beam3dtools::SolveElasticBeam(), and pressurizedhole::SolveElasticHole().
Print2()
template<class T > void NRmatrix< T >::Print2
Definition at line 524 of file nr3.h.
resize()
template<class T > void NRmatrix< T >::resize (int newn, int newm)
Definition at line 765 of file nr3.h.
Referenced by elastoplastic2D< YC >::Assemble(), mesh::Assemble(), mesh::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolution(), gridmesh::CreateMesh(), NRtensor< Doub >::EigenSystem(), KLGalerkinRF::GenerateGaussinRandomField(), KLGalerkinRF::GenerateNonGaussinRandomField(), Cholesky::inverse(), LUdcmp::inverse(), shapequad::pointsandweigths(), shapehexahedron::pointsandweigths(), shapequad::pointsandweigths1D(), shapehexahedron::pointsandweigths1D(), elastoplastic2D< YC >::PostProcessStrain(), shapequad::shapes(), shapequad::shapes1D(), shapehexahedron::shapes1D(), and NRmatrix< Doub >::Transpose().
ToEigen()
template<class T > void NRmatrix< T >::ToEigen (MatrixXd & data) inline
Definition at line 337 of file nr3.h.
Referenced by elastoplastic2D< YC >::ContributeEig().
Transpose()
template<class T > void NRmatrix< T >::Transpose (NRmatrix< T > & transpose)
Definition at line 542 of file nr3.h.
Referenced by vonmises::closestpointproj(), druckerprager::closestpointproj(), elastoplastic2D< YC >::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolution(), elastmat2D::Contribute(), elastoplastic3D< YC >::Contribute(), elastoplastic2D< YC >::Contribute(), KLGalerkinRF::ContributeB(), KLGalerkinRF::ContributeC(), elastoplastic2D< YC >::ContributeCurvedLine(), elastoplastic2D< YC >::ContributeEig(), vonmises::dadsig(), FindEl(), mesh::FindSolution(), KLGalerkinRF::GenerateGaussinRandomField(), KLGalerkinRF::GenerateNonGaussinRandomField(), IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), FuncdSearch::operator()(), postprocess::PostProcess(), elastmat2D::PostProcess(), elastoplastic2D< YC >::PostProcess(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), elastmat2D::SolPt(), elastoplastic2D< YC >::SolPt(), vonmises::stressrecosntruction(), and druckerprager::stressrecosntruction().
Member Data Documentation
mm
template<class T > int NRmatrix< T >::mm private
Definition at line 296 of file nr3.h.
Referenced by NRmatrix< Doub >::NRmatrix(), and NRmatrix< Doub >::operator=().
nn
template<class T > int NRmatrix< T >::nn private
Definition at line 295 of file nr3.h.
Referenced by NRmatrix< Doub >::NRmatrix(), and NRmatrix< Doub >::operator=().
v
template<class T > T** NRmatrix< T >::v private
Definition at line 297 of file nr3.h.
Referenced by NRmatrix< Doub >::ComputeInverse(), NRmatrix< Doub >::DetEig(), NRmatrix< Doub >::FromEigen(), NRmatrix< Doub >::NRmatrix(), and NRmatrix< Doub >::ToEigen().
The documentation for this class was generated from the following file:
src/nr3.h