DCPROJ: elastoplastic3D< YC > Class Template Reference
elastoplastic3D< YC > Class Template Reference
#include <elastoplastic3D.h>
Public Member Functions
elastoplastic3D (NRmatrix< Doub > bodyforce, Int order)
elastoplastic3D (NRmatrix< Doub > bodyforce, Int order, NRmatrix< Doub > HHAT)
elastoplastic3D (elastoplastic3D &copy)
elastoplastic3D ()
~elastoplastic3D ()
void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, NRmatrix< Doub > &KG, NRmatrix< Doub > &Fint, NRmatrix< Doub > &Fbody)
void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, SparseMatrix< double > &KG, VectorXd &Fint, VectorXd &Fbody)
void DirichletBC (SparseMatrix< double > &KG, VectorXd &Fint, std::vector< int > ids, Int dir, Int val)
void Contribute (NRmatrix< Doub > &ek, NRmatrix< Doub > &efint, NRmatrix< Doub > &efbody, NRvector< Doub > intptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
void CacStiff (NRmatrix< Doub > &ek, NRmatrix< Doub > &efint, NRmatrix< Doub > &efbody, const NRmatrix< Doub > &elcoords, NRmatrix< Doub > eldisplace)
void assembleBandN (NRmatrix< Doub > &B, NRmatrix< Doub > &N, const NRmatrix< Doub > &psis, const NRmatrix< Doub > &GradPhi)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)
void DirichletBC (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, std::vector< int > ids, Int dir, Int val)
void ContributeLineNewan (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, std::vector< int > ids, Int dir, Int val)
void ContributeCurvedLine (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, NRmatrix< Doub > meshnodes, MatInt linetopology, Doub force)
void SolPt (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt &meshtopology, const Int &el, const NRmatrix< Doub > &solG, const Doub &xi, const Doub &eta, NRmatrix< Doub > &xycoords, MatDoub &sol)
void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)
void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, Int var, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &sol)
void PostProcessStrain (mesh *inmesh, NRvector< NRvector< NRtensor< Doub >>> &sol)
void PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &sol)
void SetRandomField (NRmatrix< Doub > hhat)
void SetRandomFieldLocal (NRvector< NRmatrix< Doub > > hhatvel)
void SetMemory (Int ngloblapoints, Int systemsize)
void UpdateDisplacement (NRmatrix< Doub > displace)
void UpdateDisplacement (VectorXd displace)
void UpdatePlasticStrain ()
void UpdateBodyForce (NRmatrix< Doub > newbodyforce)
void ResetPlasticStrain ()
void ResetDisplacement ()
void ResetMat ()
void ResetMemory ()
NRmatrix< Doub > GetSolution ()
void ComputeSolAndDSol (mesh *inmesh, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)
void ComputeSolAndDSol (mesh *inmesh, NRvector< NRmatrix< Doub >> &sol, NRvector< NRmatrix< Doub >> &dsol)
void ComputeSolution (mesh *inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)
void ResetCounter ()
void SetMatConstants (NRvector< Doub > &consts)
void GetMatConstants (NRvector< Doub > &consts)
virtual void GetMaterialData ()
NRmatrix< Doub > GetBodyForce ()
virtual NRvector< NRtensor< Doub > > GetPlasticStrain ()
Doub ComputePhi (NRtensor< Doub > eps)
Public Member Functions inherited from material
material ()
~material ()
virtual void Contribute (MatDoub &ek, MatDoub &efint, MatDoub &efbody, NRvector< Doub > ptsw, MatDoub elcoords, MatDoub eldisplace)=0
virtual void CacStiff (MatDoub &ek, MatDoub &efint, MatDoub &efbody, const MatDoub &elcoords, MatDoub eldisplace)=0
virtual void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub &KG, MatDoub &Fint, MatDoub &Fbody)=0
virtual void assembleBandN (MatDoub &B, MatDoub &N, const MatDoub &psis, const MatDoub &GradPhi)=0
virtual void DirichletBC (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeLineNewan (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeCurvedLine (MatDoub &KG, MatDoub &FG, MatDoub meshnodes, MatInt linetopology, Doub force)=0
virtual void SolPt (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt &meshtopology, const Int &el, const MatDoub &solG, const Doub &xi, const Doub &eta, MatDoub &xycoords, MatDoub &sol)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, Int var, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void SetRandomField (MatDoub hhat)=0
virtual void UpdateDisplacement (MatDoub displace)=0
virtual void UpdateBodyForce (MatDoub newbodyforce)=0
virtual void SetRandomFieldLocal (NRvector< MatDoub > hhatvel)=0
Public Attributes
NRmatrix< Doub > fHHAT
NRvector< NRmatrix< Doub > > fhhatvel
YC fYC
NRmatrix< Doub > fdisplace
NRvector< NRtensor< Doub > > fepspvec
NRvector< NRtensor< Doub > > fepspsolitern
Int fglobalcounter
Private Attributes
NRmatrix< Doub > fbodyforce
Int fOrder
Detailed Description
template<class YC>
class elastoplastic3D< YC >
Definition at line 11 of file elastoplastic3D.h.
Constructor & Destructor Documentation
elastoplastic3D() [1/4]
template<class YC > elastoplastic3D< YC >::elastoplastic3D (NRmatrix< Doub > bodyforce, Int order)
Definition at line 6 of file elastoplastic3D.cpp.
elastoplastic3D() [2/4]
template<class YC > elastoplastic3D< YC >::elastoplastic3D (NRmatrix< Doub > bodyforce, Int order, NRmatrix< Doub > HHAT)
Definition at line 16 of file elastoplastic3D.cpp.
elastoplastic3D() [3/4]
template<class YC > elastoplastic3D< YC >::elastoplastic3D (elastoplastic3D< YC > & copy)
Definition at line 25 of file elastoplastic3D.cpp.
elastoplastic3D() [4/4]
template<class YC > elastoplastic3D< YC >::elastoplastic3D
Definition at line 30 of file elastoplastic3D.cpp.
~elastoplastic3D()
template<class YC > elastoplastic3D< YC >::~elastoplastic3D
Definition at line 37 of file elastoplastic3D.cpp.
Member Function Documentation
Assemble() [1/2]
template<class YC > void elastoplastic3D< YC >::Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, NRmatrix< Doub > & KG, NRmatrix< Doub > & Fint, NRmatrix< Doub > & Fbody)
Definition at line 505 of file elastoplastic3D.cpp.
References DebugStop.
Assemble() [2/2]
template<class YC > void elastoplastic3D< YC >::Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, SparseMatrix< double > & KG, VectorXd & Fint, VectorXd & Fbody)
Definition at line 512 of file elastoplastic3D.cpp.
References DebugStop.
assembleBandN()
template<class YC > void elastoplastic3D< YC >::assembleBandN (NRmatrix< Doub > & B, NRmatrix< Doub > & N, const NRmatrix< Doub > & psis, const NRmatrix< Doub > & GradPhi)
Definition at line 324 of file elastoplastic3D.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
CacStiff()
template<class YC > void elastoplastic3D< YC >::CacStiff (NRmatrix< Doub > & ek, NRmatrix< Doub > & efint, NRmatrix< Doub > & efbody, const NRmatrix< Doub > & elcoords, NRmatrix< Doub > eldisplace)
Definition at line 295 of file elastoplastic3D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and shapehexahedron::pointsandweigths().
ComputePhi()
template<class YC > Doub elastoplastic3D< YC >::ComputePhi (NRtensor< Doub > eps) inline virtual
Implements material.
Definition at line 85 of file elastoplastic3D.h.
ComputeSolAndDSol() [1/2]
template<class YC > void elastoplastic3D< YC >::ComputeSolAndDSol (mesh * inmesh, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) virtual
Implements material.
Definition at line 525 of file elastoplastic3D.cpp.
References DebugStop.
ComputeSolAndDSol() [2/2]
template<class YC > void elastoplastic3D< YC >::ComputeSolAndDSol (mesh * inmesh, NRvector< NRmatrix< Doub >> & sol, NRvector< NRmatrix< Doub >> & dsol) virtual
Implements material.
Definition at line 532 of file elastoplastic3D.cpp.
References DebugStop.
ComputeSolution()
template<class YC > void elastoplastic3D< YC >::ComputeSolution (mesh * inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) virtual
Implements material.
Definition at line 463 of file elastoplastic3D.cpp.
References DebugStop.
Contribute()
template<class YC > void elastoplastic3D< YC >::Contribute (NRmatrix< Doub > & ek, NRmatrix< Doub > & efint, NRmatrix< Doub > & efbody, NRvector< Doub > intptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
Definition at line 157 of file elastoplastic3D.cpp.
References DebugStop, NRmatrix< T >::Mult(), NRmatrix< T >::Print(), shapehexahedron::shapes(), and NRmatrix< T >::Transpose().
ContributeCurvedLine()
template<class YC > void elastoplastic3D< YC >::ContributeCurvedLine (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, NRmatrix< Doub > meshnodes, MatInt linetopology, Doub force)
Definition at line 457 of file elastoplastic3D.cpp.
References DebugStop.
ContributeLineNewan()
template<class YC > void elastoplastic3D< YC >::ContributeLineNewan (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 450 of file elastoplastic3D.cpp.
References DebugStop.
DirichletBC() [1/2]
template<class YC > void elastoplastic3D< YC >::DirichletBC (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 401 of file elastoplastic3D.cpp.
References NRmatrix< T >::nrows().
DirichletBC() [2/2]
template<class YC > void elastoplastic3D< YC >::DirichletBC (SparseMatrix< double > & KG, VectorXd & Fint, std::vector< int > ids, Int dir, Int val) virtual
Implements material.
Definition at line 443 of file elastoplastic3D.cpp.
References DebugStop.
GetBodyForce()
template<class YC > NRmatrix<Doub> elastoplastic3D< YC >::GetBodyForce () inline virtual
Implements material.
Definition at line 79 of file elastoplastic3D.h.
GetElCoords()
template<class YC > void elastoplastic3D< YC >::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords) virtual
Implements material.
Definition at line 387 of file elastoplastic3D.cpp.
References NRmatrix< T >::assign().
GetMatConstants()
template<class YC > void elastoplastic3D< YC >::GetMatConstants (NRvector< Doub > & consts) inline virtual
Implements material.
Definition at line 69 of file elastoplastic3D.h.
GetMaterialData()
template<class YC > virtual void elastoplastic3D< YC >::GetMaterialData () inline virtual
Definition at line 74 of file elastoplastic3D.h.
GetPlasticStrain()
template<class YC > NRvector< NRtensor< Doub > > elastoplastic3D< YC >::GetPlasticStrain virtual
Implements material.
Definition at line 134 of file elastoplastic3D.cpp.
GetSolution()
template<class YC > NRmatrix< Doub > elastoplastic3D< YC >::GetSolution virtual
Implements material.
Definition at line 519 of file elastoplastic3D.cpp.
PostProcess() [1/2]
template<class YC > void elastoplastic3D< YC >::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & solx, std::vector< std::vector< double >> & soly)
Definition at line 477 of file elastoplastic3D.cpp.
References DebugStop.
PostProcess() [2/2]
template<class YC > void elastoplastic3D< YC >::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, Int var, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 484 of file elastoplastic3D.cpp.
References DebugStop.
PostProcessIntegrationPointVar()
template<class YC > void elastoplastic3D< YC >::PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 491 of file elastoplastic3D.cpp.
References DebugStop.
PostProcessStrain()
template<class YC > void elastoplastic3D< YC >::PostProcessStrain (mesh * inmesh, NRvector< NRvector< NRtensor< Doub >>> & sol) virtual
Implements material.
Definition at line 498 of file elastoplastic3D.cpp.
References DebugStop.
ResetCounter()
template<class YC > void elastoplastic3D< YC >::ResetCounter () inline virtual
Implements material.
Definition at line 58 of file elastoplastic3D.h.
ResetDisplacement()
template<class YC > void elastoplastic3D< YC >::ResetDisplacement virtual
Implements material.
Definition at line 150 of file elastoplastic3D.cpp.
ResetMat()
template<class YC > void elastoplastic3D< YC >::ResetMat virtual
Implements material.
Definition at line 140 of file elastoplastic3D.cpp.
ResetMemory()
template<class YC > void elastoplastic3D< YC >::ResetMemory virtual
Implements material.
Definition at line 53 of file elastoplastic3D.cpp.
ResetPlasticStrain()
template<class YC > void elastoplastic3D< YC >::ResetPlasticStrain virtual
Implements material.
Definition at line 105 of file elastoplastic3D.cpp.
SetMatConstants()
template<class YC > void elastoplastic3D< YC >::SetMatConstants (NRvector< Doub > & consts) inline virtual
Implements material.
Definition at line 64 of file elastoplastic3D.h.
SetMemory()
template<class YC > void elastoplastic3D< YC >::SetMemory (Int ngloblapoints, Int systemsize) virtual
Implements material.
Definition at line 42 of file elastoplastic3D.cpp.
Referenced by beam3dtools::CreateMatAndMesh(), and beam3dtools::CreateMatAndMeshCube().
SetRandomField()
template<class YC > void elastoplastic3D< YC >::SetRandomField (NRmatrix< Doub > hhat)
Definition at line 65 of file elastoplastic3D.cpp.
SetRandomFieldLocal()
template<class YC > void elastoplastic3D< YC >::SetRandomFieldLocal (NRvector< NRmatrix< Doub > > hhatvel)
Definition at line 70 of file elastoplastic3D.cpp.
SolPt()
template<class YC > void elastoplastic3D< YC >::SolPt (const std::vector< std::vector< std::vector< Doub > > > & allcoords, const MatInt & meshtopology, const Int & el, const NRmatrix< Doub > & solG, const Doub & xi, const Doub & eta, NRmatrix< Doub > & xycoords, MatDoub & sol)
Definition at line 470 of file elastoplastic3D.cpp.
References DebugStop.
UpdateBodyForce()
template<class YC > void elastoplastic3D< YC >::UpdateBodyForce (NRmatrix< Doub > newbodyforce)
Definition at line 99 of file elastoplastic3D.cpp.
Referenced by beam3dtools::CreateMatAndMesh(), and beam3dtools::CreateMatAndMeshCube().
UpdateDisplacement() [1/2]
template<class YC > void elastoplastic3D< YC >::UpdateDisplacement (NRmatrix< Doub > displace)
Definition at line 77 of file elastoplastic3D.cpp.
UpdateDisplacement() [2/2]
template<class YC > void elastoplastic3D< YC >::UpdateDisplacement (VectorXd displace) virtual
Implements material.
Definition at line 83 of file elastoplastic3D.cpp.
UpdatePlasticStrain()
template<class YC > void elastoplastic3D< YC >::UpdatePlasticStrain virtual
Implements material.
Definition at line 91 of file elastoplastic3D.cpp.
Member Data Documentation
fbodyforce
template<class YC > NRmatrix<Doub> elastoplastic3D< YC >::fbodyforce private
Definition at line 94 of file elastoplastic3D.h.
fdisplace
template<class YC > NRmatrix<Doub> elastoplastic3D< YC >::fdisplace
Definition at line 105 of file elastoplastic3D.h.
fepspsolitern
template<class YC > NRvector<NRtensor<Doub> > elastoplastic3D< YC >::fepspsolitern
Definition at line 106 of file elastoplastic3D.h.
fepspvec
template<class YC > NRvector<NRtensor<Doub> > elastoplastic3D< YC >::fepspvec
Definition at line 106 of file elastoplastic3D.h.
fglobalcounter
template<class YC > Int elastoplastic3D< YC >::fglobalcounter
Definition at line 107 of file elastoplastic3D.h.
fHHAT
template<class YC > NRmatrix<Doub> elastoplastic3D< YC >::fHHAT
Definition at line 101 of file elastoplastic3D.h.
fhhatvel
template<class YC > NRvector<NRmatrix<Doub> > elastoplastic3D< YC >::fhhatvel
Definition at line 102 of file elastoplastic3D.h.
fOrder
template<class YC > Int elastoplastic3D< YC >::fOrder private
Definition at line 95 of file elastoplastic3D.h.
fYC
template<class YC > YC elastoplastic3D< YC >::fYC
Definition at line 103 of file elastoplastic3D.h.
Referenced by beam3dtools::CreateMatAndMesh(), and beam3dtools::CreateMatAndMeshCube().
The documentation for this class was generated from the following files:
src/elastoplastic3D.h
src/elastoplastic3D.cpp