DCPROJ: mesh Class Reference
mesh Class Reference
#include <mesh.h>
Public Member Functions
mesh (int dim, std::vector< std::vector< std::vector< Doub > > > &allcoords, NRmatrix< Doub > &meshnodes, NRmatrix< Int > &meshtopology)
mesh (int dim, material *mat, std::vector< std::vector< std::vector< Doub > > > &allcoords, NRmatrix< Doub > &meshnodes, NRmatrix< Int > &meshtopology)
mesh (int dim, material *mat, std::vector< std::vector< std::vector< Doub > > > &allcoords, NRmatrix< Doub > &meshnodes, NRmatrix< Int > &meshtopology, MatDoub HHAT)
mesh (mesh &copy)
mesh ()
~mesh ()
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)
MatDoub FindSolution (VecDoub coord, MatDoub datatosearch)
MatDoub TransferSolution (mesh &out, MatDoub datatosearch)
std::vector< std::vector< std::vector< Doub > > > GetAllCoords ()
MatDoub GetMeshNodes ()
MatInt GetMeshTopology ()
MatInt GetMeshTopologyVTK ()
void Assemble (MatDoub &KG, MatDoub &Fint, MatDoub &Fbody)
void Assemble (SparseMatrix< double > &KG, VectorXd &Fint, VectorXd &Fbody)
void FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< int > &ids)
void ComputeSolAndDSol (NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)
void SetHhat (NRmatrix< Doub > HHAT)
void GetHhat (NRmatrix< Doub > &HHAT)
Public Attributes
material * fmaterial
Private Attributes
int fdim
std::vector< std::vector< std::vector< Doub > > > fallcoords
MatDoub fmeshnodes
MatInt fmeshtopology
NRmatrix< Doub > fHHAT
NRvector< MatDoub > fhhatvel
Detailed Description
Definition at line 26 of file mesh.h.
Constructor & Destructor Documentation
mesh() [1/5]
mesh::mesh (int dim, std::vector< std::vector< std::vector< Doub > > > & allcoords, NRmatrix< Doub > & meshnodes, NRmatrix< Int > & meshtopology)
Definition at line 8 of file mesh.cpp.
References fallcoords, fdim, fmeshnodes, and fmeshtopology.
mesh() [2/5]
mesh::mesh (int dim, material * mat, std::vector< std::vector< std::vector< Doub > > > & allcoords, NRmatrix< Doub > & meshnodes, NRmatrix< Int > & meshtopology)
Definition at line 16 of file mesh.cpp.
References fallcoords, fdim, fmaterial, fmeshnodes, and fmeshtopology.
mesh() [3/5]
mesh::mesh (int dim, material * mat, std::vector< std::vector< std::vector< Doub > > > & allcoords, NRmatrix< Doub > & meshnodes, NRmatrix< Int > & meshtopology, MatDoub HHAT)
Definition at line 27 of file mesh.cpp.
References fallcoords, fdim, fHHAT, fmaterial, fmeshnodes, and fmeshtopology.
mesh() [4/5]
mesh::mesh (mesh & copy)
Definition at line 41 of file mesh.cpp.
References fallcoords, fdim, fmeshnodes, fmeshtopology, and mesh().
mesh() [5/5]
mesh::mesh ()
Definition at line 37 of file mesh.cpp.
Referenced by mesh().
~mesh()
mesh::~mesh ()
Definition at line 46 of file mesh.cpp.
References fmaterial.
Member Function Documentation
Assemble() [1/2]
void mesh::Assemble (MatDoub & KG, MatDoub & Fint, MatDoub & Fbody)
Definition at line 304 of file mesh.cpp.
References NRmatrix< T >::assign(), material::CacStiff(), fallcoords, fdim, fHHAT, fhhatvel, fmaterial, fmeshnodes, fmeshtopology, GetElCoords(), material::GetSolution(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), material::ResetCounter(), NRmatrix< T >::resize(), material::SetRandomField(), and material::SetRandomFieldLocal().
Referenced by pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), beam3dtools::SolveElasticBeam(), beam3dtools::SolveElasticCube(), and pressurizedhole::SolveElasticHole().
Assemble() [2/2]
void mesh::Assemble (SparseMatrix< double > & KG, VectorXd & Fint, VectorXd & Fbody)
Definition at line 452 of file mesh.cpp.
References NRmatrix< T >::assign(), material::CacStiff(), fallcoords, fHHAT, fhhatvel, fmaterial, fmeshnodes, fmeshtopology, GetElCoords(), material::GetSolution(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), material::ResetCounter(), NRmatrix< T >::resize(), material::SetRandomField(), and material::SetRandomFieldLocal().
ComputeSolAndDSol()
void mesh::ComputeSolAndDSol (NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol)
Definition at line 399 of file mesh.cpp.
References NRmatrix< T >::assign(), fallcoords, fdim, fmaterial, fmeshnodes, fmeshtopology, GetElCoords(), material::GetSolution(), NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
FindIds()
void mesh::FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< int > & ids)
Definition at line 572 of file mesh.cpp.
References fallcoords, fmeshtopology, GetElCoords(), NRmatrix< T >::nrows(), and NRvector< T >::size().
FindSolution()
MatDoub mesh::FindSolution (VecDoub coord, MatDoub datatosearch)
Definition at line 85 of file mesh.cpp.
References NRmatrix< T >::assign(), fallcoords, fmeshtopology, GetElCoords(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), NRvector< T >::Print(), NRmatrix< T >::Print(), FuncdSearch::set(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Referenced by TransferSolution().
GetAllCoords()
std::vector< std::vector< std::vector< Doub > > > mesh::GetAllCoords ()
Definition at line 51 of file mesh.cpp.
References fallcoords.
Referenced by KLGalerkinRF::AssembleB(), KLGalerkinRF::AssembleC(), elastoplastic2D< YC >::ComputeSolAndDSol(), slopeproject::findbcids(), findbcids(), pressurizedhole::InsertBC(), beam3dtools::InsertBC(), beam3dtools::InsertCubeBC(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), pressurizedhole::LoadBC(), mainlinux(), mainlinuxserial(), mainwindows(), slopeproject::MonteCarloSRM(), KLGalerkinRF::PerfomIntegralOfListconst(), KLGalerkinRF::PerfomIntegralOfListconst2(), postprocess::PostProcess(), elastoplastic2D< YC >::PostProcessStrain(), slopeproject::PrintMCS(), and KLGalerkinRF::SolveGenEigValProblem().
GetElCoords()
void mesh::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords)
Definition at line 74 of file mesh.cpp.
References NRmatrix< T >::assign().
Referenced by Assemble(), ComputeSolAndDSol(), FindIds(), FindSolution(), postprocess::PostProcess(), and TransferSolution().
GetHhat()
void mesh::GetHhat (NRmatrix< Doub > & HHAT) inline
Definition at line 60 of file mesh.h.
References fHHAT.
Referenced by VTKGraphMesh::DrawSolution(), slopeproject::IterativeProcessShearRed(), and slopeproject::IterativeProcessShearRed2().
GetMeshNodes()
MatDoub mesh::GetMeshNodes ()
Definition at line 57 of file mesh.cpp.
References fmeshnodes.
Referenced by KLGalerkinRF::AssembleB(), KLGalerkinRF::AssembleC(), elastoplastic2D< YC >::ComputeSolAndDSol(), VTKGraphMesh::DrawSolution(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), pressurizedhole::LoadBC(), mainlinux(), mainlinuxserial(), MonteCarlo(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), KLGalerkinRF::PerfomIntegralOfListconst(), KLGalerkinRF::PerfomIntegralOfListconst2(), postprocess::PostProcess(), elastoplastic2D< YC >::PostProcessStrain(), slopeproject::PrintMCS(), solvedetermtest(), and KLGalerkinRF::SolveGenEigValProblem().
GetMeshTopology()
MatInt mesh::GetMeshTopology ()
Definition at line 62 of file mesh.cpp.
References fmeshtopology.
Referenced by KLGalerkinRF::AssembleB(), KLGalerkinRF::AssembleC(), elastoplastic2D< YC >::ComputeSolAndDSol(), slopeproject::findbcids(), findbcids(), VTKGraphMesh::GetMeshTopologyVTK(), pressurizedhole::InsertBC(), beam3dtools::InsertBC(), beam3dtools::InsertCubeBC(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), pressurizedhole::LoadBC(), mainlinux(), mainlinuxserial(), MonteCarlo(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), KLGalerkinRF::PerfomIntegralOfListconst(), KLGalerkinRF::PerfomIntegralOfListconst2(), postprocess::PostProcess(), elastoplastic2D< YC >::PostProcessStrain(), slopeproject::PrintMCS(), solvedetermtest(), and KLGalerkinRF::SolveGenEigValProblem().
GetMeshTopologyVTK()
MatInt mesh::GetMeshTopologyVTK ()
SetHhat()
void mesh::SetHhat (NRmatrix< Doub > HHAT) inline
Definition at line 55 of file mesh.h.
References fHHAT.
Referenced by slopeproject::IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), main2(), mainlinux(), mainlinuxserial(), MonteCarlo(), slopeproject::MonteCarloGIM(), and slopeproject::MonteCarloSRM().
TransferSolution()
MatDoub mesh::TransferSolution (mesh & out, MatDoub datatosearch)
Definition at line 190 of file mesh.cpp.
References fallcoords, FindSolution(), fmeshnodes, fmeshtopology, GetElCoords(), and NRmatrix< T >::nrows().
Member Data Documentation
fallcoords
std::vector<std::vector< std::vector<Doub > > > mesh::fallcoords private
Definition at line 71 of file mesh.h.
Referenced by Assemble(), ComputeSolAndDSol(), FindIds(), FindSolution(), GetAllCoords(), mesh(), and TransferSolution().
fdim
int mesh::fdim private
Definition at line 70 of file mesh.h.
Referenced by Assemble(), ComputeSolAndDSol(), and mesh().
fHHAT
NRmatrix<Doub> mesh::fHHAT private
Definition at line 74 of file mesh.h.
Referenced by Assemble(), GetHhat(), mesh(), and SetHhat().
fhhatvel
NRvector<MatDoub> mesh::fhhatvel private
Definition at line 75 of file mesh.h.
Referenced by Assemble().
fmaterial
material* mesh::fmaterial
Definition at line 67 of file mesh.h.
Referenced by Assemble(), ComputeSolAndDSol(), VTKGraphMesh::DrawSolution(), pressurizedhole::InsertBC(), beam3dtools::InsertBC(), beam3dtools::InsertCubeBC(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), pressurizedhole::LoadBC(), mainlinux(), mainlinuxserial(), mesh(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), slopeproject::PrintMCS(), VTKGraphMesh::VTKGraphMesh(), and ~mesh().
fmeshnodes
MatDoub mesh::fmeshnodes private
Definition at line 72 of file mesh.h.
Referenced by Assemble(), ComputeSolAndDSol(), GetMeshNodes(), mesh(), and TransferSolution().
fmeshtopology
MatInt mesh::fmeshtopology private
Definition at line 73 of file mesh.h.
Referenced by Assemble(), ComputeSolAndDSol(), FindIds(), FindSolution(), GetMeshTopology(), mesh(), and TransferSolution().
The documentation for this class was generated from the following files:
src/mesh.h
src/mesh.cpp