DCPROJ: elastmat2D Class Reference
elastmat2D Class Reference
#include <elastmat2D.h>
Public Member Functions
elastmat2D (mesh &inmesh, Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order)
elastmat2D (Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order, MatDoub HHAT)
elastmat2D ()
~elastmat2D ()
void Contribute (MatDoub &ek, MatDoub &ef, Doub xi, Doub eta, Doub w, MatDoub elcoords)
void CacStiff (MatDoub &ek, MatDoub &ef, const MatDoub &elcoords)
void Assemble (MatDoub &KG, MatDoub &FG, const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatDoub &meshnodes, const MatInt meshtopology)
void assembleBandN (MatDoub &B, MatDoub &N, const MatDoub &psis, const MatDoub &GradPhi)
void assembleConstitutiveMatrix (MatDoub &C, Doub mult)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > &allcoords, Int el, MatDoub &elcoords)
void DirichletBC (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)
void ContributeLineNewan (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)
void SolPt (const Int &el, const MatDoub &solG, const Doub &xi, const Doub &eta, MatDoub &xycoords, MatDoub &sol)
void PostProcess (const MatDoub &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)
void PostProcess (const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)
Public Attributes
MatDoub fHHAT
MatDoub fhhatvel
Private Attributes
Doub fyoung
Doub fnu
Doub fbodyforce
Int fplanestress
Doub fthickness
Int fOrder
mesh fmesh
Detailed Description
Definition at line 7 of file elastmat2D.h.
Constructor & Destructor Documentation
elastmat2D() [1/3]
elastmat2D::elastmat2D (mesh & inmesh, Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order)
Definition at line 5 of file elastmat2D.cpp.
elastmat2D() [2/3]
elastmat2D::elastmat2D (Doub young, Doub nu, Doub thickness, Doub bodyforce, Int planestress, Int order, MatDoub HHAT)
Definition at line 16 of file elastmat2D.cpp.
elastmat2D() [3/3]
elastmat2D::elastmat2D ()
Definition at line 27 of file elastmat2D.cpp.
~elastmat2D()
elastmat2D::~elastmat2D ()
Definition at line 32 of file elastmat2D.cpp.
Member Function Documentation
Assemble()
void elastmat2D::Assemble (MatDoub & KG, MatDoub & FG, const std::vector< std::vector< std::vector< Doub > > > & allcoords, const MatDoub & meshnodes, const MatInt meshtopology)
Definition at line 39 of file elastmat2D.cpp.
References NRmatrix< T >::nrows().
assembleBandN()
void elastmat2D::assembleBandN (MatDoub & B, MatDoub & N, const MatDoub & psis, const MatDoub & GradPhi)
Definition at line 176 of file elastmat2D.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
assembleConstitutiveMatrix()
void elastmat2D::assembleConstitutiveMatrix (MatDoub & C, Doub mult)
Definition at line 207 of file elastmat2D.cpp.
References NRmatrix< T >::assign().
CacStiff()
void elastmat2D::CacStiff (MatDoub & ek, MatDoub & ef, const MatDoub & elcoords)
Definition at line 86 of file elastmat2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and shapequad::pointsandweigths().
Contribute()
void elastmat2D::Contribute (MatDoub & ek, MatDoub & ef, Doub xi, Doub eta, Doub w, MatDoub elcoords)
Definition at line 110 of file elastmat2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), shapequad::shapes(), and NRmatrix< T >::Transpose().
ContributeLineNewan()
void elastmat2D::ContributeLineNewan (MatDoub & KG, MatDoub & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 263 of file elastmat2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths1D(), and shapequad::shapes1D().
DirichletBC()
void elastmat2D::DirichletBC (MatDoub & KG, MatDoub & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 230 of file elastmat2D.cpp.
References NRmatrix< T >::nrows().
GetElCoords()
void elastmat2D::GetElCoords (std::vector< std::vector< std::vector< Doub > > > & allcoords, Int el, MatDoub & elcoords)
Definition at line 217 of file elastmat2D.cpp.
References NRmatrix< T >::assign().
Referenced by KLGalerkinRF::AssembleB(), KLGalerkinRF::AssembleC(), and KLGalerkinRF::PerfomIntegralOfListconst().
PostProcess() [1/2]
void elastmat2D::PostProcess (const MatDoub & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 351 of file elastmat2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
PostProcess() [2/2]
void elastmat2D::PostProcess (const MatDoub & nodalsol, std::vector< std::vector< double >> & solx, std::vector< std::vector< double >> & soly)
Definition at line 310 of file elastmat2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
SolPt()
void elastmat2D::SolPt (const Int & el, const MatDoub & solG, const Doub & xi, const Doub & eta, MatDoub & xycoords, MatDoub & sol)
Definition at line 286 of file elastmat2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Referenced by KLGalerkinRF::PerfomIntegralOfListconst2().
Member Data Documentation
fbodyforce
Doub elastmat2D::fbodyforce private
Definition at line 32 of file elastmat2D.h.
fHHAT
MatDoub elastmat2D::fHHAT
Definition at line 38 of file elastmat2D.h.
fhhatvel
MatDoub elastmat2D::fhhatvel
Definition at line 39 of file elastmat2D.h.
fmesh
mesh elastmat2D::fmesh private
Definition at line 36 of file elastmat2D.h.
fnu
Doub elastmat2D::fnu private
Definition at line 31 of file elastmat2D.h.
fOrder
Int elastmat2D::fOrder private
Definition at line 35 of file elastmat2D.h.
fplanestress
Int elastmat2D::fplanestress private
Definition at line 33 of file elastmat2D.h.
fthickness
Doub elastmat2D::fthickness private
Definition at line 34 of file elastmat2D.h.
fyoung
Doub elastmat2D::fyoung private
Definition at line 30 of file elastmat2D.h.
The documentation for this class was generated from the following files:
src/elastmat2D.h
src/elastmat2D.cpp