DCPROJ: gridmesh Class Reference
gridmesh Class Reference
#include <gridmesh.h>
Public Member Functions
gridmesh (Doub L, Doub h, Int nx, Int ny, Int order)
~gridmesh ()
void CreateMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology)
void PrintAllCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, MatInt meshtopology)
void PrintGMeshVTK (std::vector< std::vector< std::vector< Doub > > > allcoords, MatInt meshtopology, std::ofstream &file)
void GetData (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology)
Static Public Member Functions
static void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)
static void FindIdsInPath (const MatDoub &path, std::vector< std::vector< std::vector< Doub > > > &allcoords, MatInt &meshtopology, std::vector< int > &idpath)
static void Line (VecDoub a, VecDoub b, Int ndivs, MatDoub &path)
Public Attributes
std::vector< std::vector< std::vector< Doub > > > fallcoords
MatDoub fmeshcoords
MatInt fmeshtopology
Int forder
Doub fL
Doub fh
Int fnx
Int fny
Detailed Description
Definition at line 4 of file gridmesh.h.
Constructor & Destructor Documentation
gridmesh()
gridmesh::gridmesh (Doub L, Doub h, Int nx, Int ny, Int order)
Definition at line 7 of file gridmesh.cpp.
References fh, fL, fnx, fny, and forder.
~gridmesh()
gridmesh::~gridmesh ()
Definition at line 17 of file gridmesh.cpp.
Member Function Documentation
CreateMesh()
void gridmesh::CreateMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology)
Definition at line 22 of file gridmesh.cpp.
References fallcoords, fh, fL, fmeshcoords, fmeshtopology, fnx, fny, forder, NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
FindIdsInPath()
void gridmesh::FindIdsInPath (const MatDoub & path, std::vector< std::vector< std::vector< Doub > > > & allcoords, MatInt & meshtopology, std::vector< int > & idpath) static
Definition at line 271 of file gridmesh.cpp.
References GetElCoords(), and NRmatrix< T >::nrows().
Referenced by findbcids(), IterativeCho(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), and pressurizedhole::LoadBC().
GetData()
void gridmesh::GetData (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology) inline
Definition at line 17 of file gridmesh.h.
References fallcoords, fmeshcoords, and fmeshtopology.
GetElCoords()
void gridmesh::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords) static
Definition at line 257 of file gridmesh.cpp.
References NRmatrix< T >::assign().
Referenced by FindEl(), FindIdsInPath(), and PrintGMeshVTK().
Line()
void gridmesh::Line (VecDoub a, VecDoub b, Int ndivs, MatDoub & path) static
Definition at line 305 of file gridmesh.cpp.
References NRmatrix< T >::assign().
Referenced by findbcids(), IterativeCho(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
PrintAllCoords()
void gridmesh::PrintAllCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, MatInt meshtopology)
Definition at line 243 of file gridmesh.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
PrintGMeshVTK()
void gridmesh::PrintGMeshVTK (std::vector< std::vector< std::vector< Doub > > > allcoords, MatInt meshtopology, std::ofstream & file)
Definition at line 327 of file gridmesh.cpp.
References GetElCoords(), and NRmatrix< T >::nrows().
Member Data Documentation
fallcoords
std::vector<std::vector< std::vector<Doub > > > gridmesh::fallcoords
Definition at line 32 of file gridmesh.h.
Referenced by CreateMesh(), and GetData().
fh
Doub gridmesh::fh
Definition at line 37 of file gridmesh.h.
Referenced by CreateMesh(), and gridmesh().
fL
Doub gridmesh::fL
Definition at line 36 of file gridmesh.h.
Referenced by CreateMesh(), and gridmesh().
fmeshcoords
MatDoub gridmesh::fmeshcoords
Definition at line 33 of file gridmesh.h.
Referenced by CreateMesh(), and GetData().
fmeshtopology
MatInt gridmesh::fmeshtopology
Definition at line 34 of file gridmesh.h.
Referenced by CreateMesh(), and GetData().
fnx
Int gridmesh::fnx
Definition at line 38 of file gridmesh.h.
Referenced by CreateMesh(), and gridmesh().
fny
Int gridmesh::fny
Definition at line 39 of file gridmesh.h.
Referenced by CreateMesh(), and gridmesh().
forder
Int gridmesh::forder
Definition at line 35 of file gridmesh.h.
Referenced by CreateMesh(), and gridmesh().
The documentation for this class was generated from the following files:
src/gridmesh.h
src/gridmesh.cpp