DCPROJ: elastoplastic2D< YC > Class Template Reference
elastoplastic2D< YC > Class Template Reference
#include <elastoplastic2D.h>
Public Member Functions
elastoplastic2D (Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order, NRmatrix< Doub > HHAT)
elastoplastic2D (Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order)
elastoplastic2D (Doub young, Doub nu, Doub sigy, Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order, NRmatrix< Doub > HHAT)
elastoplastic2D (elastoplastic2D &copy)
elastoplastic2D ()
~elastoplastic2D ()
void Contribute (NRmatrix< Doub > &ek, NRmatrix< Doub > &efint, NRmatrix< Doub > &efbody, NRvector< Doub > ptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
void ContributeEig (NRmatrix< Doub > &ek, NRmatrix< Doub > &efint, NRmatrix< Doub > &efbody, NRvector< Doub > ptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
void CacStiff (NRmatrix< Doub > &ek, NRmatrix< Doub > &efint, NRmatrix< Doub > &efbody, const NRmatrix< Doub > &elcoords, NRmatrix< Doub > eldisplace)
void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, NRmatrix< Doub > &KG, NRmatrix< Doub > &Fint, NRmatrix< Doub > &Fbody)
void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, SparseMatrix< double > &KG, VectorXd &Fint, VectorXd &Fbody)
void assembleBandN (NRmatrix< Doub > &B, NRmatrix< Doub > &N, const NRmatrix< Doub > &psis, const NRmatrix< Doub > &GradPhi)
void assembleBandN (MatrixXd &B, MatrixXd &N, const NRmatrix< Doub > &psis, const NRmatrix< Doub > &GradPhi)
void assembleConstitutiveMatrix (MatDoub &C, Doub mult)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)
void DirichletBC (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, std::vector< int > ids, Int dir, Int val)
void DirichletBC (SparseMatrix< double > &KG, VectorXd &FG, std::vector< int > ids, Int dir, Int val)
void ContributeLineNewan (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, std::vector< int > ids, Int dir, Int val)
void ContributeCurvedLine (NRmatrix< Doub > &KG, NRmatrix< Doub > &FG, NRmatrix< Doub > meshnodes, MatInt linetopology, Doub force)
void SolPt (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt &meshtopology, const Int &el, const NRmatrix< Doub > &solG, const Doub &xi, const Doub &eta, NRmatrix< Doub > &xycoords, MatDoub &sol)
void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)
void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, Int var, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &sol)
void PostProcessStrain (mesh *inmesh, NRvector< NRvector< NRtensor< Doub >>> &sol)
void PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > &nodalsol, std::vector< std::vector< double >> &sol)
void SetRandomField (NRmatrix< Doub > hhat)
void SetRandomFieldLocal (NRvector< NRmatrix< Doub > > hhatvel)
void SetMemory (Int ngloblapoints, Int systemsize)
void UpdateDisplacement (NRmatrix< Doub > displace)
void UpdateDisplacement (VectorXd displace)
void UpdatePlasticStrain ()
void UpdateBodyForce (NRmatrix< Doub > newbodyforce)
void ResetPlasticStrain ()
void ResetDisplacement ()
void ResetMat ()
void ResetMemory ()
NRmatrix< Doub > GetSolution ()
NRvector< NRtensor< Doub > > GetPlasticStrain ()
void ComputeSolution (mesh *inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)
void ComputeSolAndDSol (mesh *inmesh, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)
void ComputeSolAndDSol (mesh *inmesh, NRvector< NRmatrix< Doub >> &sol, NRvector< NRmatrix< Doub >> &dsol)
Doub ComputePhi (NRtensor< Doub > eps)
void ResetCounter ()
void SetMatConstants (NRvector< Doub > &consts)
void GetMatConstants (NRvector< Doub > &consts)
virtual void GetMaterialData ()
NRmatrix< Doub > GetBodyForce ()
Int getIndex (vector< int > indexvec, int inode)
void deleteduplicates (std::vector< int > &v)
Public Member Functions inherited from material
material ()
~material ()
virtual void Contribute (MatDoub &ek, MatDoub &efint, MatDoub &efbody, NRvector< Doub > ptsw, MatDoub elcoords, MatDoub eldisplace)=0
virtual void CacStiff (MatDoub &ek, MatDoub &efint, MatDoub &efbody, const MatDoub &elcoords, MatDoub eldisplace)=0
virtual void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub &KG, MatDoub &Fint, MatDoub &Fbody)=0
virtual void assembleBandN (MatDoub &B, MatDoub &N, const MatDoub &psis, const MatDoub &GradPhi)=0
virtual void DirichletBC (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeLineNewan (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeCurvedLine (MatDoub &KG, MatDoub &FG, MatDoub meshnodes, MatInt linetopology, Doub force)=0
virtual void SolPt (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt &meshtopology, const Int &el, const MatDoub &solG, const Doub &xi, const Doub &eta, MatDoub &xycoords, MatDoub &sol)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, Int var, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void SetRandomField (MatDoub hhat)=0
virtual void UpdateDisplacement (MatDoub displace)=0
virtual void UpdateBodyForce (MatDoub newbodyforce)=0
virtual void SetRandomFieldLocal (NRvector< MatDoub > hhatvel)=0
Public Attributes
NRmatrix< Doub > fHHAT
NRvector< NRmatrix< Doub > > fhhatvel
YC fYC
NRmatrix< Doub > fdisplace
NRvector< NRtensor< Doub > > fepspvec
NRvector< NRtensor< Doub > > fepspsolitern
Int fglobalcounter
Private Attributes
NRmatrix< Doub > fbodyforce
Int fplanestress
Doub fthickness
Int fOrder
Detailed Description
template<class YC>
class elastoplastic2D< YC >
Definition at line 13 of file elastoplastic2D.h.
Constructor & Destructor Documentation
elastoplastic2D() [1/5]
template<class YC > elastoplastic2D< YC >::elastoplastic2D (Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order, NRmatrix< Doub > HHAT)
Definition at line 29 of file elastoplastic2D.cpp.
elastoplastic2D() [2/5]
template<class YC > elastoplastic2D< YC >::elastoplastic2D (Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order)
Definition at line 6 of file elastoplastic2D.cpp.
elastoplastic2D() [3/5]
template<class YC > elastoplastic2D< YC >::elastoplastic2D (Doub young, Doub nu, Doub sigy, Doub thickness, NRmatrix< Doub > bodyforce, Int planestress, Int order, NRmatrix< Doub > HHAT)
Definition at line 18 of file elastoplastic2D.cpp.
elastoplastic2D() [4/5]
template<class YC > elastoplastic2D< YC >::elastoplastic2D (elastoplastic2D< YC > & copy)
Definition at line 40 of file elastoplastic2D.cpp.
elastoplastic2D() [5/5]
template<class YC > elastoplastic2D< YC >::elastoplastic2D
Definition at line 45 of file elastoplastic2D.cpp.
~elastoplastic2D()
template<class YC > elastoplastic2D< YC >::~elastoplastic2D
Definition at line 52 of file elastoplastic2D.cpp.
Member Function Documentation
Assemble() [1/2]
template<class YC > void elastoplastic2D< YC >::Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, NRmatrix< Doub > & KG, NRmatrix< Doub > & Fint, NRmatrix< Doub > & Fbody)
Definition at line 561 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
Assemble() [2/2]
template<class YC > void elastoplastic2D< YC >::Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, SparseMatrix< double > & KG, VectorXd & Fint, VectorXd & Fbody)
Definition at line 647 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
assembleBandN() [1/2]
template<class YC > void elastoplastic2D< YC >::assembleBandN (MatrixXd & B, MatrixXd & N, const NRmatrix< Doub > & psis, const NRmatrix< Doub > & GradPhi)
Definition at line 734 of file elastoplastic2D.cpp.
References NRmatrix< T >::nrows().
assembleBandN() [2/2]
template<class YC > void elastoplastic2D< YC >::assembleBandN (NRmatrix< Doub > & B, NRmatrix< Doub > & N, const NRmatrix< Doub > & psis, const NRmatrix< Doub > & GradPhi)
Definition at line 770 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
assembleConstitutiveMatrix()
template<class YC > void elastoplastic2D< YC >::assembleConstitutiveMatrix (MatDoub & C, Doub mult)
Definition at line 802 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign().
CacStiff()
template<class YC > void elastoplastic2D< YC >::CacStiff (NRmatrix< Doub > & ek, NRmatrix< Doub > & efint, NRmatrix< Doub > & efbody, const NRmatrix< Doub > & elcoords, NRmatrix< Doub > eldisplace)
Definition at line 436 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::nrows(), and shapequad::pointsandweigths().
ComputePhi()
template<class YC > Doub elastoplastic2D< YC >::ComputePhi (NRtensor< Doub > eps) inline virtual
Implements material.
Definition at line 78 of file elastoplastic2D.h.
ComputeSolAndDSol() [1/2]
template<class YC > void elastoplastic2D< YC >::ComputeSolAndDSol (mesh * inmesh, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) virtual
Implements material.
Definition at line 1246 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), DebugStop, mesh::GetAllCoords(), mesh::GetMeshTopology(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths(), shapequad::shapes(), and NRmatrix< T >::Transpose().
ComputeSolAndDSol() [2/2]
template<class YC > void elastoplastic2D< YC >::ComputeSolAndDSol (mesh * inmesh, NRvector< NRmatrix< Doub >> & sol, NRvector< NRmatrix< Doub >> & dsol) virtual
Implements material.
Definition at line 1308 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), DebugStop, mesh::GetAllCoords(), shapequad::GetBaseNodes(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths(), NRmatrix< T >::resize(), shapequad::shapes(), and NRmatrix< T >::Transpose().
ComputeSolution()
template<class YC > void elastoplastic2D< YC >::ComputeSolution (mesh * inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) virtual
Implements material.
Definition at line 1551 of file elastoplastic2D.cpp.
References DebugStop, NRmatrix< T >::Mult(), NRmatrix< T >::resize(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Contribute()
template<class YC > void elastoplastic2D< YC >::Contribute (NRmatrix< Doub > & ek, NRmatrix< Doub > & efint, NRmatrix< Doub > & efbody, NRvector< Doub > ptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
Definition at line 313 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), DebugStop, NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), shapequad::shapes(), and NRmatrix< T >::Transpose().
ContributeCurvedLine()
template<class YC > void elastoplastic2D< YC >::ContributeCurvedLine (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, NRmatrix< Doub > meshnodes, MatInt linetopology, Doub force)
Definition at line 919 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths1D(), shapequad::shapes1D(), and NRmatrix< T >::Transpose().
ContributeEig()
template<class YC > void elastoplastic2D< YC >::ContributeEig (NRmatrix< Doub > & ek, NRmatrix< Doub > & efint, NRmatrix< Doub > & efbody, NRvector< Doub > ptsw, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace)
Definition at line 189 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::FromEigen(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), shapequad::shapes(), NRmatrix< T >::ToEigen(), and NRmatrix< T >::Transpose().
ContributeLineNewan()
template<class YC > void elastoplastic2D< YC >::ContributeLineNewan (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 894 of file elastoplastic2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths1D(), and shapequad::shapes1D().
deleteduplicates()
template<class YC > void elastoplastic2D< YC >::deleteduplicates (std::vector< int > & v) inline
Definition at line 126 of file elastoplastic2D.h.
DirichletBC() [1/2]
template<class YC > void elastoplastic2D< YC >::DirichletBC (NRmatrix< Doub > & KG, NRmatrix< Doub > & FG, std::vector< int > ids, Int dir, Int val)
Definition at line 825 of file elastoplastic2D.cpp.
References NRmatrix< T >::nrows().
DirichletBC() [2/2]
template<class YC > void elastoplastic2D< YC >::DirichletBC (SparseMatrix< double > & KG, VectorXd & FG, std::vector< int > ids, Int dir, Int val) virtual
Implements material.
Definition at line 859 of file elastoplastic2D.cpp.
GetBodyForce()
template<class YC > NRmatrix<Doub> elastoplastic2D< YC >::GetBodyForce () inline virtual
Implements material.
Definition at line 105 of file elastoplastic2D.h.
GetElCoords()
template<class YC > void elastoplastic2D< YC >::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords) virtual
Implements material.
Definition at line 813 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign().
getIndex()
template<class YC > Int elastoplastic2D< YC >::getIndex (vector< int > indexvec, int inode) inline
Definition at line 111 of file elastoplastic2D.h.
GetMatConstants()
template<class YC > void elastoplastic2D< YC >::GetMatConstants (NRvector< Doub > & consts) inline virtual
Implements material.
Definition at line 95 of file elastoplastic2D.h.
GetMaterialData()
template<class YC > virtual void elastoplastic2D< YC >::GetMaterialData () inline virtual
Definition at line 100 of file elastoplastic2D.h.
GetPlasticStrain()
template<class YC > NRvector< NRtensor< Doub > > elastoplastic2D< YC >::GetPlasticStrain virtual
Implements material.
Definition at line 164 of file elastoplastic2D.cpp.
GetSolution()
template<class YC > NRmatrix< Doub > elastoplastic2D< YC >::GetSolution virtual
Implements material.
Definition at line 1587 of file elastoplastic2D.cpp.
Referenced by main2(), and MonteCarlo().
PostProcess() [1/2]
template<class YC > void elastoplastic2D< YC >::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & solx, std::vector< std::vector< double >> & soly)
Definition at line 1015 of file elastoplastic2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Referenced by main2().
PostProcess() [2/2]
template<class YC > void elastoplastic2D< YC >::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, Int var, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 1059 of file elastoplastic2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
PostProcessIntegrationPointVar()
template<class YC > void elastoplastic2D< YC >::PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, NRmatrix< Doub > meshnodes, MatInt meshtopology, const NRmatrix< Doub > & nodalsol, std::vector< std::vector< double >> & sol)
Definition at line 1102 of file elastoplastic2D.cpp.
References NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::pointsandweigths(), shapequad::shapes(), and NRmatrix< T >::Transpose().
Referenced by main2(), and MonteCarlo().
PostProcessStrain()
template<class YC > void elastoplastic2D< YC >::PostProcessStrain (mesh * inmesh, NRvector< NRvector< NRtensor< Doub >>> & sol) virtual
Implements material.
Definition at line 1145 of file elastoplastic2D.cpp.
References mesh::GetAllCoords(), shapequad::GetBaseNodes(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), NRmatrix< T >::nrows(), shapequad::pointsandweigths(), NRvector< T >::Print(), NRmatrix< T >::Print(), NRvector< T >::resize(), and NRmatrix< T >::resize().
ResetCounter()
template<class YC > void elastoplastic2D< YC >::ResetCounter () inline virtual
Implements material.
Definition at line 84 of file elastoplastic2D.h.
ResetDisplacement()
template<class YC > void elastoplastic2D< YC >::ResetDisplacement virtual
Implements material.
Definition at line 180 of file elastoplastic2D.cpp.
ResetMat()
template<class YC > void elastoplastic2D< YC >::ResetMat virtual
Implements material.
Definition at line 170 of file elastoplastic2D.cpp.
Referenced by main2().
ResetMemory()
template<class YC > void elastoplastic2D< YC >::ResetMemory virtual
Implements material.
Definition at line 82 of file elastoplastic2D.cpp.
ResetPlasticStrain()
template<class YC > void elastoplastic2D< YC >::ResetPlasticStrain virtual
Implements material.
Definition at line 134 of file elastoplastic2D.cpp.
SetMatConstants()
template<class YC > void elastoplastic2D< YC >::SetMatConstants (NRvector< Doub > & consts) inline virtual
Implements material.
Definition at line 90 of file elastoplastic2D.h.
Referenced by MonteCarlo().
SetMemory()
template<class YC > void elastoplastic2D< YC >::SetMemory (Int ngloblapoints, Int systemsize) virtual
Implements material.
Definition at line 71 of file elastoplastic2D.cpp.
Referenced by pressurizedhole::CreateMatAndMesh(), createrandomfield(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), mainwindows(), and MonteCarlo().
SetRandomField()
template<class YC > void elastoplastic2D< YC >::SetRandomField (NRmatrix< Doub > hhat)
Definition at line 94 of file elastoplastic2D.cpp.
Referenced by MonteCarlo().
SetRandomFieldLocal()
template<class YC > void elastoplastic2D< YC >::SetRandomFieldLocal (NRvector< NRmatrix< Doub > > hhatvel)
Definition at line 99 of file elastoplastic2D.cpp.
SolPt()
template<class YC > void elastoplastic2D< YC >::SolPt (const std::vector< std::vector< std::vector< Doub > > > & allcoords, const MatInt & meshtopology, const Int & el, const NRmatrix< Doub > & solG, const Doub & xi, const Doub & eta, NRmatrix< Doub > & xycoords, MatDoub & sol)
Definition at line 991 of file elastoplastic2D.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), shapequad::shapes(), and NRmatrix< T >::Transpose().
UpdateBodyForce()
template<class YC > void elastoplastic2D< YC >::UpdateBodyForce (NRmatrix< Doub > newbodyforce)
Definition at line 128 of file elastoplastic2D.cpp.
Referenced by pressurizedhole::CreateMatAndMesh(), createrandomfield(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), mainwindows(), and MonteCarlo().
UpdateDisplacement() [1/2]
template<class YC > void elastoplastic2D< YC >::UpdateDisplacement (NRmatrix< Doub > displace)
Definition at line 106 of file elastoplastic2D.cpp.
UpdateDisplacement() [2/2]
template<class YC > void elastoplastic2D< YC >::UpdateDisplacement (VectorXd displace) virtual
Implements material.
Definition at line 112 of file elastoplastic2D.cpp.
UpdatePlasticStrain()
template<class YC > void elastoplastic2D< YC >::UpdatePlasticStrain virtual
Implements material.
Definition at line 120 of file elastoplastic2D.cpp.
Member Data Documentation
fbodyforce
template<class YC > NRmatrix<Doub> elastoplastic2D< YC >::fbodyforce private
Definition at line 138 of file elastoplastic2D.h.
fdisplace
template<class YC > NRmatrix<Doub> elastoplastic2D< YC >::fdisplace
Definition at line 151 of file elastoplastic2D.h.
fepspsolitern
template<class YC > NRvector<NRtensor<Doub> > elastoplastic2D< YC >::fepspsolitern
Definition at line 152 of file elastoplastic2D.h.
fepspvec
template<class YC > NRvector<NRtensor<Doub> > elastoplastic2D< YC >::fepspvec
Definition at line 152 of file elastoplastic2D.h.
fglobalcounter
template<class YC > Int elastoplastic2D< YC >::fglobalcounter
Definition at line 153 of file elastoplastic2D.h.
fHHAT
template<class YC > NRmatrix<Doub> elastoplastic2D< YC >::fHHAT
Definition at line 147 of file elastoplastic2D.h.
fhhatvel
template<class YC > NRvector<NRmatrix<Doub> > elastoplastic2D< YC >::fhhatvel
Definition at line 148 of file elastoplastic2D.h.
fOrder
template<class YC > Int elastoplastic2D< YC >::fOrder private
Definition at line 141 of file elastoplastic2D.h.
fplanestress
template<class YC > Int elastoplastic2D< YC >::fplanestress private
Definition at line 139 of file elastoplastic2D.h.
fthickness
template<class YC > Doub elastoplastic2D< YC >::fthickness private
Definition at line 140 of file elastoplastic2D.h.
fYC
template<class YC > YC elastoplastic2D< YC >::fYC
Definition at line 149 of file elastoplastic2D.h.
Referenced by pressurizedhole::CreateMatAndMesh(), createrandomfield(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), and mainwindows().
The documentation for this class was generated from the following files:
src/elastoplastic2D.h
src/elastoplastic2D.cpp