DCPROJ: NRmatrix3D< T > Class Template Reference
NRmatrix3D< T > Class Template Reference
#include <nr3.h>
Public Types
typedef NRmatrix< NRvector< T > > value_type
Public Member Functions
NRmatrix3D ()
NRmatrix3D (int n, int m, int k)
~NRmatrix3D ()
void Print ()
Private Attributes
NRmatrix< NRvector< T > > vv
T *** v
Detailed Description
template<class T>
class NRmatrix3D< T >
Definition at line 1290 of file nr3.h.
Member Typedef Documentation
value_type
template<class T > typedef NRmatrix<NRvector<T> > NRmatrix3D< T >::value_type
Definition at line 1301 of file nr3.h.
Constructor & Destructor Documentation
NRmatrix3D() [1/2]
template<class T > NRmatrix3D< T >::NRmatrix3D
Definition at line 1309 of file nr3.h.
NRmatrix3D() [2/2]
template<class T > NRmatrix3D< T >::NRmatrix3D (int n, int m, int k)
Definition at line 1312 of file nr3.h.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
~NRmatrix3D()
template<class T > NRmatrix3D< T >::~NRmatrix3D ()
Member Function Documentation
Print()
template<class T > void NRmatrix3D< T >::Print ()
Member Data Documentation
v
template<class T > T*** NRmatrix3D< T >::v private
Definition at line 1293 of file nr3.h.
vv
template<class T > NRmatrix<NRvector<T> > NRmatrix3D< T >::vv private
Definition at line 1292 of file nr3.h.
The documentation for this class was generated from the following file:
src/nr3.h