DCPROJ: pressurizedhole Class Reference
pressurizedhole Class Reference
#include <pressurizedhole.h>
Public Member Functions
pressurizedhole ()
pressurizedhole (mesh *inmesh)
~pressurizedhole ()
void SolveElasticHole ()
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology, string filenameel, string filenamecoord)
template<class T >
std::vector< T > vecstr_to_vec (std::vector< std::string > vs)
void FindIdsInFace (NRvector< double > constcoorddata, int constcoord, std::vector< std::vector< std::vector< Doub > > > &allcoords, MatInt &meshtopology, std::vector< int > &idsface)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, NRmatrix< Doub > &elcoords)
void SolveEigenSparse (MatDoub A, MatDoub b, MatDoub &x)
void SolveEigen (MatDoub A, MatDoub b, MatDoub &x)
void CreateMatAndMesh (mesh &getmesh, material &mat)
void IterativeProcess ()
void InsertBC (mesh &mesh0, NRmatrix< Doub > &K, NRmatrix< Doub > &F)
void LoadBC (mesh &mesh0, NRmatrix< Doub > &K, NRmatrix< Doub > &F)
Doub computelamda (MatDoub &dwb, MatDoub &dws, MatDoub &dw, Doub &l)
std::vector< std::vector< int > > LineTopology (std::vector< int > ids, Int order)
void ToMatInt (std::vector< std::vector< int >> in, MatInt &out)
void FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< std::vector< std::vector< Doub > > > &allcoords, MatInt &meshtopology, std::vector< int > &ids)
template<class T >
void OutPutPost (NRmatrix< T > &postdata, std::ofstream &file)
void OutPutFile (MatDoub &postdata, std::ofstream &file)
void OutPutPost (std::vector< std::vector< double >> &postdata, std::ofstream &file)
template<class T >
std::vector< T > vecstr_to_vec (std::vector< string > vs)
Private Attributes
mesh * fmesh
Detailed Description
Definition at line 16 of file pressurizedhole.h.
Constructor & Destructor Documentation
pressurizedhole() [1/2]
pressurizedhole::pressurizedhole ()
Definition at line 4 of file pressurizedhole.cpp.
pressurizedhole() [2/2]
pressurizedhole::pressurizedhole (mesh * inmesh)
Definition at line 9 of file pressurizedhole.cpp.
References fmesh.
~pressurizedhole()
pressurizedhole::~pressurizedhole ()
Definition at line 14 of file pressurizedhole.cpp.
Member Function Documentation
computelamda()
Doub pressurizedhole::computelamda (MatDoub & dwb, MatDoub & dws, MatDoub & dw, Doub & l)
CreateMatAndMesh()
void pressurizedhole::CreateMatAndMesh (mesh & getmesh, material & mat)
Definition at line 124 of file pressurizedhole.cpp.
References NRmatrix< T >::assign(), elastoplastic2D< YC >::fYC, NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), ReadMesh(), elastoplastic2D< YC >::SetMemory(), vonmises::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
Referenced by IterativeProcess(), and SolveElasticHole().
FindIds()
void pressurizedhole::FindIds (NRvector< double > constcoorddata, NRvector< int > constcoord, std::vector< std::vector< std::vector< Doub > > > & allcoords, MatInt & meshtopology, std::vector< int > & ids)
Definition at line 394 of file pressurizedhole.cpp.
References GetElCoords(), NRmatrix< T >::nrows(), and NRvector< T >::size().
Referenced by InsertBC().
FindIdsInFace()
void pressurizedhole::FindIdsInFace (NRvector< double > constcoorddata, int constcoord, std::vector< std::vector< std::vector< Doub > > > & allcoords, MatInt & meshtopology, std::vector< int > & idsface)
GetElCoords()
void pressurizedhole::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, NRmatrix< Doub > & elcoords)
Definition at line 450 of file pressurizedhole.cpp.
References NRmatrix< T >::assign().
Referenced by FindIds().
InsertBC()
void pressurizedhole::InsertBC (mesh & mesh0, NRmatrix< Doub > & K, NRmatrix< Doub > & F)
Definition at line 197 of file pressurizedhole.cpp.
References material::DirichletBC(), FindIds(), mesh::fmaterial, mesh::GetAllCoords(), and mesh::GetMeshTopology().
Referenced by IterativeProcess(), and SolveElasticHole().
IterativeProcess()
void pressurizedhole::IterativeProcess ()
Definition at line 20 of file pressurizedhole.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), material::ComputeSolAndDSol(), CreateMatAndMesh(), VTKGraphMesh::DrawSolution(), mesh::fmaterial, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), InsertBC(), LoadBC(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), SolveEigen(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
LineTopology()
std::vector< std::vector< int > > pressurizedhole::LineTopology (std::vector< int > ids, Int order)
Definition at line 465 of file pressurizedhole.cpp.
Referenced by LoadBC().
LoadBC()
void pressurizedhole::LoadBC (mesh & mesh0, NRmatrix< Doub > & K, NRmatrix< Doub > & F)
Definition at line 168 of file pressurizedhole.cpp.
References NRmatrix< T >::assign(), material::ContributeCurvedLine(), gridmesh::FindIdsInPath(), mesh::fmaterial, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), LineTopology(), and ToMatInt().
Referenced by IterativeProcess().
OutPutFile()
void pressurizedhole::OutPutFile (MatDoub & postdata, std::ofstream & file) inline
Definition at line 62 of file pressurizedhole.h.
References NRmatrix< T >::nrows().
Referenced by IterativeProcess().
OutPutPost() [1/2]
template<class T > void pressurizedhole::OutPutPost (NRmatrix< T > & postdata, std::ofstream & file) inline
Definition at line 48 of file pressurizedhole.h.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by CreateMatAndMesh(), and IterativeProcess().
OutPutPost() [2/2]
void pressurizedhole::OutPutPost (std::vector< std::vector< double >> & postdata, std::ofstream & file) inline
Definition at line 73 of file pressurizedhole.h.
ReadMesh()
void pressurizedhole::ReadMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology, string filenameel, string filenamecoord)
Definition at line 302 of file pressurizedhole.cpp.
References NRmatrix< T >::CopyFromVector(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by CreateMatAndMesh().
SolveEigen()
void pressurizedhole::SolveEigen (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 251 of file pressurizedhole.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess(), and SolveElasticHole().
SolveEigenSparse()
void pressurizedhole::SolveEigenSparse (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 268 of file pressurizedhole.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
SolveElasticHole()
void pressurizedhole::SolveElasticHole ()
Definition at line 235 of file pressurizedhole.cpp.
References mesh::Assemble(), CreateMatAndMesh(), InsertBC(), NRmatrix< T >::Print(), and SolveEigen().
ToMatInt()
void pressurizedhole::ToMatInt (std::vector< std::vector< int >> in, MatInt & out)
Definition at line 483 of file pressurizedhole.cpp.
References NRmatrix< T >::assign().
Referenced by LoadBC().
vecstr_to_vec() [1/2]
template<class T > std::vector<T> pressurizedhole::vecstr_to_vec (std::vector< std::string > vs)
vecstr_to_vec() [2/2]
template<class T > std::vector<T> pressurizedhole::vecstr_to_vec (std::vector< string > vs)
Definition at line 381 of file pressurizedhole.cpp.
Member Data Documentation
fmesh
mesh* pressurizedhole::fmesh private
Definition at line 90 of file pressurizedhole.h.
Referenced by pressurizedhole().
The documentation for this class was generated from the following files:
src/pressurizedhole.h
src/pressurizedhole.cpp