DCPROJ: shapehexahedron Class Reference
shapehexahedron Class Reference
#include <shapehexahedron.h>
Public Member Functions
shapehexahedron (int order, int type)
shapehexahedron ()
~shapehexahedron ()
void shapes (MatDoub &psis, MatDoub &gradpsis, Doub xi, Doub eta, Doub zeta)
void shapes (MatrixXd &psis, MatrixXd &gradpsis, double xi, double eta)
void shapes1D (MatDoub &psis, MatDoub &gradpsis, Doub xi)
void pointsandweigths (MatDoub &pts)
void pointsandweigths1D (MatDoub &pts)
Protected Attributes
int forder
int ftype
Detailed Description
Definition at line 3 of file shapehexahedron.h.
Constructor & Destructor Documentation
shapehexahedron() [1/2]
shapehexahedron::shapehexahedron (int order, int type) inline
Definition at line 6 of file shapehexahedron.h.
References forder, and ftype.
shapehexahedron() [2/2]
shapehexahedron::shapehexahedron () inline
Definition at line 12 of file shapehexahedron.h.
~shapehexahedron()
shapehexahedron::~shapehexahedron () inline
Definition at line 15 of file shapehexahedron.h.
Member Function Documentation
pointsandweigths()
void shapehexahedron::pointsandweigths (MatDoub & pts) inline
Definition at line 456 of file shapehexahedron.h.
References forder, and NRmatrix< T >::resize().
Referenced by elastoplastic3D< YC >::CacStiff(), beam3dtools::CreateMatAndMesh(), and beam3dtools::CreateMatAndMeshCube().
pointsandweigths1D()
void shapehexahedron::pointsandweigths1D (MatDoub & pts) inline
Definition at line 551 of file shapehexahedron.h.
References NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
shapes() [1/2]
void shapehexahedron::shapes (MatDoub & psis, MatDoub & gradpsis, Doub xi, Doub eta, Doub zeta) inline
Definition at line 20 of file shapehexahedron.h.
References NRmatrix< T >::assign(), and forder.
Referenced by elastoplastic3D< YC >::Contribute().
shapes() [2/2]
void shapehexahedron::shapes (MatrixXd & psis, MatrixXd & gradpsis, double xi, double eta) inline
Definition at line 359 of file shapehexahedron.h.
References forder.
shapes1D()
void shapehexahedron::shapes1D (MatDoub & psis, MatDoub & gradpsis, Doub xi) inline
Definition at line 419 of file shapehexahedron.h.
References forder, and NRmatrix< T >::resize().
Member Data Documentation
forder
int shapehexahedron::forder protected
Definition at line 573 of file shapehexahedron.h.
Referenced by pointsandweigths(), shapehexahedron(), shapes(), and shapes1D().
ftype
int shapehexahedron::ftype protected
Definition at line 574 of file shapehexahedron.h.
Referenced by shapehexahedron().
The documentation for this class was generated from the following file:
src/shapehexahedron.h