DCPROJ: shapequad Class Reference
shapequad Class Reference
#include <shapequad.h>
Public Member Functions
shapequad (int order, int type)
shapequad ()
~shapequad ()
void shapes (MatDoub &psis, MatDoub &gradpsis, Doub xi, Doub eta)
void shapes (MatrixXd &psis, MatrixXd &gradpsis, double xi, double eta)
void shapes1D (MatDoub &psis, MatDoub &gradpsis, Doub xi)
void pointsandweigths (MatDoub &pts)
void pointsandweigths1D (MatDoub &pts)
NRmatrix< Doub > GetBaseNodes ()
Protected Attributes
int forder
int ftype
Detailed Description
Definition at line 3 of file shapequad.h.
Constructor & Destructor Documentation
shapequad() [1/2]
shapequad::shapequad (int order, int type) inline
Definition at line 6 of file shapequad.h.
References forder, and ftype.
shapequad() [2/2]
shapequad::shapequad () inline
Definition at line 12 of file shapequad.h.
~shapequad()
shapequad::~shapequad () inline
Definition at line 15 of file shapequad.h.
Member Function Documentation
GetBaseNodes()
NRmatrix<Doub> shapequad::GetBaseNodes () inline
Definition at line 293 of file shapequad.h.
References forder.
Referenced by elastoplastic2D< YC >::ComputeSolAndDSol(), and elastoplastic2D< YC >::PostProcessStrain().
pointsandweigths()
void shapequad::pointsandweigths (MatDoub & pts) inline
Definition at line 176 of file shapequad.h.
References forder, and NRmatrix< T >::resize().
Referenced by elastmat2D::CacStiff(), elastoplastic2D< YC >::CacStiff(), KLGalerkinRF::CacStiffB(), KLGalerkinRF::CacStiffC(), elastoplastic2D< YC >::ComputeSolAndDSol(), pressurizedhole::CreateMatAndMesh(), createrandomfield(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), mainwindows(), MonteCarlo(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), KLGalerkinRF::PerfomIntegralOfListconst(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), elastoplastic2D< YC >::PostProcessStrain(), solvedeterm(), and solvedetermtest().
pointsandweigths1D()
void shapequad::pointsandweigths1D (MatDoub & pts) inline
Definition at line 273 of file shapequad.h.
References NRmatrix< T >::nrows(), and NRmatrix< T >::resize().
Referenced by elastoplastic2D< YC >::ContributeCurvedLine(), elastmat2D::ContributeLineNewan(), and elastoplastic2D< YC >::ContributeLineNewan().
shapes() [1/2]
void shapequad::shapes (MatDoub & psis, MatDoub & gradpsis, Doub xi, Doub eta) inline
Definition at line 20 of file shapequad.h.
References NRmatrix< T >::assign(), forder, and NRmatrix< T >::resize().
Referenced by KLGalerkinRF::CacStiffC(), elastoplastic2D< YC >::ComputeSolAndDSol(), elastoplastic2D< YC >::ComputeSolution(), elastmat2D::Contribute(), elastoplastic2D< YC >::Contribute(), KLGalerkinRF::ContributeB(), elastoplastic2D< YC >::ContributeEig(), FindEl(), mesh::FindSolution(), FuncdSearch::operator()(), KLGalerkinRF::PerfomIntegralOfListconst(), postprocess::PostProcess(), elastmat2D::PostProcess(), elastoplastic2D< YC >::PostProcess(), elastoplastic2D< YC >::PostProcessIntegrationPointVar(), elastmat2D::SolPt(), and elastoplastic2D< YC >::SolPt().
shapes() [2/2]
void shapequad::shapes (MatrixXd & psis, MatrixXd & gradpsis, double xi, double eta) inline
Definition at line 79 of file shapequad.h.
References forder.
shapes1D()
void shapequad::shapes1D (MatDoub & psis, MatDoub & gradpsis, Doub xi) inline
Definition at line 139 of file shapequad.h.
References forder, and NRmatrix< T >::resize().
Referenced by elastoplastic2D< YC >::ContributeCurvedLine(), elastmat2D::ContributeLineNewan(), and elastoplastic2D< YC >::ContributeLineNewan().
Member Data Documentation
forder
int shapequad::forder protected
Definition at line 339 of file shapequad.h.
Referenced by GetBaseNodes(), pointsandweigths(), shapequad(), shapes(), and shapes1D().
ftype
int shapequad::ftype protected
Definition at line 340 of file shapequad.h.
Referenced by shapequad().
The documentation for this class was generated from the following file:
src/shapequad.h