DCPROJ: material Class Reference
material Class Reference abstract
#include <material.h>
Public Member Functions
material ()
~material ()
virtual void Contribute (MatDoub &ek, MatDoub &efint, MatDoub &efbody, NRvector< Doub > ptsw, MatDoub elcoords, MatDoub eldisplace)=0
virtual void CacStiff (MatDoub &ek, MatDoub &efint, MatDoub &efbody, const MatDoub &elcoords, MatDoub eldisplace)=0
virtual void Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub &KG, MatDoub &Fint, MatDoub &Fbody)=0
virtual void assembleBandN (MatDoub &B, MatDoub &N, const MatDoub &psis, const MatDoub &GradPhi)=0
virtual void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)=0
virtual void DirichletBC (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void DirichletBC (SparseMatrix< double > &KG, VectorXd &Fint, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeLineNewan (MatDoub &KG, MatDoub &FG, std::vector< int > ids, Int dir, Int val)=0
virtual void ContributeCurvedLine (MatDoub &KG, MatDoub &FG, MatDoub meshnodes, MatInt linetopology, Doub force)=0
virtual void SolPt (const std::vector< std::vector< std::vector< Doub > > > &allcoords, const MatInt &meshtopology, const Int &el, const MatDoub &solG, const Doub &xi, const Doub &eta, MatDoub &xycoords, MatDoub &sol)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &solx, std::vector< std::vector< double >> &soly)=0
virtual void PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, Int var, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void PostProcessStrain (mesh *inmesh, NRvector< NRvector< NRtensor< Doub >>> &sol)=0
virtual void PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub &nodalsol, std::vector< std::vector< double >> &sol)=0
virtual void SetRandomField (MatDoub hhat)=0
virtual void SetMemory (Int ngloblapoints, Int systemsize)=0
virtual void UpdateDisplacement (MatDoub displace)=0
virtual void UpdateDisplacement (VectorXd displace)=0
virtual void UpdatePlasticStrain ()=0
virtual void UpdateBodyForce (MatDoub newbodyforce)=0
virtual void ResetPlasticStrain ()=0
virtual void ResetDisplacement ()=0
virtual void ResetMat ()=0
virtual void ResetMemory ()=0
virtual NRmatrix< Doub > GetSolution ()=0
virtual NRvector< NRtensor< Doub > > GetPlasticStrain ()=0
virtual void SetMatConstants (NRvector< Doub > &consts)=0
virtual void GetMatConstants (NRvector< Doub > &consts)=0
virtual void ResetCounter ()=0
virtual void SetRandomFieldLocal (NRvector< MatDoub > hhatvel)=0
virtual MatDoub GetBodyForce ()=0
virtual void ComputeSolAndDSol (mesh *inmesh, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)=0
virtual void ComputeSolAndDSol (mesh *inmesh, NRvector< NRmatrix< Doub >> &sol, NRvector< NRmatrix< Doub >> &dsol)=0
virtual Doub ComputePhi (NRtensor< Doub > eps)=0
virtual void ComputeSolution (mesh *inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > &sol, NRmatrix< Doub > &dsol)=0
Detailed Description
Definition at line 9 of file material.h.
Constructor & Destructor Documentation
material()
material::material ()
Definition at line 5 of file material.cpp.
~material()
material::~material ()
Definition at line 9 of file material.cpp.
Member Function Documentation
Assemble()
virtual void material::Assemble (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, MatDoub & KG, MatDoub & Fint, MatDoub & Fbody) pure virtual
Referenced by IterativeCho(), IterativeProcess(), IterativeProcessShearRed(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
assembleBandN()
virtual void material::assembleBandN (MatDoub & B, MatDoub & N, const MatDoub & psis, const MatDoub & GradPhi) pure virtual
CacStiff()
virtual void material::CacStiff (MatDoub & ek, MatDoub & efint, MatDoub & efbody, const MatDoub & elcoords, MatDoub eldisplace) pure virtual
Referenced by mesh::Assemble().
ComputePhi()
virtual Doub material::ComputePhi (NRtensor< Doub > eps) pure virtual
Implemented in elastoplastic3D< YC >, and elastoplastic2D< YC >.
Referenced by VTKGraphMesh::DrawSolution().
ComputeSolAndDSol() [1/2]
virtual void material::ComputeSolAndDSol (mesh * inmesh, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by VTKGraphMesh::DrawSolution(), and pressurizedhole::IterativeProcess().
ComputeSolAndDSol() [2/2]
virtual void material::ComputeSolAndDSol (mesh * inmesh, NRvector< NRmatrix< Doub >> & sol, NRvector< NRmatrix< Doub >> & dsol) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
ComputeSolution()
virtual void material::ComputeSolution (mesh * inmesh, NRmatrix< Doub > elcoords, NRmatrix< Doub > eldisplace, NRvector< Doub > ptsw, NRmatrix< Doub > & sol, NRmatrix< Doub > & dsol) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Contribute()
virtual void material::Contribute (MatDoub & ek, MatDoub & efint, MatDoub & efbody, NRvector< Doub > ptsw, MatDoub elcoords, MatDoub eldisplace) pure virtual
ContributeCurvedLine()
virtual void material::ContributeCurvedLine (MatDoub & KG, MatDoub & FG, MatDoub meshnodes, MatInt linetopology, Doub force) pure virtual
Referenced by pressurizedhole::LoadBC().
ContributeLineNewan()
virtual void material::ContributeLineNewan (MatDoub & KG, MatDoub & FG, std::vector< int > ids, Int dir, Int val) pure virtual
DirichletBC() [1/2]
virtual void material::DirichletBC (MatDoub & KG, MatDoub & FG, std::vector< int > ids, Int dir, Int val) pure virtual
Referenced by slopeproject::InserBC(), InserBC(), pressurizedhole::InsertBC(), beam3dtools::InsertBC(), beam3dtools::InsertCubeBC(), IterativeCho(), and IterativeSlopeStabilityEig().
DirichletBC() [2/2]
virtual void material::DirichletBC (SparseMatrix< double > & KG, VectorXd & Fint, std::vector< int > ids, Int dir, Int val) pure virtual
Implemented in elastoplastic3D< YC >, and elastoplastic2D< YC >.
GetBodyForce()
virtual MatDoub material::GetBodyForce () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by slopeproject::MonteCarloGIM(), and slopeproject::MonteCarloSRM().
GetElCoords()
virtual void material::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
GetMatConstants()
virtual void material::GetMatConstants (NRvector< Doub > & consts) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), slopeproject::MonteCarloGIM(), and slopeproject::MonteCarloSRM().
GetPlasticStrain()
virtual NRvector<NRtensor<Doub> > material::GetPlasticStrain () pure virtual
Implemented in elastoplastic3D< YC >, and elastoplastic2D< YC >.
GetSolution()
virtual NRmatrix<Doub> material::GetSolution () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by mesh::Assemble(), mesh::ComputeSolAndDSol(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), slopeproject::MonteCarloSRM(), slopeproject::PrintMCS(), and VTKGraphMesh::VTKGraphMesh().
PostProcess() [1/2]
virtual void material::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub & nodalsol, std::vector< std::vector< double >> & solx, std::vector< std::vector< double >> & soly) pure virtual
Referenced by IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), mainlinux(), mainlinuxserial(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), slopeproject::PrintMCS(), and solvedetermtest().
PostProcess() [2/2]
virtual void material::PostProcess (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, Int var, const MatDoub & nodalsol, std::vector< std::vector< double >> & sol) pure virtual
PostProcessIntegrationPointVar()
virtual void material::PostProcessIntegrationPointVar (std::vector< std::vector< std::vector< Doub > > > allcoords, MatDoub meshnodes, MatInt meshtopology, const MatDoub & nodalsol, std::vector< std::vector< double >> & sol) pure virtual
Referenced by IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), slopeproject::PrintMCS(), and solvedetermtest().
PostProcessStrain()
virtual void material::PostProcessStrain (mesh * inmesh, NRvector< NRvector< NRtensor< Doub >>> & sol) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
ResetCounter()
virtual void material::ResetCounter () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by mesh::Assemble().
ResetDisplacement()
virtual void material::ResetDisplacement () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
ResetMat()
virtual void material::ResetMat () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), IterativeSlopeStabilityEig(), and slopeproject::MonteCarloSRM().
ResetMemory()
virtual void material::ResetMemory () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
ResetPlasticStrain()
virtual void material::ResetPlasticStrain () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by IterativeCho(), slopeproject::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
SetMatConstants()
virtual void material::SetMatConstants (NRvector< Doub > & consts) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), slopeproject::MonteCarloGIM(), and slopeproject::MonteCarloSRM().
SetMemory()
virtual void material::SetMemory (Int ngloblapoints, Int systemsize) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), solvedeterm(), and solvedetermtest().
SetRandomField()
virtual void material::SetRandomField (MatDoub hhat) pure virtual
Referenced by mesh::Assemble(), slopeproject::MonteCarloGIM(), and MonteCarloTalude2().
SetRandomFieldLocal()
virtual void material::SetRandomFieldLocal (NRvector< MatDoub > hhatvel) pure virtual
Referenced by mesh::Assemble().
SolPt()
virtual void material::SolPt (const std::vector< std::vector< std::vector< Doub > > > & allcoords, const MatInt & meshtopology, const Int & el, const MatDoub & solG, const Doub & xi, const Doub & eta, MatDoub & xycoords, MatDoub & sol) pure virtual
UpdateBodyForce()
virtual void material::UpdateBodyForce (MatDoub newbodyforce) pure virtual
Referenced by IterativeProcessShearRed2(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), MonteCarloTalude2(), solvedeterm(), and solvedetermtest().
UpdateDisplacement() [1/2]
virtual void material::UpdateDisplacement (MatDoub displace) pure virtual
Referenced by IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), slopeproject::IterativeProcessShearRed(), IterativeProcessShearRed(), slopeproject::IterativeProcessShearRed2(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
UpdateDisplacement() [2/2]
virtual void material::UpdateDisplacement (VectorXd displace) pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
UpdatePlasticStrain()
virtual void material::UpdatePlasticStrain () pure virtual
Implemented in elastoplastic2D< YC >, and elastoplastic3D< YC >.
Referenced by IterativeCho(), pressurizedhole::IterativeProcess(), slopeproject::IterativeProcess(), beam3dtools::IterativeProcess(), IterativeProcess(), slopeproject::IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), IterativeProcessShearRed2(), IterativeProcessShearRed3(), and IterativeSlopeStabilityEig().
The documentation for this class was generated from the following files:
src/material.h
src/material.cpp