DCPROJ: druckerprager Class Reference
druckerprager Class Reference
#include <druckerprager.h>
Public Member Functions
druckerprager ()
Default constructor.
druckerprager (Doub young, Doub nu, Doub coesion, Doub frictionangle)
Class constructor.
~druckerprager ()
Default destructor.
void closestpointproj (NRtensor< Doub > epst, NRtensor< Doub > epsp, NRtensor< Doub > &projstress, NRtensor< Doub > &projstrain, NRmatrix< Doub > &Dep, Doub &projgamma)
Implements the elastoplastic decomposition whit the Closest Point Projection Method and computes the tangent operator.
Doub yield (Doub xi, Doub rho)
Compute the yield function.
NRmatrix< Doub > GetElasticMatrix ()
NRmatrix< Doub > GetInverseElasticMatrix ()
NRmatrix< Doub > F1HWCylDruckerPragerSmoothPSMATCH (Doub xisol, Doub rho, Doub betasol)
Compute the cylindrical coordinates in DP plane strain match.
NRmatrix< Doub > HW (NRmatrix< Doub > sig)
Compute the cylindrical coordinates.
NRmatrix< Doub > stressrecosntruction (NRmatrix< Doub > val, NRmatrix< Doub > vec)
Reconstruct a second order stress tensor.
NRmatrix< Doub > dadsig (NRtensor< Doub > sigprojvoigt)
Equation 58 of the Reference. Compute the flow rule derivative with respect to the projected stress.
NRmatrix< Doub > P ()
\(\boldsymbol{P}= \left[\begin{array}{cccccc} 2/3 & -1/3 & -1/3 & 0 & 0 & 0\\ -1/3 & 2/3 & -1/3 & 0 & 0 & 0\\ -1/3 & -1/3 & 2/3 & 0 & 0 & 0\\ 0 & 0 & 0 & 2 & 0 & 0\\ 0 & 0 & 0 & 0 & 2 & 0\\ 0 & 0 & 0 & 0 & 0 & 2\\ \end{array}\right] \)
NRmatrix< Doub > avec (NRtensor< Doub > sigprojvoigt)
Equation 57 of the Reference. Compute the flow rule.
Doub FindMinimum (NRmatrix< Doub > pt, Doub xitrial, bool flag)
Find the project xi cylindrical coordinate using a combination of Newton-Raphson and bisection.
MatDoub ComputeQ (NRmatrix< Doub > fulltensorproj, NRmatrix< Doub > tempepsemat, NRtensor< Doub > &projstress, NRtensor< Doub > &projstrain, Doub &projgamma, NRmatrix< Doub > &nvec)
Compute \(\boldsymbol{Q} = \boldsymbol{I} + \Delta \gamma \mathbf{D}^e \frac{\boldsymbol{\partial{a}}}{\boldsymbol{\partial{\sigma}}} \).
Doub phi (NRtensor< Doub > epse)
void setup (Doub young, Doub nu, Doub coesion, Doub frictionangle)
Doub GetCoes ()
Doub GetPhi ()
Doub GetYoung ()
Doub GetNu ()
void reset ()
void updateatributes (NRvector< MatDoub > mult)
void restoreoriginalatributes ()
void GetMatConstants (NRvector< Doub > &consts)
void SetMatConstants (NRvector< Doub > &consts)
Doub Det (NRmatrix< Doub > A)
NRmatrix< Doub > Inverse (NRmatrix< Doub > A)
Public Attributes
Doub fyoung
Doub fnu
Private Attributes
Doub fcoesion
Doub fphi
Doub fcoesion0
Doub fphi0
Doub fK
Doub fG
Doub ftanphi
Doub fapex
Doub fa
Doub fb
bool fflag
Doub fyoung0
Doub fnu0
Detailed Description
Definition at line 20 of file druckerprager.h.
Constructor & Destructor Documentation
druckerprager() [1/2]
druckerprager::druckerprager ()
Default constructor.
Definition at line 10 of file druckerprager.cpp.
druckerprager() [2/2]
druckerprager::druckerprager (Doub young, Doub nu, Doub coesion, Doub frictionangle)
Class constructor.
Parameters
[in] young material youngs modulus
[in] nu material poisson ratio
[in] coesion material cohesion
[in] frictionangle material internal friction angle
Definition at line 14 of file druckerprager.cpp.
References setup().
~druckerprager()
druckerprager::~druckerprager ()
Default destructor.
Definition at line 20 of file druckerprager.cpp.
Member Function Documentation
avec()
NRmatrix< Doub > druckerprager::avec (NRtensor< Doub > sigprojvoigt)
Equation 57 of the Reference. Compute the flow rule.
Parameters
[in] sigprojvoigt projected stress tensor in Voigt notation
[out] avec yield function derivative with respect to the projected stress
Definition at line 288 of file druckerprager.cpp.
References NRtensor< T >::ComputeS(), fa, fapex, fb, NRtensor< T >::FromTensorToNRmatrix(), and NRtensor< T >::I1().
Referenced by ComputeQ().
closestpointproj()
void druckerprager::closestpointproj (NRtensor< Doub > epst, NRtensor< Doub > epsp, NRtensor< Doub > & projstress, NRtensor< Doub > & projstrain, NRmatrix< Doub > & Dep, Doub & projgamma)
Implements the elastoplastic decomposition whit the Closest Point Projection Method and computes the tangent operator.
Parameters
[in] epst total strain tensor
[in] epsp plastic strain tensor
[out] projstress projected stress tensor
[out] projstrain projected strain tensor
[out] Dep Elastoplastic tangent operator
[out] projgamma Plastic multiplier
Definition at line 25 of file druckerprager.cpp.
References NRmatrix< T >::ComputeInverse(), ComputeQ(), NRmatrix< T >::DetEig(), NRtensor< T >::EigenSystem(), F1HWCylDruckerPragerSmoothPSMATCH(), fflag, FindMinimum(), NRtensor< T >::FromNRmatrixToTensor(), NRtensor< T >::FromTensorToNRmatrix(), GetElasticMatrix(), HW(), NRtensor< T >::I1(), NRtensor< T >::isfailed(), NRtensor< T >::J2(), NRmatrix< T >::Mult(), NRmatrix< T >::nrows(), stressrecosntruction(), NRmatrix< T >::Transpose(), and yield().
ComputeQ()
NRmatrix< Doub > druckerprager::ComputeQ (NRmatrix< Doub > fulltensorproj, NRmatrix< Doub > tempepsemat, NRtensor< Doub > & projstress, NRtensor< Doub > & projstrain, Doub & projgamma, NRmatrix< Doub > & nvec)
Compute \(\boldsymbol{Q} = \boldsymbol{I} + \Delta \gamma \mathbf{D}^e \frac{\boldsymbol{\partial{a}}}{\boldsymbol{\partial{\sigma}}} \).
Parameters
[in] pt trial principal stress
[in] xitrial trial xi cylindrical coordinate
Definition at line 162 of file druckerprager.cpp.
References avec(), dadsig(), NRmatrix< T >::FromFullToVoigt(), NRtensor< T >::FromNRmatrixToTensor(), GetElasticMatrix(), GetInverseElasticMatrix(), NRmatrix< T >::Mult(), NRtensor< T >::Norm(), and NRmatrix< T >::NRmatrixNorm().
Referenced by closestpointproj().
dadsig()
NRmatrix< Doub > druckerprager::dadsig (NRtensor< Doub > sigprojvoigt)
Equation 58 of the Reference. Compute the flow rule derivative with respect to the projected stress.
Parameters
[in] sigprojvoigt projected stress tensor in Voigt notation
[out] dadsig derivative with respect to the projected stress
Definition at line 274 of file druckerprager.cpp.
References fa, fb, and P().
Referenced by ComputeQ().
Det()
Doub druckerprager::Det (NRmatrix< Doub > A) inline
Definition at line 236 of file druckerprager.h.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
F1HWCylDruckerPragerSmoothPSMATCH()
NRmatrix< Doub > druckerprager::F1HWCylDruckerPragerSmoothPSMATCH (Doub xisol, Doub rho, Doub betasol)
Compute the cylindrical coordinates in DP plane strain match.
Parameters
[in] xi cylindrical coordinate xi=I1/3
[in] rho cylindrical coordinate rho = sqrt(2 J2)
[in] beta angle
[out] NRmatrix<Doub> {sig1,sig2,sig3}
Definition at line 234 of file druckerprager.cpp.
References fa, fapex, and fb.
Referenced by closestpointproj().
FindMinimum()
Doub druckerprager::FindMinimum (NRmatrix< Doub > pt, Doub xitrial, bool flag)
Find the project xi cylindrical coordinate using a combination of Newton-Raphson and bisection.
Parameters
[in] pt trial principal stress
[in] xitrial trial xi cylindrical coordinate
Definition at line 152 of file druckerprager.cpp.
References fcoesion, flag, fnu, fphi, fyoung, rtsafe(), and Funcd::setpt().
Referenced by closestpointproj().
GetCoes()
Doub druckerprager::GetCoes () inline
Definition at line 176 of file druckerprager.h.
GetElasticMatrix()
NRmatrix< Doub > druckerprager::GetElasticMatrix ()
Definition at line 210 of file druckerprager.cpp.
References fG, and fK.
Referenced by closestpointproj(), and ComputeQ().
GetInverseElasticMatrix()
NRmatrix< Doub > druckerprager::GetInverseElasticMatrix ()
Definition at line 222 of file druckerprager.cpp.
References fG, and fK.
Referenced by ComputeQ().
GetMatConstants()
void druckerprager::GetMatConstants (NRvector< Doub > & consts) inline
Definition at line 221 of file druckerprager.h.
References NRvector< T >::assign().
GetNu()
Doub druckerprager::GetNu () inline
Definition at line 191 of file druckerprager.h.
GetPhi()
Doub druckerprager::GetPhi () inline
Definition at line 181 of file druckerprager.h.
GetYoung()
Doub druckerprager::GetYoung () inline
Definition at line 186 of file druckerprager.h.
HW()
NRmatrix< Doub > druckerprager::HW (NRmatrix< Doub > sig)
Compute the cylindrical coordinates.
Parameters
[in] sig principla stress
[out] NRmatrix<Doub> {xi,rho,beta} cylindrical coordinates
Definition at line 243 of file druckerprager.cpp.
Referenced by closestpointproj().
Inverse()
NRmatrix<Doub> druckerprager::Inverse (NRmatrix< Doub > A) inline
Definition at line 251 of file druckerprager.h.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
P()
NRmatrix< Doub > druckerprager::P ()
\(\boldsymbol{P}= \left[\begin{array}{cccccc} 2/3 & -1/3 & -1/3 & 0 & 0 & 0\\ -1/3 & 2/3 & -1/3 & 0 & 0 & 0\\ -1/3 & -1/3 & 2/3 & 0 & 0 & 0\\ 0 & 0 & 0 & 2 & 0 & 0\\ 0 & 0 & 0 & 0 & 2 & 0\\ 0 & 0 & 0 & 0 & 0 & 2\\ \end{array}\right] \)
Definition at line 308 of file druckerprager.cpp.
Referenced by dadsig().
phi()
Doub druckerprager::phi (NRtensor< Doub > epse) inline
Definition at line 133 of file druckerprager.h.
References NRtensor< T >::FromNRmatrixToTensor(), NRtensor< T >::FromTensorToNRmatrix(), NRtensor< T >::I1(), NRtensor< T >::J2(), and NRmatrix< T >::Mult().
reset()
void druckerprager::reset () inline
Definition at line 196 of file druckerprager.h.
restoreoriginalatributes()
void druckerprager::restoreoriginalatributes () inline
Definition at line 215 of file druckerprager.h.
SetMatConstants()
void druckerprager::SetMatConstants (NRvector< Doub > & consts) inline
Definition at line 230 of file druckerprager.h.
setup()
void druckerprager::setup (Doub young, Doub nu, Doub coesion, Doub frictionangle) inline
Definition at line 162 of file druckerprager.h.
Referenced by createrandomfield(), druckerprager(), main2(), mainlinux(), mainlinux2(), mainlinuxserial(), mainwindows(), and updateatributes().
stressrecosntruction()
NRmatrix< Doub > druckerprager::stressrecosntruction (NRmatrix< Doub > val, NRmatrix< Doub > vec)
Reconstruct a second order stress tensor.
Parameters
[in] val eigenvalues
[in] vec eigenvectors
[out] fulltensor
Definition at line 255 of file druckerprager.cpp.
References NRmatrix< T >::Transpose().
Referenced by closestpointproj().
updateatributes()
void druckerprager::updateatributes (NRvector< MatDoub > mult)
Definition at line 321 of file druckerprager.cpp.
References fcoesion, fcoesion0, fnu, fnu0, fphi, fphi0, fyoung, fyoung0, and setup().
yield()
Doub druckerprager::yield (Doub xi, Doub rho)
Compute the yield function.
Parameters
[in] xi cylindrical coordinate xi=I1/3
[in] rho cylindrical coordinate rho = sqrt(2 J2)
[out] yieldfunction
Definition at line 200 of file druckerprager.cpp.
References fa, fapex, and fb.
Referenced by closestpointproj().
Member Data Documentation
fa
Doub druckerprager::fa private
Definition at line 287 of file druckerprager.h.
Referenced by avec(), dadsig(), F1HWCylDruckerPragerSmoothPSMATCH(), and yield().
fapex
Doub druckerprager::fapex private
Definition at line 286 of file druckerprager.h.
Referenced by avec(), F1HWCylDruckerPragerSmoothPSMATCH(), and yield().
fb
Doub druckerprager::fb private
Definition at line 287 of file druckerprager.h.
Referenced by avec(), dadsig(), F1HWCylDruckerPragerSmoothPSMATCH(), and yield().
fcoesion
Doub druckerprager::fcoesion private
Definition at line 278 of file druckerprager.h.
Referenced by FindMinimum(), and updateatributes().
fcoesion0
Doub druckerprager::fcoesion0 private
Definition at line 280 of file druckerprager.h.
Referenced by updateatributes().
fflag
bool druckerprager::fflag private
Definition at line 288 of file druckerprager.h.
Referenced by closestpointproj().
fG
Doub druckerprager::fG private
Definition at line 284 of file druckerprager.h.
Referenced by GetElasticMatrix(), and GetInverseElasticMatrix().
fK
Doub druckerprager::fK private
Definition at line 283 of file druckerprager.h.
Referenced by GetElasticMatrix(), and GetInverseElasticMatrix().
fnu
Doub druckerprager::fnu
Definition at line 275 of file druckerprager.h.
Referenced by FindMinimum(), and updateatributes().
fnu0
Doub druckerprager::fnu0 private
Definition at line 291 of file druckerprager.h.
Referenced by updateatributes().
fphi
Doub druckerprager::fphi private
Definition at line 279 of file druckerprager.h.
Referenced by FindMinimum(), and updateatributes().
fphi0
Doub druckerprager::fphi0 private
Definition at line 281 of file druckerprager.h.
Referenced by updateatributes().
ftanphi
Doub druckerprager::ftanphi private
Definition at line 285 of file druckerprager.h.
fyoung
Doub druckerprager::fyoung
Definition at line 274 of file druckerprager.h.
Referenced by FindMinimum(), and updateatributes().
fyoung0
Doub druckerprager::fyoung0 private
Definition at line 289 of file druckerprager.h.
Referenced by updateatributes().
The documentation for this class was generated from the following files:
src/druckerprager.h
src/druckerprager.cpp