DCPROJ: NRtensor< T > Class Template Reference
NRtensor< T > Class Template Reference
#include <nr3.h>
Public Types
typedef T value_type
Public Member Functions
NRtensor ()
NRtensor (const T &a)
NRtensor (const T *a)
NRtensor (const NRtensor &rhs)
NRtensor & operator= (const NRtensor &rhs)
NRtensor & operator+ (const NRtensor &rhs)
NRtensor & operator- (const NRtensor &rhs)
NRtensor & operator*= (const T &multipl)
NRtensor & operator+= (const NRtensor &rhs)
T & operator[] (const int i)
const T & operator[] (const int i) const
void assign (int newn, const T &a)
void Print ()
~NRtensor ()
bool isfailed ()
T & XX () const
T & XY () const
T & XZ () const
T & YY () const
T & YZ () const
T & ZZ () const
void Multiply (const NRtensor< T > tensor, NRtensor< T > &resp) const
void DeviatoricDiagonal (NRvector< T > &vec) const
T J2 () const
T I1 () const
void FromTensorToNRmatrix (NRmatrix< T > &resp)
void FromTensorVoigtToFullTensor (NRmatrix< T > &full)
void FromNRmatrixToTensor (NRmatrix< T > &input, NRtensor< T > &resp)
void EigenSystem (NRmatrix< T > &eigenvalues, NRmatrix< T > &eigenvectors)
void ComputeS (NRtensor< T > &out)
T Norm ()
void CopyFromNRmatrix (NRmatrix< T > source)
Private Attributes
bool fail
int nn
T * v
Detailed Description
template<class T>
class NRtensor< T >
Definition at line 932 of file nr3.h.
Member Typedef Documentation
value_type
template<class T > typedef T NRtensor< T >::value_type
Definition at line 949 of file nr3.h.
Constructor & Destructor Documentation
NRtensor() [1/4]
template<class T > NRtensor< T >::NRtensor
Definition at line 1037 of file nr3.h.
NRtensor() [2/4]
template<class T > NRtensor< T >::NRtensor (const T & a)
Definition at line 1046 of file nr3.h.
NRtensor() [3/4]
template<class T > NRtensor< T >::NRtensor (const T * a)
Definition at line 1052 of file nr3.h.
NRtensor() [4/4]
template<class T > NRtensor< T >::NRtensor (const NRtensor< T > & rhs)
~NRtensor()
template<class T > NRtensor< T >::~NRtensor
Definition at line 1169 of file nr3.h.
Member Function Documentation
assign()
template<class T > void NRtensor< T >::assign (int newn, const T & a)
Definition at line 1158 of file nr3.h.
ComputeS()
template<class T > void NRtensor< T >::ComputeS (NRtensor< T > & out)
Definition at line 1277 of file nr3.h.
Referenced by druckerprager::avec(), vonmises::closestpointproj(), and vonmises::dadsig().
CopyFromNRmatrix()
template<class T > void NRtensor< T >::CopyFromNRmatrix (NRmatrix< T > source)
Definition at line 1023 of file nr3.h.
DeviatoricDiagonal()
template<class T > void NRtensor< T >::DeviatoricDiagonal (NRvector< T > & vec) const
Definition at line 1189 of file nr3.h.
EigenSystem()
template<class T > void NRtensor< T >::EigenSystem (NRmatrix< T > & eigenvalues, NRmatrix< T > & eigenvectors)
Definition at line 1582 of file nr3.h.
Referenced by vonmises::closestpointproj(), and druckerprager::closestpointproj().
FromNRmatrixToTensor()
template<class T > void NRtensor< T >::FromNRmatrixToTensor (NRmatrix< T > & input, NRtensor< T > & resp)
Definition at line 1248 of file nr3.h.
Referenced by vonmises::closestpointproj(), druckerprager::closestpointproj(), druckerprager::ComputeQ(), vonmises::phi(), and druckerprager::phi().
FromTensorToNRmatrix()
template<class T > void NRtensor< T >::FromTensorToNRmatrix (NRmatrix< T > & resp)
Definition at line 1234 of file nr3.h.
Referenced by druckerprager::avec(), vonmises::closestpointproj(), druckerprager::closestpointproj(), vonmises::dadsig(), vonmises::phi(), and druckerprager::phi().
FromTensorVoigtToFullTensor()
template<class T > void NRtensor< T >::FromTensorVoigtToFullTensor (NRmatrix< T > & full)
Definition at line 1259 of file nr3.h.
I1()
template<class T > T NRtensor< T >::I1
Definition at line 1213 of file nr3.h.
Referenced by druckerprager::avec(), vonmises::closestpointproj(), druckerprager::closestpointproj(), vonmises::dadsig(), vonmises::phi(), and druckerprager::phi().
isfailed()
template<class T > bool NRtensor< T >::isfailed () inline
Definition at line 955 of file nr3.h.
Referenced by druckerprager::closestpointproj().
J2()
template<class T > T NRtensor< T >::J2
Definition at line 1197 of file nr3.h.
Referenced by vonmises::closestpointproj(), druckerprager::closestpointproj(), vonmises::dadsig(), vonmises::phi(), and druckerprager::phi().
Multiply()
template<class T > void NRtensor< T >::Multiply (const NRtensor< T > tensor, NRtensor< T > & resp) const
Definition at line 1218 of file nr3.h.
Norm()
template<class T > T NRtensor< T >::Norm () inline
Definition at line 1004 of file nr3.h.
Referenced by vonmises::closestpointproj(), and druckerprager::ComputeQ().
operator*=()
template<class T > NRtensor< T > & NRtensor< T >::operator*= (const T & multipl)
Definition at line 1118 of file nr3.h.
operator+()
template<class T > NRtensor< T > & NRtensor< T >::operator+ (const NRtensor< T > & rhs)
Definition at line 1079 of file nr3.h.
operator+=()
template<class T > NRtensor< T > & NRtensor< T >::operator+= (const NRtensor< T > & rhs)
Definition at line 1126 of file nr3.h.
operator-()
template<class T > NRtensor< T > & NRtensor< T >::operator- (const NRtensor< T > & rhs)
Definition at line 1098 of file nr3.h.
operator=()
template<class T > NRtensor< T > & NRtensor< T >::operator= (const NRtensor< T > & rhs)
Definition at line 1065 of file nr3.h.
operator[]() [1/2]
template<class T > T & NRtensor< T >::operator[] (const int i) inline
Definition at line 1133 of file nr3.h.
operator[]() [2/2]
template<class T > const T & NRtensor< T >::operator[] (const int i) const inline
Definition at line 1145 of file nr3.h.
Print()
template<class T > void NRtensor< T >::Print
Definition at line 1176 of file nr3.h.
XX()
template<class T > T& NRtensor< T >::XX () const inline
Definition at line 959 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), VTKGraphMesh::DrawSolution(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
XY()
template<class T > T& NRtensor< T >::XY () const inline
Definition at line 963 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), VTKGraphMesh::DrawSolution(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
XZ()
template<class T > T& NRtensor< T >::XZ () const inline
Definition at line 967 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
YY()
template<class T > T& NRtensor< T >::YY () const inline
Definition at line 971 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), VTKGraphMesh::DrawSolution(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
YZ()
template<class T > T& NRtensor< T >::YZ () const inline
Definition at line 975 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
ZZ()
template<class T > T& NRtensor< T >::ZZ () const inline
Definition at line 979 of file nr3.h.
Referenced by NRtensor< Doub >::ComputeS(), NRtensor< Doub >::FromNRmatrixToTensor(), and NRtensor< Doub >::Multiply().
Member Data Documentation
fail
template<class T > bool NRtensor< T >::fail private
Definition at line 933 of file nr3.h.
Referenced by NRtensor< Doub >::isfailed().
nn
template<class T > int NRtensor< T >::nn private
Definition at line 936 of file nr3.h.
Referenced by NRtensor< Doub >::NRtensor(), NRtensor< Doub >::operator+(), and NRtensor< Doub >::operator-().
v
template<class T > T* NRtensor< T >::v private
Definition at line 937 of file nr3.h.
Referenced by NRtensor< Doub >::Multiply(), NRtensor< Doub >::Norm(), NRtensor< Doub >::NRtensor(), NRtensor< Doub >::XX(), NRtensor< Doub >::XY(), NRtensor< Doub >::XZ(), NRtensor< Doub >::YY(), NRtensor< Doub >::YZ(), and NRtensor< Doub >::ZZ().
The documentation for this class was generated from the following file:
src/nr3.h