DCPROJ: slopeproject Class Reference
slopeproject Class Reference
#include <slopeproject.h>
Public Member Functions
slopeproject (mesh *inmesh, KLGalerkinRF *inklgalerking)
slopeproject (mesh *inmesh, KLGalerkinRF *inklgalerking, NRmatrix< MatDoub > randomfield)
slopeproject (mesh inmesh, KLGalerkinRF inklgalerking, NRmatrix< MatDoub > randomfield)
slopeproject ()
~slopeproject ()
slopeproject (slopeproject &copy)
void CreateRandomField (string namefolder)
void PrintMCS (string namefolder, int imc, bool print)
void OutPutPost (MatDoub &postdata, std::ofstream &file)
void OutPutPost (MatInt &postdata, std::ofstream &file)
void OutPutPost (std::vector< std::vector< double >> &postdata, std::ofstream &file)
void OutPutFile (MatDoub &postdata, std::ofstream &file)
void OutPutFile1var (MatDoub &postdata, std::ofstream &file)
void OutPutFile4var (MatDoub &postdata, std::ofstream &file)
void PrintMathematicaFormat (MatDoub postdata, std::ofstream &file)
Doub computelamda (MatDoub &dwb, MatDoub &dws, MatDoub &dw, Doub &l)
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology, string filenameel, string filenamecoord)
std::vector< Doub > vecstr_to_vecdoub2 (std::vector< string > vs)
template<class T >
std::vector< T > vecstr_to_vec (std::vector< string > vs)
void ReadMatDoub (MatDoub &matdoub, std::string file)
std::vector< Doub > vecstr_to_vecdoub (std::vector< string > vs)
std::vector< Int > vecstr_to_vecint (std::vector< string > vs)
std::vector< std::vector< double > > IterativeProcess (int ndesi, Doub dlamb0, Doub alphatol, int niter)
std::vector< std::vector< double > > IterativeProcessArcLengthSRM (int ndesi, Doub dlamb0, Doub alphatol, int niter)
void SolveEigenSparse (MatDoub A, MatDoub b, MatDoub &x)
void SolveEigen (SparseMatrix< double > A, VectorXd b, VectorXd &x)
void SolveEigen (MatDoub A, MatDoub b, MatDoub &x)
void SolveEigen2 (MatDoub A, MatDoub b, MatDoub &x)
void SolveEigen3 (MatDoub A, MatDoub b, MatDoub &x)
void InserBC (MatDoub &KG, MatDoub &R, MatDoub &FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material *mat)
void InserBC (SparseMatrix< double > &KG, VectorXd &R, VectorXd &FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material *mat)
void GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub &elcoords)
void FindIdsInPath (const MatDoub &path, std::vector< std::vector< std::vector< Doub > > > &allcoords, MatInt &meshtopology, std::vector< int > &idpath)
void Line (VecDoub a, VecDoub b, Int ndivs, MatDoub &path)
void findbcids (mesh *gmesh, std::vector< std::vector< int >> &idsvector)
MatDoub AssembleHhationho (Int i)
std::vector< std::vector< double > > IterativeProcessShearRed (Doub fac, Doub delta, Doub tol)
std::vector< std::vector< double > > IterativeProcessShearRed2 (Doub fac, Doub delta, Doub tol)
void MonteCarloSRM (int iter, int iter2, bool print, string writenamefolder)
void MonteCarloGIM (int iter, int iter2, bool print, string writenamefolder)
Public Attributes
mesh * fmesh
KLGalerkinRF * fklgalerking
NRmatrix< MatDoub > frandomfield
Detailed Description
Definition at line 24 of file slopeproject.h.
Constructor & Destructor Documentation
slopeproject() [1/5]
slopeproject::slopeproject (mesh * inmesh, KLGalerkinRF * inklgalerking)
Definition at line 16 of file slopeproject.cpp.
References fklgalerking, and fmesh.
slopeproject() [2/5]
slopeproject::slopeproject (mesh * inmesh, KLGalerkinRF * inklgalerking, NRmatrix< MatDoub > randomfield)
Definition at line 21 of file slopeproject.cpp.
References fklgalerking, fmesh, and frandomfield.
slopeproject() [3/5]
slopeproject::slopeproject (mesh inmesh, KLGalerkinRF inklgalerking, NRmatrix< MatDoub > randomfield)
Definition at line 27 of file slopeproject.cpp.
References fklgalerking, fmesh, and frandomfield.
slopeproject() [4/5]
slopeproject::slopeproject ()
Definition at line 11 of file slopeproject.cpp.
~slopeproject()
slopeproject::~slopeproject ()
Definition at line 33 of file slopeproject.cpp.
References fklgalerking, and fmesh.
slopeproject() [5/5]
slopeproject::slopeproject (slopeproject & copy)
Definition at line 39 of file slopeproject.cpp.
Member Function Documentation
AssembleHhationho()
MatDoub slopeproject::AssembleHhationho (Int i)
Definition at line 1620 of file slopeproject.cpp.
References frandomfield, and NRmatrix< T >::nrows().
Referenced by mainlinux(), mainlinuxserial(), MonteCarloGIM(), MonteCarloSRM(), and PrintMCS().
computelamda()
Doub slopeproject::computelamda (MatDoub & dwb, MatDoub & dws, MatDoub & dw, Doub & l)
Definition at line 1201 of file slopeproject.cpp.
References NRmatrix< T >::nrows().
Referenced by IterativeProcess(), and IterativeProcessArcLengthSRM().
CreateRandomField()
void slopeproject::CreateRandomField (string namefolder)
Definition at line 44 of file slopeproject.cpp.
References fklgalerking, fmesh, KLGalerkinRF::GetExpansionorder(), KLGalerkinRF::Getftype(), KLGalerkinRF::GetLx(), KLGalerkinRF::GetLy(), KLGalerkinRF::GetSamples(), KLGalerkinRF::GetSig(), OutPutPost(), and KLGalerkinRF::SolveGenEigValProblem().
Referenced by createrandomfield(), mainlinux(), and mainlinuxserial().
findbcids()
void slopeproject::findbcids (mesh * gmesh, std::vector< std::vector< int >> & idsvector)
Definition at line 132 of file slopeproject.cpp.
References FindIdsInPath(), mesh::GetAllCoords(), mesh::GetMeshTopology(), and Line().
Referenced by IterativeProcess(), IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), and IterativeProcessShearRed2().
FindIdsInPath()
void slopeproject::FindIdsInPath (const MatDoub & path, std::vector< std::vector< std::vector< Doub > > > & allcoords, MatInt & meshtopology, std::vector< int > & idpath)
Definition at line 1564 of file slopeproject.cpp.
References GetElCoords(), and NRmatrix< T >::nrows().
Referenced by findbcids().
GetElCoords()
void slopeproject::GetElCoords (std::vector< std::vector< std::vector< Doub > > > allcoords, Int el, MatDoub & elcoords)
Definition at line 1550 of file slopeproject.cpp.
References NRmatrix< T >::assign().
Referenced by FindIdsInPath().
InserBC() [1/2]
void slopeproject::InserBC (MatDoub & KG, MatDoub & R, MatDoub & FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material * mat)
Definition at line 1261 of file slopeproject.cpp.
References material::DirichletBC().
Referenced by IterativeProcess(), IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), and IterativeProcessShearRed2().
InserBC() [2/2]
void slopeproject::InserBC (SparseMatrix< double > & KG, VectorXd & R, VectorXd & FBODY, std::vector< int > idsbottom, std::vector< int > idsright, std::vector< int > idsleft, material * mat)
Definition at line 1223 of file slopeproject.cpp.
References material::DirichletBC().
IterativeProcess()
std::vector< std::vector< double > > slopeproject::IterativeProcess (int ndesi, Doub dlamb0, Doub alphatol, int niter)
Definition at line 699 of file slopeproject.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), computelamda(), NRmatrix< T >::CopyFromVector(), DebugStop, VTKGraphMesh::DrawSolution(), findbcids(), mesh::fmaterial, fmesh, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), PrintMathematicaFormat(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), SolveEigen(), SolveEigen2(), SolveEigenSparse(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
Referenced by mainlinux(), mainlinuxserial(), and MonteCarloGIM().
IterativeProcessArcLengthSRM()
std::vector< std::vector< double > > slopeproject::IterativeProcessArcLengthSRM (int ndesi, Doub dlamb0, Doub alphatol, int niter)
Definition at line 998 of file slopeproject.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), computelamda(), NRmatrix< T >::CopyFromVector(), findbcids(), mesh::fmaterial, fmesh, mesh::GetAllCoords(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::Mult(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetDisplacement(), material::ResetMat(), material::ResetPlasticStrain(), material::SetMatConstants(), SolveEigen(), NRmatrix< T >::Transpose(), material::UpdateDisplacement(), and material::UpdatePlasticStrain().
IterativeProcessShearRed()
std::vector< std::vector< double > > slopeproject::IterativeProcessShearRed (Doub fac, Doub delta, Doub tol)
Definition at line 172 of file slopeproject.cpp.
References mesh::Assemble(), NRmatrix< T >::assign(), NRmatrix< T >::CopyFromVector(), findbcids(), mesh::fmaterial, fmesh, mesh::GetAllCoords(), mesh::GetHhat(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::NRmatrixNorm(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetMat(), mesh::SetHhat(), material::SetMatConstants(), SolveEigenSparse(), and material::UpdateDisplacement().
Referenced by mainwindows(), and MonteCarloSRM().
IterativeProcessShearRed2()
std::vector< std::vector< double > > slopeproject::IterativeProcessShearRed2 (Doub fac, Doub delta, Doub tol)
Definition at line 413 of file slopeproject.cpp.
References mesh::Assemble(), NRmatrix< T >::CopyFromVector(), findbcids(), mesh::fmaterial, fmesh, mesh::GetAllCoords(), mesh::GetHhat(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), InserBC(), NRmatrix< T >::nrows(), OutPutFile(), OutPutPost(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetMat(), mesh::SetHhat(), material::SetMatConstants(), SolveEigen(), and material::UpdateDisplacement().
Line()
void slopeproject::Line (VecDoub a, VecDoub b, Int ndivs, MatDoub & path)
Definition at line 1598 of file slopeproject.cpp.
References NRmatrix< T >::assign().
Referenced by findbcids().
MonteCarloGIM()
void slopeproject::MonteCarloGIM (int iter, int iter2, bool print, string writenamefolder)
Definition at line 1840 of file slopeproject.cpp.
References AssembleHhationho(), NRmatrix< T >::CopyFromVector(), fklgalerking, mesh::fmaterial, fmesh, frandomfield, material::GetBodyForce(), KLGalerkinRF::GetExpansionorder(), KLGalerkinRF::Getftype(), KLGalerkinRF::GetLx(), KLGalerkinRF::GetLy(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), KLGalerkinRF::GetSamples(), KLGalerkinRF::GetSig(), IterativeProcess(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), OutPutFile1var(), shapequad::pointsandweigths(), PrintMCS(), mesh::SetHhat(), material::SetMatConstants(), material::SetMemory(), material::SetRandomField(), and material::UpdateBodyForce().
Referenced by main2(), mainlinux(), mainlinuxserial(), myTreads(), and myTreads2().
MonteCarloSRM()
void slopeproject::MonteCarloSRM (int iter, int iter2, bool print, string writenamefolder)
Definition at line 1645 of file slopeproject.cpp.
References AssembleHhationho(), NRmatrix< T >::CopyFromVector(), mesh::fmaterial, fmesh, frandomfield, mesh::GetAllCoords(), material::GetBodyForce(), material::GetMatConstants(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), IterativeProcessShearRed(), NRmatrix< T >::nrows(), OutPutFile1var(), OutPutPost(), shapequad::pointsandweigths(), material::PostProcess(), material::PostProcessIntegrationPointVar(), material::ResetMat(), mesh::SetHhat(), material::SetMatConstants(), material::SetMemory(), and material::UpdateBodyForce().
Referenced by main2(), mainlinuxserial(), and myTreadsSRM().
OutPutFile()
void slopeproject::OutPutFile (MatDoub & postdata, std::ofstream & file)
Definition at line 2097 of file slopeproject.cpp.
References NRmatrix< T >::nrows().
Referenced by IterativeProcess(), IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), and IterativeProcessShearRed2().
OutPutFile1var()
void slopeproject::OutPutFile1var (MatDoub & postdata, std::ofstream & file)
Definition at line 2084 of file slopeproject.cpp.
References NRmatrix< T >::nrows().
Referenced by MonteCarloGIM(), and MonteCarloSRM().
OutPutFile4var()
void slopeproject::OutPutFile4var (MatDoub & postdata, std::ofstream & file)
OutPutPost() [1/3]
void slopeproject::OutPutPost (MatDoub & postdata, std::ofstream & file)
Definition at line 2172 of file slopeproject.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by CreateRandomField(), IterativeProcess(), IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), IterativeProcessShearRed2(), mainlinux(), mainlinuxserial(), MonteCarloSRM(), and PrintMCS().
OutPutPost() [2/3]
void slopeproject::OutPutPost (MatInt & postdata, std::ofstream & file)
Definition at line 2186 of file slopeproject.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
OutPutPost() [3/3]
void slopeproject::OutPutPost (std::vector< std::vector< double >> & postdata, std::ofstream & file)
Definition at line 2153 of file slopeproject.cpp.
PrintMathematicaFormat()
void slopeproject::PrintMathematicaFormat (MatDoub postdata, std::ofstream & file)
Definition at line 2200 of file slopeproject.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess().
PrintMCS()
void slopeproject::PrintMCS (string namefolder, int imc, bool print)
Definition at line 1998 of file slopeproject.cpp.
References AssembleHhationho(), mesh::fmaterial, fmesh, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), material::GetSolution(), OutPutPost(), material::PostProcess(), and material::PostProcessIntegrationPointVar().
Referenced by MonteCarloGIM().
ReadMatDoub()
void slopeproject::ReadMatDoub (MatDoub & matdoub, std::string file)
Definition at line 1520 of file slopeproject.cpp.
References NRmatrix< T >::CopyFromVector(), and vecstr_to_vecdoub2().
ReadMesh()
void slopeproject::ReadMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology, string filenameel, string filenamecoord)
Definition at line 1378 of file slopeproject.cpp.
References NRmatrix< T >::CopyFromVector(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), vecstr_to_vecdoub(), and vecstr_to_vecint().
SolveEigen() [1/2]
void slopeproject::SolveEigen (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 1321 of file slopeproject.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
SolveEigen() [2/2]
void slopeproject::SolveEigen (SparseMatrix< double > A, VectorXd b, VectorXd & x)
time_span = static_cast<chrono::duration<double>>(end - start);
Definition at line 122 of file slopeproject.cpp.
Referenced by IterativeProcess(), IterativeProcessArcLengthSRM(), and IterativeProcessShearRed2().
SolveEigen2()
void slopeproject::SolveEigen2 (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 661 of file slopeproject.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess().
SolveEigen3()
void slopeproject::SolveEigen3 (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 1298 of file slopeproject.cpp.
References NRmatrix< T >::assign(), NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
SolveEigenSparse()
void slopeproject::SolveEigenSparse (MatDoub A, MatDoub b, MatDoub & x)
Definition at line 1342 of file slopeproject.cpp.
References NRmatrix< T >::assign(), and NRmatrix< T >::nrows().
Referenced by IterativeProcess(), and IterativeProcessShearRed().
vecstr_to_vec()
template<class T > std::vector< T > slopeproject::vecstr_to_vec (std::vector< string > vs)
Definition at line 1507 of file slopeproject.cpp.
vecstr_to_vecdoub()
std::vector< Doub > slopeproject::vecstr_to_vecdoub (std::vector< string > vs)
Definition at line 1467 of file slopeproject.cpp.
Referenced by ReadMesh().
vecstr_to_vecdoub2()
std::vector< Doub > slopeproject::vecstr_to_vecdoub2 (std::vector< string > vs)
Definition at line 1493 of file slopeproject.cpp.
Referenced by ReadMatDoub().
vecstr_to_vecint()
std::vector< Int > slopeproject::vecstr_to_vecint (std::vector< string > vs)
Definition at line 1454 of file slopeproject.cpp.
Referenced by ReadMesh().
Member Data Documentation
fklgalerking
KLGalerkinRF* slopeproject::fklgalerking
Definition at line 71 of file slopeproject.h.
Referenced by CreateRandomField(), MonteCarloGIM(), slopeproject(), and ~slopeproject().
fmesh
mesh* slopeproject::fmesh
Definition at line 70 of file slopeproject.h.
Referenced by CreateRandomField(), IterativeProcess(), IterativeProcessArcLengthSRM(), IterativeProcessShearRed(), IterativeProcessShearRed2(), MonteCarloGIM(), MonteCarloSRM(), PrintMCS(), slopeproject(), and ~slopeproject().
frandomfield
NRmatrix<MatDoub> slopeproject::frandomfield
Definition at line 72 of file slopeproject.h.
Referenced by AssembleHhationho(), MonteCarloGIM(), MonteCarloSRM(), and slopeproject().
The documentation for this class was generated from the following files:
src/slopeproject.h
src/slopeproject.cpp