DCPROJ: NRvector< T > Class Template Reference
NRvector< T > Class Template Reference
#include <nr3.h>
Public Types
typedef T value_type
Public Member Functions
NRvector ()
NRvector (int n)
NRvector (int n, const T &a)
NRvector (int n, const T *a)
NRvector (const NRvector &rhs)
NRvector & operator= (const NRvector &rhs)
T & operator[] (const int i)
const T & operator[] (const int i) const
int size () const
void resize (int newn)
void assign (int newn, const T &a)
void Print ()
~NRvector ()
Private Attributes
int nn
T * v
Detailed Description
template<class T>
class NRvector< T >
Definition at line 150 of file nr3.h.
Member Typedef Documentation
value_type
template<class T > typedef T NRvector< T >::value_type
Definition at line 161 of file nr3.h.
Constructor & Destructor Documentation
NRvector() [1/5]
template<class T > NRvector< T >::NRvector
Definition at line 178 of file nr3.h.
NRvector() [2/5]
template<class T > NRvector< T >::NRvector (int n) explicit
Definition at line 181 of file nr3.h.
NRvector() [3/5]
template<class T > NRvector< T >::NRvector (int n, const T & a)
Definition at line 184 of file nr3.h.
NRvector() [4/5]
template<class T > NRvector< T >::NRvector (int n, const T * a)
Definition at line 190 of file nr3.h.
NRvector() [5/5]
template<class T > NRvector< T >::NRvector (const NRvector< T > & rhs)
~NRvector()
template<class T > NRvector< T >::~NRvector
Definition at line 270 of file nr3.h.
Member Function Documentation
assign()
template<class T > void NRvector< T >::assign (int newn, const T & a)
Definition at line 259 of file nr3.h.
Referenced by FindEl(), vonmises::GetMatConstants(), druckerprager::GetMatConstants(), and KLGalerkinRF::SolveGenEigValProblem().
operator=()
template<class T > NRvector< T > & NRvector< T >::operator= (const NRvector< T > & rhs)
Definition at line 202 of file nr3.h.
operator[]() [1/2]
template<class T > T & NRvector< T >::operator[] (const int i) inline
Definition at line 221 of file nr3.h.
operator[]() [2/2]
template<class T > const T & NRvector< T >::operator[] (const int i) const inline
Definition at line 232 of file nr3.h.
Print()
template<class T > void NRvector< T >::Print
Definition at line 277 of file nr3.h.
Referenced by mesh::FindSolution(), elastoplastic2D< YC >::PostProcessStrain(), and KLGalerkinRF::SolveGenEigValProblem().
resize()
template<class T > void NRvector< T >::resize (int newn)
Definition at line 249 of file nr3.h.
Referenced by FindEl(), Powell< T >::minimize(), Frprmn< T >::minimize(), mohrcoulomb::Phi(), elastoplastic2D< YC >::PostProcessStrain(), and zbrak().
size()
template<class T > int NRvector< T >::size inline
Definition at line 243 of file nr3.h.
Referenced by NRtensor< Doub >::EigenSystem(), Jacobi::eigsrt(), Cholesky::elmult(), Cholesky::elsolve(), FindEl(), pressurizedhole::FindIds(), mesh::FindIds(), beam3dtools::FindIds(), Linemethod< T >::linmin(), Dlinemethod< T >::linmin(), MonteCarlo(), MonteCarloTalude2(), Cholesky::solve(), LUdcmp::solve(), and KLGalerkinRF::SolveGenEigValProblem().
Member Data Documentation
nn
template<class T > int NRvector< T >::nn private
Definition at line 152 of file nr3.h.
Referenced by NRvector< Doub >::operator=().
v
template<class T > T* NRvector< T >::v private
Definition at line 153 of file nr3.h.
Referenced by NRvector< Doub >::NRvector().
The documentation for this class was generated from the following file:
src/nr3.h