DCPROJ: src/dcproj.cpp File Reference
dcproj.cpp File Reference
#include "dcproj.h"
#include "mesh.h"
#include "elastoplastic3D.h"
#include <thread>
#include "beam3dtools.h"
#include "pressurizedhole.h"
#include <Eigen/Core>
Classes
class SynchronizedFile
class Writer
Macros
#define EIGEN_USE_MKL_ALL
Functions
void ReadMatDoub (MatDoub &matdoub, std::string file)
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > &allcoords, MatDoub &meshcoords, MatInt &meshtopology, string filenameel, string filenamecoord)
template<class T >
void OutPutPost (NRmatrix< T > &postdata, std::ofstream &file)
template<class T >
void vecstr_to_vec (std::vector< std::string > vs, std::vector< T > &ret)
std::vector< Int > vecstr_to_vecint (std::vector< string > vs)
std::vector< Doub > vecstr_to_vecdoub (std::vector< string > vs)
void myTreads (int a, int b, slopeproject *slopeobj2, string traedN)
void leakcraw ()
void myTreadsSRM (int a, int b, slopeproject *slopeobj2, string namefolder3)
void mainlinux2 (int simtype, int comeco, int fim)
void mainlinux (int simtype, int comeco, int fim)
void mainwindows ()
void createrandomfield ()
void mainlinuxserial (int simtype, int comeco, int fim)
int main3 ()
int main (int argc, char *argv[])
std::vector< Doub > vecstr_to_vecdoub2 (std::vector< string > vs)
template<class T >
std::vector< T > vecstr_to_vec (std::vector< string > vs)
Macro Definition Documentation
EIGEN_USE_MKL_ALL
#define EIGEN_USE_MKL_ALL
Definition at line 18 of file dcproj.cpp.
Function Documentation
createrandomfield()
void createrandomfield ()
Definition at line 904 of file dcproj.cpp.
References slopeproject::CreateRandomField(), elastoplastic2D< YC >::fYC, NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), ReadMesh(), elastoplastic2D< YC >::SetMemory(), KLGalerkinRF::SetMesh(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
leakcraw()
void leakcraw ()
main()
int main (int argc, char * argv[])
Definition at line 1188 of file dcproj.cpp.
References mainlinux(), mainwindows(), and beam3dtools::SolveElasticBeam().
main3()
int main3 ()
Definition at line 1132 of file dcproj.cpp.
mainlinux()
void mainlinux (int simtype, int comeco, int fim)
Definition at line 185 of file dcproj.cpp.
References slopeproject::AssembleHhationho(), slopeproject::CreateRandomField(), mesh::fmaterial, elastoplastic2D< YC >::fYC, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), slopeproject::IterativeProcess(), slopeproject::MonteCarloGIM(), myTreadsSRM(), NRmatrix< T >::nrows(), slopeproject::OutPutPost(), OutPutPost(), shapequad::pointsandweigths(), material::PostProcess(), ReadMatDoub(), ReadMesh(), mesh::SetHhat(), elastoplastic2D< YC >::SetMemory(), KLGalerkinRF::SetMesh(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
Referenced by main().
mainlinux2()
void mainlinux2 (int simtype, int comeco, int fim)
Definition at line 74 of file dcproj.cpp.
References elastoplastic2D< YC >::fYC, myTreads(), NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), ReadMatDoub(), ReadMesh(), elastoplastic2D< YC >::SetMemory(), KLGalerkinRF::SetMesh(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
mainlinuxserial()
void mainlinuxserial (int simtype, int comeco, int fim)
Definition at line 972 of file dcproj.cpp.
References slopeproject::AssembleHhationho(), slopeproject::CreateRandomField(), mesh::fmaterial, elastoplastic2D< YC >::fYC, mesh::GetAllCoords(), mesh::GetMeshNodes(), mesh::GetMeshTopology(), slopeproject::IterativeProcess(), slopeproject::MonteCarloGIM(), slopeproject::MonteCarloSRM(), NRmatrix< T >::nrows(), slopeproject::OutPutPost(), OutPutPost(), shapequad::pointsandweigths(), material::PostProcess(), ReadMatDoub(), ReadMesh(), mesh::SetHhat(), elastoplastic2D< YC >::SetMemory(), KLGalerkinRF::SetMesh(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
mainwindows()
void mainwindows ()
Definition at line 719 of file dcproj.cpp.
References elastoplastic2D< YC >::fYC, mesh::GetAllCoords(), slopeproject::IterativeProcessShearRed(), myTreads(), NRmatrix< T >::nrows(), OutPutPost(), shapequad::pointsandweigths(), ReadMatDoub(), ReadMesh(), elastoplastic2D< YC >::SetMemory(), KLGalerkinRF::SetMesh(), druckerprager::setup(), and elastoplastic2D< YC >::UpdateBodyForce().
Referenced by main().
myTreads()
void myTreads (int a, int b, slopeproject * slopeobj2, string traedN)
Definition at line 61 of file dcproj.cpp.
References slopeproject::MonteCarloGIM().
Referenced by mainlinux2(), and mainwindows().
myTreadsSRM()
void myTreadsSRM (int a, int b, slopeproject * slopeobj2, string namefolder3)
Definition at line 67 of file dcproj.cpp.
References slopeproject::MonteCarloSRM().
Referenced by mainlinux().
OutPutPost()
template<class T > void OutPutPost (NRmatrix< T > & postdata, std::ofstream & file)
Definition at line 1230 of file dcproj.cpp.
References NRmatrix< T >::ncols(), and NRmatrix< T >::nrows().
Referenced by createrandomfield(), mainlinux(), mainlinux2(), mainlinuxserial(), and mainwindows().
ReadMatDoub()
void ReadMatDoub (MatDoub & matdoub, std::string file)
Definition at line 1374 of file dcproj.cpp.
References NRmatrix< T >::CopyFromVector(), and vecstr_to_vecdoub2().
Referenced by mainlinux(), mainlinux2(), mainlinuxserial(), and mainwindows().
ReadMesh()
void ReadMesh (std::vector< std::vector< std::vector< Doub > > > & allcoords, MatDoub & meshcoords, MatInt & meshtopology, string filenameel, string filenamecoord)
Definition at line 1245 of file dcproj.cpp.
References NRmatrix< T >::CopyFromVector(), NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), NRmatrix< T >::Print(), vecstr_to_vecdoub(), and vecstr_to_vecint().
Referenced by createrandomfield(), mainlinux(), mainlinux2(), mainlinuxserial(), and mainwindows().
vecstr_to_vec() [1/2]
template<class T > void vecstr_to_vec (std::vector< std::string > vs, std::vector< T > & ret)
vecstr_to_vec() [2/2]
template<class T > std::vector< T > vecstr_to_vec (std::vector< string > vs)
Definition at line 1361 of file dcproj.cpp.
vecstr_to_vecdoub()
std::vector< Doub > vecstr_to_vecdoub (std::vector< string > vs)
Definition at line 1334 of file dcproj.cpp.
Referenced by ReadMesh().
vecstr_to_vecdoub2()
std::vector<Doub> vecstr_to_vecdoub2 (std::vector< string > vs)
Definition at line 1347 of file dcproj.cpp.
Referenced by ReadMatDoub().
vecstr_to_vecint()
std::vector< Int > vecstr_to_vecint (std::vector< string > vs)
Definition at line 1321 of file dcproj.cpp.
Referenced by ReadMesh().