DCPROJ: src/nr3.h File Reference
nr3.h File Reference
#include <math.h>
#include <cmath>
#include <fstream>
#include <complex>
#include <iostream>
#include <iomanip>
#include <vector>
#include <limits>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <fcntl.h>
#include <string.h>
#include <ctype.h>
#include "error.h"
#include <Eigen/Core>
Classes
class NRvector< T >
class NRmatrix< T >
class NRMat3d< T >
class NRtensor< T >
class NRmatrix3D< T >
struct Jacobi
Macros
#define _XX_
#define _YY_
#define _ZZ_
#define _XZ_
#define _YZ_
#define _XY_
#define _CHECKBOUNDS_
#define _USE_MATH_DEFINES
Typedefs
typedef int Int
typedef double Doub
typedef unsigned int Uint
typedef long long int Llong
typedef unsigned long long int Ullong
typedef char Char
typedef unsigned char Uchar
typedef long double Ldoub
typedef complex< double > Complex
typedef bool Bool
typedef NRvector< Int > VecInt
typedef NRvector< Int > VecInt_O
typedef NRvector< Int > VecInt_IO
typedef NRvector< Uint > VecUint
typedef NRvector< Uint > VecUint_O
typedef NRvector< Uint > VecUint_IO
typedef NRvector< Llong > VecLlong
typedef NRvector< Llong > VecLlong_O
typedef NRvector< Llong > VecLlong_IO
typedef NRvector< Ullong > VecUllong
typedef NRvector< Ullong > VecUllong_O
typedef NRvector< Ullong > VecUllong_IO
typedef NRvector< Char > VecChar
typedef NRvector< Char > VecChar_O
typedef NRvector< Char > VecChar_IO
typedef NRvector< Char * > VecCharp
typedef NRvector< Char * > VecCharp_O
typedef NRvector< Char * > VecCharp_IO
typedef NRvector< Uchar > VecUchar
typedef NRvector< Uchar > VecUchar_O
typedef NRvector< Uchar > VecUchar_IO
typedef NRvector< Doub > VecDoub
typedef NRvector< Doub > VecDoub_O
typedef NRvector< Doub > VecDoub_IO
typedef NRvector< Doub * > VecDoubp
typedef NRvector< Doub * > VecDoubp_O
typedef NRvector< Doub * > VecDoubp_IO
typedef NRvector< Complex > VecComplex
typedef NRvector< Complex > VecComplex_O
typedef NRvector< Complex > VecComplex_IO
typedef NRvector< Bool > VecBool
typedef NRvector< Bool > VecBool_O
typedef NRvector< Bool > VecBool_IO
typedef NRmatrix< Int > MatInt
typedef NRmatrix< Int > MatInt_O
typedef NRmatrix< Int > MatInt_IO
typedef NRmatrix< Uint > MatUint
typedef NRmatrix< Uint > MatUint_O
typedef NRmatrix< Uint > MatUint_IO
typedef NRmatrix< Llong > MatLlong
typedef NRmatrix< Llong > MatLlong_O
typedef NRmatrix< Llong > MatLlong_IO
typedef NRmatrix< Ullong > MatUllong
typedef NRmatrix< Ullong > MatUllong_O
typedef NRmatrix< Ullong > MatUllong_IO
typedef NRmatrix< Char > MatChar
typedef NRmatrix< Char > MatChar_O
typedef NRmatrix< Char > MatChar_IO
typedef NRmatrix< Uchar > MatUchar
typedef NRmatrix< Uchar > MatUchar_O
typedef NRmatrix< Uchar > MatUchar_IO
typedef NRmatrix< Doub > MatDoub
typedef NRmatrix< Doub > MatDoub_O
typedef NRmatrix< Doub > MatDoub_IO
typedef NRmatrix< Bool > MatBool
typedef NRmatrix< Bool > MatBool_O
typedef NRmatrix< Bool > MatBool_IO
typedef NRMat3d< Doub > Mat3DDoub
typedef NRMat3d< Doub > Mat3DDoub_O
typedef NRMat3d< Doub > Mat3DDoub_IO
typedef NRmatrix3D< Doub > Matrix3DDoub
typedef NRmatrix3D< Doub > Matrix3DDoub_O
typedef NRmatrix3D< Doub > Matrix3DDoub_IO
Functions
template<class T >
T SQR (const T a)
template<class T >
const T & MAX (const T &a, const T &b)
float MAX (const double &a, const float &b)
float MAX (const float &a, const double &b)
template<class T >
const T & MIN (const T &a, const T &b)
float MIN (const double &a, const float &b)
float MIN (const float &a, const double &b)
template<class T >
T SIGN (const T &a, const T &b)
float SIGN (const float &a, const double &b)
float SIGN (const double &a, const float &b)
template<class T >
void SWAP (T &a, T &b)
Variables
const typedef NRvector< Int > VecInt_I
const typedef NRvector< Uint > VecUint_I
const typedef NRvector< Llong > VecLlong_I
const typedef NRvector< Ullong > VecUllong_I
const typedef NRvector< Char > VecChar_I
const typedef NRvector< Char * > VecCharp_I
const typedef NRvector< Uchar > VecUchar_I
const typedef NRvector< Doub > VecDoub_I
const typedef NRvector< Doub * > VecDoubp_I
const typedef NRvector< Complex > VecComplex_I
const typedef NRvector< Bool > VecBool_I
const typedef NRmatrix< Int > MatInt_I
const typedef NRmatrix< Uint > MatUint_I
const typedef NRmatrix< Llong > MatLlong_I
const typedef NRmatrix< Ullong > MatUllong_I
const typedef NRmatrix< Char > MatChar_I
const typedef NRmatrix< Uchar > MatUchar_I
const typedef NRmatrix< Doub > MatDoub_I
const typedef NRmatrix< Bool > MatBool_I
const typedef NRMat3d< Doub > Mat3DDoub_I
const typedef NRmatrix3D< Doub > Matrix3DDoub_I
static const Doub NaN
Macro Definition Documentation
_CHECKBOUNDS_
#define _CHECKBOUNDS_
Definition at line 38 of file nr3.h.
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 57 of file nr3.h.
_XX_
#define _XX_
Definition at line 28 of file nr3.h.
_XY_
#define _XY_
Definition at line 33 of file nr3.h.
_XZ_
#define _XZ_
Definition at line 31 of file nr3.h.
_YY_
#define _YY_
Definition at line 29 of file nr3.h.
_YZ_
#define _YZ_
Definition at line 32 of file nr3.h.
_ZZ_
#define _ZZ_
Definition at line 30 of file nr3.h.
Typedef Documentation
Bool
typedef bool Bool
Definition at line 1372 of file nr3.h.
Char
typedef char Char
Definition at line 1364 of file nr3.h.
Complex
typedef complex<double> Complex
Definition at line 1370 of file nr3.h.
Doub
typedef double Doub
Definition at line 1353 of file nr3.h.
Int
typedef int Int
Definition at line 1352 of file nr3.h.
Ldoub
typedef long double Ldoub
Definition at line 1368 of file nr3.h.
Llong
typedef long long int Llong
Definition at line 1360 of file nr3.h.
Mat3DDoub
typedef NRMat3d<Doub> Mat3DDoub
Definition at line 1448 of file nr3.h.
Mat3DDoub_IO
typedef NRMat3d<Doub> Mat3DDoub_IO
Definition at line 1448 of file nr3.h.
Mat3DDoub_O
typedef NRMat3d<Doub> Mat3DDoub_O
Definition at line 1448 of file nr3.h.
MatBool
typedef NRmatrix<Bool> MatBool
Definition at line 1443 of file nr3.h.
MatBool_IO
typedef NRmatrix<Bool> MatBool_IO
Definition at line 1443 of file nr3.h.
MatBool_O
typedef NRmatrix<Bool> MatBool_O
Definition at line 1443 of file nr3.h.
MatChar
typedef NRmatrix<Char> MatChar
Definition at line 1434 of file nr3.h.
MatChar_IO
typedef NRmatrix<Char> MatChar_IO
Definition at line 1434 of file nr3.h.
MatChar_O
typedef NRmatrix<Char> MatChar_O
Definition at line 1434 of file nr3.h.
MatDoub
typedef NRmatrix<Doub> MatDoub
Definition at line 1440 of file nr3.h.
MatDoub_IO
typedef NRmatrix<Doub> MatDoub_IO
Definition at line 1440 of file nr3.h.
MatDoub_O
typedef NRmatrix<Doub> MatDoub_O
Definition at line 1440 of file nr3.h.
MatInt
typedef NRmatrix<Int> MatInt
Definition at line 1422 of file nr3.h.
MatInt_IO
typedef NRmatrix<Int> MatInt_IO
Definition at line 1422 of file nr3.h.
MatInt_O
typedef NRmatrix<Int> MatInt_O
Definition at line 1422 of file nr3.h.
MatLlong
typedef NRmatrix<Llong> MatLlong
Definition at line 1428 of file nr3.h.
MatLlong_IO
typedef NRmatrix<Llong> MatLlong_IO
Definition at line 1428 of file nr3.h.
MatLlong_O
typedef NRmatrix<Llong> MatLlong_O
Definition at line 1428 of file nr3.h.
Matrix3DDoub
typedef NRmatrix3D<Doub> Matrix3DDoub
Definition at line 1456 of file nr3.h.
Matrix3DDoub_IO
typedef NRmatrix3D<Doub> Matrix3DDoub_IO
Definition at line 1456 of file nr3.h.
Matrix3DDoub_O
typedef NRmatrix3D<Doub> Matrix3DDoub_O
Definition at line 1456 of file nr3.h.
MatUchar
typedef NRmatrix<Uchar> MatUchar
Definition at line 1437 of file nr3.h.
MatUchar_IO
typedef NRmatrix<Uchar> MatUchar_IO
Definition at line 1437 of file nr3.h.
MatUchar_O
typedef NRmatrix<Uchar> MatUchar_O
Definition at line 1437 of file nr3.h.
MatUint
typedef NRmatrix<Uint> MatUint
Definition at line 1425 of file nr3.h.
MatUint_IO
typedef NRmatrix<Uint> MatUint_IO
Definition at line 1425 of file nr3.h.
MatUint_O
typedef NRmatrix<Uint> MatUint_O
Definition at line 1425 of file nr3.h.
MatUllong
typedef NRmatrix<Ullong> MatUllong
Definition at line 1431 of file nr3.h.
MatUllong_IO
typedef NRmatrix<Ullong> MatUllong_IO
Definition at line 1431 of file nr3.h.
MatUllong_O
typedef NRmatrix<Ullong> MatUllong_O
Definition at line 1431 of file nr3.h.
Uchar
typedef unsigned char Uchar
Definition at line 1365 of file nr3.h.
Uint
typedef unsigned int Uint
Definition at line 1354 of file nr3.h.
Ullong
typedef unsigned long long int Ullong
Definition at line 1361 of file nr3.h.
VecBool
typedef NRvector<Bool> VecBool
Definition at line 1417 of file nr3.h.
VecBool_IO
typedef NRvector<Bool> VecBool_IO
Definition at line 1417 of file nr3.h.
VecBool_O
typedef NRvector<Bool> VecBool_O
Definition at line 1417 of file nr3.h.
VecChar
typedef NRvector<Char> VecChar
Definition at line 1399 of file nr3.h.
VecChar_IO
typedef NRvector<Char> VecChar_IO
Definition at line 1399 of file nr3.h.
VecChar_O
typedef NRvector<Char> VecChar_O
Definition at line 1399 of file nr3.h.
VecCharp
typedef NRvector<Char*> VecCharp
Definition at line 1402 of file nr3.h.
VecCharp_IO
typedef NRvector<Char*> VecCharp_IO
Definition at line 1402 of file nr3.h.
VecCharp_O
typedef NRvector<Char*> VecCharp_O
Definition at line 1402 of file nr3.h.
VecComplex
typedef NRvector<Complex> VecComplex
Definition at line 1414 of file nr3.h.
VecComplex_IO
typedef NRvector<Complex> VecComplex_IO
Definition at line 1414 of file nr3.h.
VecComplex_O
typedef NRvector<Complex> VecComplex_O
Definition at line 1414 of file nr3.h.
VecDoub
typedef NRvector<Doub> VecDoub
Definition at line 1408 of file nr3.h.
VecDoub_IO
typedef NRvector<Doub> VecDoub_IO
Definition at line 1408 of file nr3.h.
VecDoub_O
typedef NRvector<Doub> VecDoub_O
Definition at line 1408 of file nr3.h.
VecDoubp
typedef NRvector<Doub*> VecDoubp
Definition at line 1411 of file nr3.h.
VecDoubp_IO
typedef NRvector<Doub*> VecDoubp_IO
Definition at line 1411 of file nr3.h.
VecDoubp_O
typedef NRvector<Doub*> VecDoubp_O
Definition at line 1411 of file nr3.h.
VecInt
typedef NRvector<Int> VecInt
Definition at line 1387 of file nr3.h.
VecInt_IO
typedef NRvector<Int> VecInt_IO
Definition at line 1387 of file nr3.h.
VecInt_O
typedef NRvector<Int> VecInt_O
Definition at line 1387 of file nr3.h.
VecLlong
typedef NRvector<Llong> VecLlong
Definition at line 1393 of file nr3.h.
VecLlong_IO
typedef NRvector<Llong> VecLlong_IO
Definition at line 1393 of file nr3.h.
VecLlong_O
typedef NRvector<Llong> VecLlong_O
Definition at line 1393 of file nr3.h.
VecUchar
typedef NRvector<Uchar> VecUchar
Definition at line 1405 of file nr3.h.
VecUchar_IO
typedef NRvector<Uchar> VecUchar_IO
Definition at line 1405 of file nr3.h.
VecUchar_O
typedef NRvector<Uchar> VecUchar_O
Definition at line 1405 of file nr3.h.
VecUint
typedef NRvector<Uint> VecUint
Definition at line 1390 of file nr3.h.
VecUint_IO
typedef NRvector<Uint> VecUint_IO
Definition at line 1390 of file nr3.h.
VecUint_O
typedef NRvector<Uint> VecUint_O
Definition at line 1390 of file nr3.h.
VecUllong
typedef NRvector<Ullong> VecUllong
Definition at line 1396 of file nr3.h.
VecUllong_IO
typedef NRvector<Ullong> VecUllong_IO
Definition at line 1396 of file nr3.h.
VecUllong_O
typedef NRvector<Ullong> VecUllong_O
Definition at line 1396 of file nr3.h.
Function Documentation
MAX() [1/3]
float MAX (const double & a, const float & b) inline
Definition at line 77 of file nr3.h.
MAX() [2/3]
float MAX (const float & a, const double & b) inline
Definition at line 82 of file nr3.h.
MAX() [3/3]
template<class T > const T& MAX (const T & a, const T & b) inline
Definition at line 72 of file nr3.h.
Referenced by Bracketmethod::bracket(), Unsymmeig::hqr(), Unsymmeig::hqr2(), and Frprmn< T >::minimize().
MIN() [1/3]
float MIN (const double & a, const float & b) inline
Definition at line 93 of file nr3.h.
MIN() [2/3]
float MIN (const float & a, const double & b) inline
Definition at line 98 of file nr3.h.
MIN() [3/3]
template<class T > const T& MIN (const T & a, const T & b) inline
Definition at line 88 of file nr3.h.
SIGN() [1/3]
float SIGN (const double & a, const float & b) inline
Definition at line 114 of file nr3.h.
SIGN() [2/3]
float SIGN (const float & a, const double & b) inline
Definition at line 109 of file nr3.h.
SIGN() [3/3]
template<class T > T SIGN (const T & a, const T & b) inline
Definition at line 104 of file nr3.h.
Referenced by Bracketmethod::bracket(), Unsymmeig::hqr(), Unsymmeig::hqr2(), Brent::minimize(), Dbrent::minimize(), zbrent(), and zriddr().
SQR()
template<class T > T SQR (const T a) inline
Definition at line 69 of file nr3.h.
Referenced by Unsymmeig::hqr2(), and Powell< T >::minimize().
SWAP()
template<class T > void SWAP (T & a, T & b) inline
Definition at line 120 of file nr3.h.
Referenced by Bracketmethod::bracket(), Unsymmeig::elmhes(), rtflsp(), and rtsec().
Variable Documentation
Mat3DDoub_I
const typedef NRMat3d<Doub> Mat3DDoub_I
Definition at line 1447 of file nr3.h.
MatBool_I
const typedef NRmatrix<Bool> MatBool_I
Definition at line 1442 of file nr3.h.
MatChar_I
const typedef NRmatrix<Char> MatChar_I
Definition at line 1433 of file nr3.h.
MatDoub_I
const typedef NRmatrix<Doub> MatDoub_I
Definition at line 1439 of file nr3.h.
MatInt_I
const typedef NRmatrix<Int> MatInt_I
Definition at line 1421 of file nr3.h.
MatLlong_I
const typedef NRmatrix<Llong> MatLlong_I
Definition at line 1427 of file nr3.h.
Matrix3DDoub_I
const typedef NRmatrix3D<Doub> Matrix3DDoub_I
Definition at line 1455 of file nr3.h.
MatUchar_I
const typedef NRmatrix<Uchar> MatUchar_I
Definition at line 1436 of file nr3.h.
MatUint_I
const typedef NRmatrix<Uint> MatUint_I
Definition at line 1424 of file nr3.h.
MatUllong_I
const typedef NRmatrix<Ullong> MatUllong_I
Definition at line 1430 of file nr3.h.
NaN
const Doub NaN static
Definition at line 1377 of file nr3.h.
VecBool_I
const typedef NRvector<Bool> VecBool_I
Definition at line 1416 of file nr3.h.
VecChar_I
const typedef NRvector<Char> VecChar_I
Definition at line 1398 of file nr3.h.
VecCharp_I
const typedef NRvector<Char*> VecCharp_I
Definition at line 1401 of file nr3.h.
VecComplex_I
const typedef NRvector<Complex> VecComplex_I
Definition at line 1413 of file nr3.h.
VecDoub_I
const typedef NRvector<Doub> VecDoub_I
Definition at line 1407 of file nr3.h.
VecDoubp_I
const typedef NRvector<Doub*> VecDoubp_I
Definition at line 1410 of file nr3.h.
VecInt_I
const typedef NRvector<Int> VecInt_I
Definition at line 1386 of file nr3.h.
VecLlong_I
const typedef NRvector<Llong> VecLlong_I
Definition at line 1392 of file nr3.h.
VecUchar_I
const typedef NRvector<Uchar> VecUchar_I
Definition at line 1404 of file nr3.h.
VecUint_I
const typedef NRvector<Uint> VecUint_I
Definition at line 1389 of file nr3.h.
VecUllong_I
const typedef NRvector<Ullong> VecUllong_I
Definition at line 1395 of file nr3.h.