DCPROJ: src/roots.h File Reference
roots.h File Reference
Functions
template<class T >
Bool zbrac (T &func, Doub &x1, Doub &x2)
template<class T >
void zbrak (T &fx, const Doub x1, const Doub x2, const Int n, VecDoub_O &xb1, VecDoub_O &xb2, Int &nroot)
template<class T >
Doub rtbis (T &func, const Doub x1, const Doub x2, const Doub xacc)
template<class T >
Doub rtflsp (T &func, const Doub x1, const Doub x2, const Doub xacc)
template<class T >
Doub rtsec (T &func, const Doub x1, const Doub x2, const Doub xacc)
template<class T >
Doub zriddr (T &func, const Doub x1, const Doub x2, const Doub xacc)
template<class T >
Doub zbrent (T &func, const Doub x1, const Doub x2, const Doub tol)
template<class T >
Doub rtnewt (T &funcd, const Doub x1, const Doub x2, const Doub xacc)
template<class T >
Doub rtsafe (T &funcd, const Doub x1, const Doub x2, const Doub xacc, bool &flag)
Function Documentation
rtbis()
template<class T > Doub rtbis (T & func, const Doub x1, const Doub x2, const Doub xacc)
Definition at line 51 of file roots.h.
rtflsp()
template<class T > Doub rtflsp (T & func, const Doub x1, const Doub x2, const Doub xacc)
Definition at line 66 of file roots.h.
References SWAP().
rtnewt()
template<class T > Doub rtnewt (T & funcd, const Doub x1, const Doub x2, const Doub xacc)
Definition at line 235 of file roots.h.
rtsafe()
template<class T > Doub rtsafe (T & funcd, const Doub x1, const Doub x2, const Doub xacc, bool & flag)
Definition at line 250 of file roots.h.
References flag.
Referenced by druckerprager::FindMinimum().
rtsec()
template<class T > Doub rtsec (T & func, const Doub x1, const Doub x2, const Doub xacc)
Definition at line 101 of file roots.h.
References SWAP().
zbrac()
template<class T > Bool zbrac (T & func, Doub & x1, Doub & x2)
Definition at line 4 of file roots.h.
zbrak()
template<class T > void zbrak (T & fx, const Doub x1, const Doub x2, const Int n, VecDoub_O & xb1, VecDoub_O & xb2, Int & nroot)
Definition at line 21 of file roots.h.
References NRvector< T >::resize().
zbrent()
template<class T > Doub zbrent (T & func, const Doub x1, const Doub x2, const Doub tol)
Definition at line 170 of file roots.h.
References SIGN().
zriddr()
template<class T > Doub zriddr (T & func, const Doub x1, const Doub x2, const Doub xacc)
Definition at line 126 of file roots.h.
References SIGN().