DCPROJ: Dbrent Struct Reference
Dbrent Struct Reference
#include <mins_ndim.h>
Public Member Functions
Dbrent (const Doub toll=3.0e-8)
template<class T >
Doub minimize (T &funcd)
Public Member Functions inherited from Bracketmethod
template<class T >
void bracket (const Doub a, const Doub b, T &func)
void shft2 (Doub &a, Doub &b, const Doub c)
void shft3 (Doub &a, Doub &b, Doub &c, const Doub d)
void mov3 (Doub &a, Doub &b, Doub &c, const Doub d, const Doub e, const Doub f)
Public Attributes
Doub xmin
Doub fmin
const Doub tol
Public Attributes inherited from Bracketmethod
Doub ax
Doub bx
Doub cx
Doub fa
Doub fb
Doub fc
Detailed Description
Definition at line 478 of file mins_ndim.h.
Constructor & Destructor Documentation
Dbrent()
Dbrent::Dbrent (const Doub toll = 3.0e-8) inline
Definition at line 481 of file mins_ndim.h.
Member Function Documentation
minimize()
template<class T > Doub Dbrent::minimize (T & funcd) inline
Definition at line 483 of file mins_ndim.h.
References Bracketmethod::ax, Bracketmethod::bx, Bracketmethod::cx, fmin, Bracketmethod::mov3(), SIGN(), tol, and xmin.
Referenced by Dlinemethod< T >::linmin().
Member Data Documentation
fmin
Doub Dbrent::fmin
Definition at line 479 of file mins_ndim.h.
Referenced by Dlinemethod< T >::linmin(), and minimize().
tol
const Doub Dbrent::tol
Definition at line 480 of file mins_ndim.h.
Referenced by minimize().
xmin
Doub Dbrent::xmin
Definition at line 479 of file mins_ndim.h.
Referenced by minimize().
The documentation for this struct was generated from the following file:
src/mins_ndim.h