DCPROJ: Cholesky Struct Reference
Cholesky Struct Reference
#include <cholesky.h>
Public Member Functions
Cholesky (MatDoub_I &a)
void solve (VecDoub_I &b, VecDoub_O &x)
void elmult (VecDoub_I &y, VecDoub_O &b)
void elsolve (VecDoub_I &b, VecDoub_O &y)
void inverse (MatDoub_O &ainv)
Doub logdet ()
Public Attributes
Int n
MatDoub el
bool fail
Detailed Description
Definition at line 3 of file cholesky.h.
Constructor & Destructor Documentation
Cholesky()
Cholesky::Cholesky (MatDoub_I & a) inline
Definition at line 7 of file cholesky.h.
References el, n, and NRmatrix< T >::ncols().
Member Function Documentation
elmult()
void Cholesky::elmult (VecDoub_I & y, VecDoub_O & b) inline
Definition at line 44 of file cholesky.h.
References el, n, and NRvector< T >::size().
elsolve()
void Cholesky::elsolve (VecDoub_I & b, VecDoub_O & y) inline
Definition at line 52 of file cholesky.h.
References el, n, and NRvector< T >::size().
inverse()
void Cholesky::inverse (MatDoub_O & ainv) inline
Definition at line 61 of file cholesky.h.
References el, n, and NRmatrix< T >::resize().
Referenced by KLGalerkinRF::SolveGenEigValProblem().
logdet()
Doub Cholesky::logdet () inline
Definition at line 76 of file cholesky.h.
References el, and n.
solve()
void Cholesky::solve (VecDoub_I & b, VecDoub_O & x) inline
Definition at line 31 of file cholesky.h.
References el, n, and NRvector< T >::size().
Referenced by SolveNR3().
Member Data Documentation
el
MatDoub Cholesky::el
Definition at line 5 of file cholesky.h.
Referenced by Cholesky(), elmult(), elsolve(), inverse(), logdet(), and solve().
fail
bool Cholesky::fail
Definition at line 6 of file cholesky.h.
n
Int Cholesky::n
Definition at line 4 of file cholesky.h.
Referenced by Cholesky(), elmult(), elsolve(), inverse(), logdet(), and solve().
The documentation for this struct was generated from the following file:
src/cholesky.h