DCPROJ: Powell< T > Struct Template Reference
Powell< T > Struct Template Reference
#include <mins_ndim.h>
Public Member Functions
Powell (T &func, const Doub ftoll=3.0e-8)
VecDoub minimize (VecDoub_I &pp)
VecDoub minimize (VecDoub_I &pp, MatDoub_IO &ximat)
Public Member Functions inherited from Linemethod< T >
Linemethod (T &funcc)
Doub linmin ()
Public Attributes
Int iter
Doub fret
const Doub ftol
Public Attributes inherited from Linemethod< T >
VecDoub p
VecDoub xi
T & func
Int n
Detailed Description
template<class T>
struct Powell< T >
Definition at line 164 of file mins_ndim.h.
Constructor & Destructor Documentation
Powell()
template<class T > Powell< T >::Powell (T & func, const Doub ftoll = 3.0e-8) inline
Definition at line 172 of file mins_ndim.h.
Member Function Documentation
minimize() [1/2]
template<class T > VecDoub Powell< T >::minimize (VecDoub_I & pp) inline
Definition at line 174 of file mins_ndim.h.
References Linemethod< T >::n.
minimize() [2/2]
template<class T > VecDoub Powell< T >::minimize (VecDoub_I & pp, MatDoub_IO & ximat) inline
Definition at line 181 of file mins_ndim.h.
References Powell< T >::fret, Powell< T >::ftol, Linemethod< T >::func, Powell< T >::iter, Linemethod< T >::linmin(), Linemethod< T >::n, Linemethod< T >::p, NRvector< T >::resize(), SQR(), and Linemethod< T >::xi.
Member Data Documentation
fret
template<class T > Doub Powell< T >::fret
Definition at line 166 of file mins_ndim.h.
Referenced by Powell< T >::minimize().
ftol
template<class T > const Doub Powell< T >::ftol
Definition at line 171 of file mins_ndim.h.
Referenced by Powell< T >::minimize().
iter
template<class T > Int Powell< T >::iter
Definition at line 165 of file mins_ndim.h.
Referenced by Powell< T >::minimize().
The documentation for this struct was generated from the following file:
src/mins_ndim.h