DCPROJ: Frprmn< T > Struct Template Reference
Frprmn< T > Struct Template Reference
#include <mins_ndim.h>
Public Member Functions
Frprmn (T &funcd, const Doub ftoll=3.0e-8)
VecDoub minimize (VecDoub_I &pp)
Public Member Functions inherited from Linemethod< T >
Linemethod (T &funcc)
Doub linmin ()
Public Attributes
Int iter
Doub fret
const Doub ftol
Public Attributes inherited from Linemethod< T >
VecDoub p
VecDoub xi
T & func
Int n
Detailed Description
template<class T>
struct Frprmn< T >
Definition at line 232 of file mins_ndim.h.
Constructor & Destructor Documentation
Frprmn()
template<class T > Frprmn< T >::Frprmn (T & funcd, const Doub ftoll = 3.0e-8) inline
Definition at line 240 of file mins_ndim.h.
Member Function Documentation
minimize()
template<class T > VecDoub Frprmn< T >::minimize (VecDoub_I & pp) inline
Definition at line 242 of file mins_ndim.h.
References Frprmn< T >::fret, Frprmn< T >::ftol, Linemethod< T >::func, Frprmn< T >::iter, Linemethod< T >::linmin(), MAX(), Linemethod< T >::n, Linemethod< T >::p, NRvector< T >::resize(), and Linemethod< T >::xi.
Member Data Documentation
fret
template<class T > Doub Frprmn< T >::fret
Definition at line 234 of file mins_ndim.h.
Referenced by Frprmn< T >::minimize().
ftol
template<class T > const Doub Frprmn< T >::ftol
Definition at line 239 of file mins_ndim.h.
Referenced by Frprmn< T >::minimize().
iter
template<class T > Int Frprmn< T >::iter
Definition at line 233 of file mins_ndim.h.
Referenced by Frprmn< T >::minimize().
The documentation for this struct was generated from the following file:
src/mins_ndim.h