DCPROJ: LUdcmp Struct Reference
LUdcmp Struct Reference
#include <ludcmp.h>
Public Member Functions
LUdcmp (MatDoub_I &a)
void solve (VecDoub_I &b, VecDoub_O &x)
void solve (MatDoub_I &b, MatDoub_O &x)
void inverse (MatDoub_O &ainv)
Doub det ()
void mprove (VecDoub_I &b, VecDoub_IO &x)
Public Attributes
Int n
MatDoub lu
VecInt indx
Doub d
MatDoub_I & aref
bool fail
Detailed Description
Definition at line 3 of file ludcmp.h.
Constructor & Destructor Documentation
LUdcmp()
LUdcmp::LUdcmp (MatDoub_I & a) inline
Definition at line 18 of file ludcmp.h.
References d, fail, indx, lu, and n.
Member Function Documentation
det()
Doub LUdcmp::det () inline
Definition at line 111 of file ludcmp.h.
References d, lu, and n.
inverse()
void LUdcmp::inverse (MatDoub_O & ainv) inline
Definition at line 101 of file ludcmp.h.
References n, NRmatrix< T >::resize(), and solve().
Referenced by vonmises::closestpointproj().
mprove()
void LUdcmp::mprove (VecDoub_I & b, VecDoub_IO & x) inline
Definition at line 117 of file ludcmp.h.
References aref, n, and solve().
solve() [1/2]
void LUdcmp::solve (MatDoub_I & b, MatDoub_O & x) inline
Definition at line 89 of file ludcmp.h.
References n, NRmatrix< T >::ncols(), NRmatrix< T >::nrows(), and solve().
solve() [2/2]
void LUdcmp::solve (VecDoub_I & b, VecDoub_O & x) inline
Definition at line 64 of file ludcmp.h.
References indx, lu, n, and NRvector< T >::size().
Referenced by inverse(), mprove(), and solve().
Member Data Documentation
aref
MatDoub_I& LUdcmp::aref
Definition at line 15 of file ludcmp.h.
Referenced by mprove().
d
Doub LUdcmp::d
Definition at line 8 of file ludcmp.h.
Referenced by det(), and LUdcmp().
fail
bool LUdcmp::fail
Definition at line 16 of file ludcmp.h.
Referenced by LUdcmp().
indx
VecInt LUdcmp::indx
Definition at line 7 of file ludcmp.h.
Referenced by LUdcmp(), and solve().
lu
MatDoub LUdcmp::lu
Definition at line 6 of file ludcmp.h.
Referenced by det(), LUdcmp(), and solve().
n
Int LUdcmp::n
Definition at line 5 of file ludcmp.h.
Referenced by det(), inverse(), LUdcmp(), mprove(), and solve().
The documentation for this struct was generated from the following file:
src/ludcmp.h