DCPROJ: Unsymmeig Struct Reference
Unsymmeig Struct Reference
#include <eigen_unsym.h>
Public Member Functions
Unsymmeig (MatDoub_I &aa, Bool yesvec=true, Bool hessenb=false)
void balance ()
void balbak ()
void elmhes ()
void eltran ()
void hqr ()
void hqr2 ()
void sort ()
void sortvecs ()
Public Attributes
Int n
MatDoub a
MatDoub zz
VecComplex wri
VecDoub scale
VecInt perm
Bool yesvecs
Bool hessen
Detailed Description
Definition at line 3 of file eigen_unsym.h.
Constructor & Destructor Documentation
Unsymmeig()
Unsymmeig::Unsymmeig (MatDoub_I & aa, Bool yesvec = true, Bool hessenb = false) inline
Definition at line 11 of file eigen_unsym.h.
References balance(), balbak(), elmhes(), eltran(), hessen, hqr(), hqr2(), n, sort(), sortvecs(), yesvecs, and zz.
Member Function Documentation
balance()
void Unsymmeig::balance () inline
Definition at line 30 of file eigen_unsym.h.
References a, n, and scale.
Referenced by Unsymmeig().
balbak()
void Unsymmeig::balbak () inline
Definition at line 68 of file eigen_unsym.h.
References n, scale, and zz.
Referenced by Unsymmeig().
elmhes()
void Unsymmeig::elmhes () inline
Definition at line 74 of file eigen_unsym.h.
References a, n, perm, and SWAP().
Referenced by Unsymmeig().
eltran()
void Unsymmeig::eltran () inline
Definition at line 103 of file eigen_unsym.h.
References a, n, perm, and zz.
Referenced by Unsymmeig().
hqr()
void Unsymmeig::hqr () inline
Definition at line 118 of file eigen_unsym.h.
References a, MAX(), n, SIGN(), and wri.
Referenced by Unsymmeig().
hqr2()
void Unsymmeig::hqr2 () inline
Definition at line 244 of file eigen_unsym.h.
References a, MAX(), n, SIGN(), SQR(), wri, and zz.
Referenced by Unsymmeig().
sort()
void Unsymmeig::sort () inline
Definition at line 520 of file eigen_unsym.h.
References n, and wri.
Referenced by Unsymmeig().
sortvecs()
void Unsymmeig::sortvecs () inline
Definition at line 532 of file eigen_unsym.h.
References n, wri, and zz.
Referenced by Unsymmeig().
Member Data Documentation
a
MatDoub Unsymmeig::a
Definition at line 5 of file eigen_unsym.h.
Referenced by balance(), elmhes(), eltran(), hqr(), and hqr2().
hessen
Bool Unsymmeig::hessen
Definition at line 9 of file eigen_unsym.h.
Referenced by Unsymmeig().
n
Int Unsymmeig::n
Definition at line 4 of file eigen_unsym.h.
Referenced by balance(), balbak(), elmhes(), eltran(), hqr(), hqr2(), sort(), sortvecs(), and Unsymmeig().
perm
VecInt Unsymmeig::perm
Definition at line 8 of file eigen_unsym.h.
Referenced by elmhes(), and eltran().
scale
VecDoub Unsymmeig::scale
Definition at line 7 of file eigen_unsym.h.
Referenced by balance(), and balbak().
wri
VecComplex Unsymmeig::wri
Definition at line 6 of file eigen_unsym.h.
Referenced by hqr(), hqr2(), KLGalerkinRF::SolveGenEigValProblem(), sort(), and sortvecs().
yesvecs
Bool Unsymmeig::yesvecs
Definition at line 9 of file eigen_unsym.h.
Referenced by Unsymmeig().
zz
MatDoub Unsymmeig::zz
Definition at line 5 of file eigen_unsym.h.
Referenced by balbak(), eltran(), hqr2(), KLGalerkinRF::SolveGenEigValProblem(), sortvecs(), and Unsymmeig().
The documentation for this struct was generated from the following file:
src/eigen_unsym.h