DCPROJ: Bracketmethod Struct Reference
Bracketmethod Struct Reference
#include <mins_ndim.h>
Public Member Functions
template<class T >
void bracket (const Doub a, const Doub b, T &func)
void shft2 (Doub &a, Doub &b, const Doub c)
void shft3 (Doub &a, Doub &b, Doub &c, const Doub d)
void mov3 (Doub &a, Doub &b, Doub &c, const Doub d, const Doub e, const Doub f)
Public Attributes
Doub ax
Doub bx
Doub cx
Doub fa
Doub fb
Doub fc
Detailed Description
Definition at line 290 of file mins_ndim.h.
Member Function Documentation
bracket()
template<class T > void Bracketmethod::bracket (const Doub a, const Doub b, T & func) inline
Definition at line 293 of file mins_ndim.h.
References ax, bx, cx, fa, fb, fc, MAX(), shft3(), SIGN(), and SWAP().
Referenced by Linemethod< T >::linmin(), and Dlinemethod< T >::linmin().
mov3()
void Bracketmethod::mov3 (Doub & a, Doub & b, Doub & c, const Doub d, const Doub e, const Doub f) inline
Definition at line 359 of file mins_ndim.h.
Referenced by Dbrent::minimize().
shft2()
void Bracketmethod::shft2 (Doub & a, Doub & b, const Doub c) inline
Definition at line 348 of file mins_ndim.h.
Referenced by Golden::minimize().
shft3()
void Bracketmethod::shft3 (Doub & a, Doub & b, Doub & c, const Doub d) inline
Definition at line 353 of file mins_ndim.h.
Referenced by bracket(), Brent::minimize(), and Golden::minimize().
Member Data Documentation
ax
Doub Bracketmethod::ax
Definition at line 291 of file mins_ndim.h.
Referenced by bracket(), Brent::minimize(), Golden::minimize(), and Dbrent::minimize().
bx
Doub Bracketmethod::bx
Definition at line 291 of file mins_ndim.h.
Referenced by bracket(), Brent::minimize(), Golden::minimize(), and Dbrent::minimize().
cx
Doub Bracketmethod::cx
Definition at line 291 of file mins_ndim.h.
Referenced by bracket(), Brent::minimize(), Golden::minimize(), and Dbrent::minimize().
fa
Doub Bracketmethod::fa
Definition at line 291 of file mins_ndim.h.
Referenced by bracket().
fb
Doub Bracketmethod::fb
Definition at line 291 of file mins_ndim.h.
Referenced by bracket().
fc
Doub Bracketmethod::fc
Definition at line 291 of file mins_ndim.h.
Referenced by bracket().
The documentation for this struct was generated from the following file:
src/mins_ndim.h