DCPROJ: Dlinemethod< T > Struct Template Reference
Dlinemethod< T > Struct Template Reference
#include <mins_ndim.h>
Public Member Functions
Dlinemethod (T &funcc)
Doub linmin ()
Public Attributes
VecDoub p
VecDoub xi
T & func
Int n
Detailed Description
template<class T>
struct Dlinemethod< T >
Definition at line 140 of file mins_ndim.h.
Constructor & Destructor Documentation
Dlinemethod()
template<class T > Dlinemethod< T >::Dlinemethod (T & funcc) inline
Definition at line 145 of file mins_ndim.h.
Member Function Documentation
linmin()
template<class T > Doub Dlinemethod< T >::linmin () inline
Definition at line 146 of file mins_ndim.h.
References Bracketmethod::bracket(), Dbrent::fmin, Dlinemethod< T >::func, Dbrent::minimize(), Dlinemethod< T >::n, Dlinemethod< T >::p, NRvector< T >::size(), and Dlinemethod< T >::xi.
Member Data Documentation
func
template<class T > T& Dlinemethod< T >::func
Definition at line 143 of file mins_ndim.h.
Referenced by Dlinemethod< T >::linmin().
n
template<class T > Int Dlinemethod< T >::n
Definition at line 144 of file mins_ndim.h.
Referenced by Dlinemethod< T >::linmin().
p
template<class T > VecDoub Dlinemethod< T >::p
Definition at line 141 of file mins_ndim.h.
Referenced by Dlinemethod< T >::linmin().
xi
template<class T > VecDoub Dlinemethod< T >::xi
Definition at line 142 of file mins_ndim.h.
Referenced by Dlinemethod< T >::linmin().
The documentation for this struct was generated from the following file:
src/mins_ndim.h