DCPROJ: Brent Struct Reference
Brent Struct Reference
#include <mins_ndim.h>
Public Member Functions
Brent (const Doub toll=3.0e-8)
template<class T >
Doub minimize (T &func)
Brent (const Doub toll=3.0e-8)
template<class T >
Doub minimize (T &func)
Public Member Functions inherited from Bracketmethod
template<class T >
void bracket (const Doub a, const Doub b, T &func)
void shft2 (Doub &a, Doub &b, const Doub c)
void shft3 (Doub &a, Doub &b, Doub &c, const Doub d)
void mov3 (Doub &a, Doub &b, Doub &c, const Doub d, const Doub e, const Doub f)
Public Attributes
Doub xmin
Doub fmin
const Doub tol
Public Attributes inherited from Bracketmethod
Doub ax
Doub bx
Doub cx
Doub fa
Doub fb
Doub fc
Detailed Description
Definition at line 1 of file mins_ndim.h.
Constructor & Destructor Documentation
Brent() [1/2]
Brent::Brent (const Doub toll = 3.0e-8) inline
Definition at line 4 of file mins_ndim.h.
Brent() [2/2]
Brent::Brent (const Doub toll = 3.0e-8) inline
Definition at line 410 of file mins_ndim.h.
Member Function Documentation
minimize() [1/2]
template<class T > Doub Brent::minimize (T & func) inline
Definition at line 6 of file mins_ndim.h.
References Bracketmethod::ax, Bracketmethod::bx, Bracketmethod::cx, fmin, Bracketmethod::shft3(), SIGN(), tol, and xmin.
Referenced by Linemethod< T >::linmin().
minimize() [2/2]
template<class T > Doub Brent::minimize (T & func) inline
Definition at line 412 of file mins_ndim.h.
References Bracketmethod::ax, Bracketmethod::bx, Bracketmethod::cx, fmin, Bracketmethod::shft3(), SIGN(), tol, and xmin.
Member Data Documentation
fmin
Doub Brent::fmin
Definition at line 2 of file mins_ndim.h.
Referenced by Linemethod< T >::linmin(), and minimize().
tol
const Doub Brent::tol
Definition at line 3 of file mins_ndim.h.
Referenced by minimize().
xmin
Doub Brent::xmin
Definition at line 2 of file mins_ndim.h.
Referenced by minimize().
The documentation for this struct was generated from the following file:
src/mins_ndim.h